### PR TITLE
fix(client): add default generic parameters to PrismaClient constructor

### LINKED ISSUE #27894: Prisma 6.14.0 adds breaking change for extending of PrismaClient
### Bug description

After update to Prisma v6.14.0 I face the TS error when I try to extend the PrismaClient:
`TS2508: No base constructor has the specified number of type arguments.`

### Severity

🚨 Critical: Data loss, app crash, security issue

### Reproduction

The simple code causes TS compilation error:
```ts
class PrismaService extends PrismaClient {}
```

Prisma generator defenition:

```prisma
generator client {
  provider        = "prisma-client"
  previewFeatures = ["relationJoins", "driverAdapters", "queryCompiler"]
  output          = "./client"
  moduleFormat    = "cjs"
}
```

### Expected vs. Actual Behavior

I expect PrismaClient to not require additional generics to make TS compile as it was before

### Frequency

Consistently reproducible

### Does this occur in development or production?

Only in development (e.g., CLI tools, migrations, Prisma Studio)

### Is this a regression?

Yes, worked in Prisma v6.13.0, broke in v6.14.0

### Workaround

Making change in `class.ts` (generated by `prisma generate`) from this:

```ts
export interface PrismaClientConstructor {
    /**
   * ## Prisma Client
   * 
   * Type-safe database client for TypeScript
   * @example
   * ```
   * const prisma = new PrismaClient()
   * // Fetch zero or more Customers
   * const customers = await prisma.customer.findMany()
   * ```
   * 
   * Read more in our [docs](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client).
   */

  new <
    Options extends Prisma.PrismaClientOptions,
    LogOpts extends LogOptions<Options>,
    OmitOpts extends Prisma.PrismaClientOptions['omit'] = Options extends { omit: infer U } ? U : Prisma.PrismaClientOptions['omit'],
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
  >(options?: Prisma.Subset<Options, Prisma.PrismaClientOptions> ): PrismaClient<LogOpts, OmitOpts, ExtArgs>
}
```

to this (setting default values for the generics):
```ts
export interface PrismaClientConstructor {
    /**
   * ## Prisma Client
   * 
   * Type-safe database client for TypeScript
   * @example
   * ```
   * const prisma = new PrismaClient()
   * // Fetch zero or more Customers
   * const customers = await prisma.customer.findMany()
   * ```
   * 
   * Read more in our [docs](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client).
   */

  new <
    Options extends Prisma.PrismaClientOptions = Prisma.PrismaClientOptions,
    LogOpts extends LogOptions<Options> = LogOptions<Options>,
    OmitOpts extends Prisma.PrismaClientOptions['omit'] = Options extends { omit: infer U } ? U : Prisma.PrismaClientOptions['omit'],
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
  >(options?: Prisma.Subset<Options, Prisma.PrismaClientOptions> ): PrismaClient<LogOpts, OmitOpts, ExtArgs>
}
```

or as alternative changing from
```ts
class PrismaService extends PrismaClient {}
```
to

```ts
class PrismaService extends PrismaClient<PrismaClientOptions, LogOptions<PrismaClientOptions>> {}
```

### Prisma Schema & Queries

```prisma
// Add relevant schema.prisma snippet
```
```ts
// Add relevant Prisma Client query
```

### Prisma Config

```ts
// Add your `prisma.config.ts`
```

### Logs & Debug Info

```
// Debug logs here
```

### Environment & Setup

- **OS:** 
- **Database:** 
- **Node.js version:** 
I think it is reproducible in any OS with any Node.js version

### Prisma Version

```
// Prisma version output
```
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
prisma                : 6.14.0
@prisma/client        : 6.14.0
Computed binaryTarget : darwin-arm64
Operating System      : darwin
Architecture          : arm64
Node.js               : v22.18.0
TypeScript            : 5.9.2
Query Compiler        : enabled
PSL                   : @prisma/prisma-schema-wasm 6.14.0-25.717184b7b35ea05dfa71a3236b7af656013e1e49
Schema Engine         : schema-engine-cli 717184b7b35ea05dfa71a3236b7af656013e1e49 (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Default Engines Hash  : 717184b7b35ea05dfa71a3236b7af656013e1e49
Studio                : 0.511.0
Preview Features      : driverAdapters, queryCompiler, relationJoins

### PR DESCRIPTION
**Pull request by mag123c**
## Description
Adds default values to PrismaClient generic parameters to allow extending without explicit generics.

## Problem
Previously in v6.14.0, extending PrismaClient resulted in TypeScript error

```typescript
class MyService extends PrismaClient {}
// TS2508: No base constructor has the specified number of type arguments
```

Users had to specify all generic parameters
```typescript
class MyService extends PrismaClient<never, never, false, ExtArgs> {}
```

## Solution

Added default values to constructor generic parameters:
- Options = Prisma.PrismaClientOptions
- LogOpts = never

Now this works without errors:
```typescript
class MyService extends PrismaClient {}
```

## Changes
- Added default generic parameters in PrismaClientConstructor interface
- This is a non-breaking change (only adds defaults to existing generics)
- All existing tests pass

Fixes #27894 Related #27777

### CODE REVIEW

**Comment by hernanistn** [comment]
Working fine here and solved the problem. Thanks!

**Review by aqrln — APPROVED** [review]
Thank you!
