### PR TITLE
fix: use public `@prisma/internals` exports in completion modules

### LINKED ISSUE #29772: @prisma/migrate 7.9.0 requires unpublished @prisma/internals completion module
### Bug description

Importing the published `@prisma/migrate` package at version 7.9.0 fails immediately because its generated CommonJS bundle requires:

```text
@prisma/internals/src/cli/completion-values
```

The published `@prisma/internals` package contains the compiled module under `dist/cli/completion-values.js`, but does not publish the referenced `src/cli/completion-values` path.

This appears related to the tab-completion imports introduced in https://github.com/prisma/prisma/pull/28351.

### Severity

⚠️ Major: Breaks core functionality (e.g., migrations fail)

### Reproduction

```bash
mkdir prisma-migrate-repro
cd prisma-migrate-repro
npm init -y
npm install @prisma/migrate@7.9.0 @prisma/internals@7.9.0
node -e "require('@prisma/migrate')"
```

No database or Prisma schema is required to reproduce the failure.

### Expected vs. Actual Behavior

Expected: `require('@prisma/migrate')` loads the package successfully.

Actual: Node.js throws `MODULE_NOT_FOUND` before any migrate API can be used:

```text
Error: Cannot find module '@prisma/internals/src/cli/completion-values'
Require stack:
- node_modules/@prisma/migrate/dist/chunk-WA2SOLDQ.js
- node_modules/@prisma/migrate/dist/index.js
- [eval]
```

### Frequency

Consistently reproducible

### Does this occur in development or production?

Both development and production

We encountered it in an AWS Lambda that uses `@prisma/migrate` programmatically, and the minimal local reproduction fails identically.

### Is this a regression?

Yes. The same programmatic usage worked with Prisma 7.8.0 and broke after upgrading to 7.9.0.

### Workaround

Either downgrade to Prisma 7.8.0 or create a compatibility shim at `@prisma/internals/src/cli/completion-values.js` that re-exports `@prisma/internals/dist/cli/completion-values.js`.

### Prisma Schema & Queries

Not applicable. The package fails during module loading before a schema, database connection, or query is used.

### Environment & Setup

- **OS:** macOS 26.5 (Darwin 25.5.0), also reproduced in AWS Lambda
- **Database:** Not applicable
- **Node.js version:** v22.17.0 locally; production bundle targets Node.js 24
- **Package manager:** npm 11.9.0

### Prisma Version

```text
prisma               : 7.9.0
@prisma/client       : 7.9.0
@prisma/migrate      : 7.9.0
@prisma/internals    : 7.9.0
Operating System     : darwin
Architecture         : arm64
Node.js              : v22.17.0
TypeScript           : 6.0.3
Query Compiler       : enabled
PSL                  : @prisma/prisma-schema-wasm 7.9.0-1.e922089b7d7502aff4249d5da3420f6fa55fc6ad
Schema Engine        : schema-engine-cli e922089b7d7502aff4249d5da3420f6fa55fc6ad
Default Engines Hash : e922089b7d7502aff4249d5da3420f6fa55fc6ad
Studio               : 0.33.0
```

### PR DESCRIPTION
**Pull request by AmirSa12**
closes #29772

### CODE REVIEW

**Comment by clemens** [comment]
@aqrln Any chance of getting this merged? It's broken in both 7.9.0 and 7.9.1.
