### ISSUE TITLE
Cannot find module '.prisma/client/default' when using custom output with pnpm

### ISSUE THREAD

**Issue by CHC383** [prisma/prisma#25833]
### Bug description

Hi, we are using custom output in our Next.js project:

- Custom output is used because we have multiple DB and thus multiple clients
- The output location is something like `"../node_modules/@prisma/xxx-client"`. I have also tried my own paths inside node_modules like `"../node_modules/@my-path/xxx-client"`, or outside like `../src/generated/prisma/xxx-client"`

I found out this issue while trying to switch from npm to pnpm today.
- While using npm, everything works fine using custom output path `"../node_modules/@prisma/xxx-client"`. A client (dummy?) is generated in `node_modules/.prisma/client` along with other actual custom output clients, and we run the application in both docker (prod via `next build`) and non-docker (dev mode through `next dev`) environments successfully
- While using pnpm, I tried all the different path setups above, and got "Error: Cannot find module '.prisma/client/default'" during runtime in `next dev` mode, but the docker mode was working fine

Specifically, the error stack trace is
<details>

<summary>stack trace</summary>

```
err: {
      "type": "Error",
      "message": "Cannot find module '.prisma/client/default'\nRequire stack:\n- /Users/<user>/workspaces/<project>/node_modules/.pnpm/@prisma+client@6.0.1_prisma@6.0.1/node_modules/@prisma/client/default.js\n- /Users/<user>/workspaces/<project>/node_modules/.pnpm/prisma-extension-nested-operations@1.0.1_patch_hash=kcg55sqsdo6qszmzrogennqvvm_@prisma+client@6.0.1_prisma@6.0.1_/node_modules/prisma-extension-nested-operations/dist/lib/utils/cloneArgs.js\n- /Users/<user>/workspaces/<project>/node_modules/.pnpm/prisma-extension-nested-operations@1.0.1_patch_hash=kcg55sqsdo6qszmzrogennqvvm_@prisma+client@6.0.1_prisma@6.0.1_/node_modules/prisma-extension-nested-operations/dist/lib/utils/execution.js\n- /Users/<user>/workspaces/<project>/node_modules/.pnpm/prisma-extension-nested-operations@1.0.1_patch_hash=kcg55sqsdo6qszmzrogennqvvm_@prisma+client@6.0.1_prisma@6.0.1_/node_modules/prisma-extension-nested-operations/dist/lib/nestedOperations.js\n- /Users/<user>/workspaces/<project>/node_modules/.pnpm/prisma-extension-nested-operations@1.0.1_patch_hash=kcg55sqsdo6qszmzrogennqvvm_@prisma+client@6.0.1_prisma@6.0.1_/node_modules/prisma-extension-nested-operations/dist/index.js\n- /Users/<user>/workspaces/<project>/node_modules/.pnpm/prisma-extension-soft-delete@2.0.0_patch_hash=uchgi7s6hw4mcxfjlogooeapja_@prisma+client@6.0.1_prisma@6.0.1_/node_modules/prisma-extension-soft-delete/dist/lib/createSoftDeleteExtension.js\n- /Users/<user>/workspaces/<project>/node_modules/.pnpm/prisma-extension-soft-delete@2.0.0_patch_hash=uchgi7s6hw4mcxfjlogooeapja_@prisma+client@6.0.1_prisma@6.0.1_/node_modules/prisma-extension-soft-delete/dist/index.js\n- /Users/<user>/workspaces/<project>/.next/server/pages/api/trpc/[trpc].js\n- /Users/<user>/workspaces/<project>/node_modules/.pnpm/next@14.2.20_@babel+core@7.26.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/future/helpers/module-loader/node-module-loader.js\n- /Users/<user>/workspaces/<project>/node_modules/.pnpm/next@14.2.20_@babel+core@7.26.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/future/helpers/module-loader/route-module-loader.js\n- /Users/<user>/workspaces/<project>/node_modules/.pnpm/next@14.2.20_@babel+core@7.26.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js\n- /Users/<user>/workspaces/<project>/node_modules/.pnpm/next@14.2.20_@babel+core@7.26.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/dev/next-dev-server.js\n- /Users/<user>/workspaces/<project>/node_modules/.pnpm/next@14.2.20_@babel+core@7.26.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next.js\n- /Users/<user>/workspaces/<project>/node_modules/.pnpm/next@14.2.20_@babel+core@7.26.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/start-server.js",
      "stack":
          Error: Cannot find module '.prisma/client/default'
          Require stack:
          - /Users/<user>/workspaces/<project>/node_modules/.pnpm/@prisma+client@6.0.1_prisma@6.0.1/node_modules/@prisma/client/default.js
          - /Users/<user>/workspaces/<project>/node_modules/.pnpm/prisma-extension-nested-operations@1.0.1_patch_hash=kcg55sqsdo6qszmzrogennqvvm_@prisma+client@6.0.1_prisma@6.0.1_/node_modules/prisma-extension-nested-operations/dist/lib/utils/cloneArgs.js
          - /Users/<user>/workspaces/<project>/node_modules/.pnpm/prisma-extension-nested-operations@1.0.1_patch_hash=kcg55sqsdo6qszmzrogennqvvm_@prisma+client@6.0.1_prisma@6.0.1_/node_modules/prisma-extension-nested-operations/dist/lib/utils/execution.js
          - /Users/<user>/workspaces/<project>/node_modules/.pnpm/prisma-extension-nested-operations@1.0.1_patch_hash=kcg55sqsdo6qszmzrogennqvvm_@prisma+client@6.0.1_prisma@6.0.1_/node_modules/prisma-extension-nested-operations/dist/lib/nestedOperations.js
          - /Users/<user>/workspaces/<project>/node_modules/.pnpm/prisma-extension-nested-operations@1.0.1_patch_hash=kcg55sqsdo6qszmzrogennqvvm_@prisma+client@6.0.1_prisma@6.0.1_/node_modules/prisma-extension-nested-operations/dist/index.js
          - /Users/<user>/workspaces/<project>/node_modules/.pnpm/prisma-extension-soft-delete@2.0.0_patch_hash=uchgi7s6hw4mcxfjlogooeapja_@prisma+client@6.0.1_prisma@6.0.1_/node_modules/prisma-extension-soft-delete/dist/lib/createSoftDeleteExtension.js
          - /Users/<user>/workspaces/<project>/node_modules/.pnpm/prisma-extension-soft-delete@2.0.0_patch_hash=uchgi7s6hw4mcxfjlogooeapja_@prisma+client@6.0.1_prisma@6.0.1_/node_modules/prisma-extension-soft-delete/dist/index.js
          - /Users/<user>/workspaces/<project>/.next/server/pages/api/trpc/[trpc].js
          - /Users/<user>/workspaces/<project>/node_modules/.pnpm/next@14.2.20_@babel+core@7.26.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/future/helpers/module-loader/node-module-loader.js
          - /Users/<user>/workspaces/<project>/node_modules/.pnpm/next@14.2.20_@babel+core@7.26.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/future/helpers/module-loader/route-module-loader.js
          - /Users/<user>/workspaces/<project>/node_modules/.pnpm/next@14.2.20_@babel+core@7.26.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js
          - /Users/<user>/workspaces/<project>/node_modules/.pnpm/next@14.2.20_@babel+core@7.26.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/dev/next-dev-server.js
          - /Users/<user>/workspaces/<project>/node_modules/.pnpm/next@14.2.20_@babel+core@7.26.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next.js
          - /Users/<user>/workspaces/<project>/node_modules/.pnpm/next@14.2.20_@babel+core@7.26.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/start-server.js
              at Function.<anonymous> (node:internal/modules/cjs/loader:1249:15)
              at /Users/<user>/workspaces/<project>/node_modules/.pnpm/next@14.2.20_@babel+core@7.26.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/require-hook.js:55:36
              at Function._load (node:internal/modules/cjs/loader:1075:27)
              at TracingChannel.traceSync (node:diagnostics_channel:315:14)
              at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
              at Module.<anonymous> (node:internal/modules/cjs/loader:1340:12)
              at mod.require (/Users/<user>/workspaces/<project>/node_modules/.pnpm/next@14.2.20_@babel+core@7.26.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/require-hook.js:65:28)
              at require (node:internal/modules/helpers:141:16)
              at Object.<anonymous> (/Users/<user>/workspaces/<project>/node_modules/.pnpm/@prisma+client@6.0.1_prisma@6.0.1/node_modules/@prisma/client/default.js:2:6)
              at Module._compile (node:internal/modules/cjs/loader:1546:14)
              at Object..js (node:internal/modules/cjs/loader:1689:10)
              at Module.load (node:internal/modules/cjs/loader:1318:32)
              at Function._load (node:internal/modules/cjs/loader:1128:12)
              at TracingChannel.traceSync (node:diagnostics_channel:315:14)
              at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
      "code": "MODULE_NOT_FOUND",
      "requireStack": [
        "/Users/<user>/workspaces/<project>/node_modules/.pnpm/@prisma+client@6.0.1_prisma@6.0.1/node_modules/@prisma/client/default.js",
        "/Users/<user>/workspaces/<project>/node_modules/.pnpm/prisma-extension-nested-operations@1.0.1_patch_hash=kcg55sqsdo6qszmzrogennqvvm_@prisma+client@6.0.1_prisma@6.0.1_/node_modules/prisma-extension-nested-operations/dist/lib/utils/cloneArgs.js",
        "/Users/<user>/workspaces/<project>/node_modules/.pnpm/prisma-extension-nested-operations@1.0.1_patch_hash=kcg55sqsdo6qszmzrogennqvvm_@prisma+client@6.0.1_prisma@6.0.1_/node_modules/prisma-extension-nested-operations/dist/lib/utils/execution.js",
        "/Users/<user>/workspaces/<project>/node_modules/.pnpm/prisma-extension-nested-operations@1.0.1_patch_hash=kcg55sqsdo6qszmzrogennqvvm_@prisma+client@6.0.1_prisma@6.0.1_/node_modules/prisma-extension-nested-operations/dist/lib/nestedOperations.js",
        "/Users/<user>/workspaces/<project>/node_modules/.pnpm/prisma-extension-nested-operations@1.0.1_patch_hash=kcg55sqsdo6qszmzrogennqvvm_@prisma+client@6.0.1_prisma@6.0.1_/node_modules/prisma-extension-nested-operations/dist/index.js",
        "/Users/<user>/workspaces/<project>/node_modules/.pnpm/prisma-extension-soft-delete@2.0.0_patch_hash=uchgi7s6hw4mcxfjlogooeapja_@prisma+client@6.0.1_prisma@6.0.1_/node_modules/prisma-extension-soft-delete/dist/lib/createSoftDeleteExtension.js",
        "/Users/<user>/workspaces/<project>/node_modules/.pnpm/prisma-extension-soft-delete@2.0.0_patch_hash=uchgi7s6hw4mcxfjlogooeapja_@prisma+client@6.0.1_prisma@6.0.1_/node_modules/prisma-extension-soft-delete/dist/index.js",
        "/Users/<user>/workspaces/<project>/.next/server/pages/api/trpc/[trpc].js",
        "/Users/<user>/workspaces/<project>/node_modules/.pnpm/next@14.2.20_@babel+core@7.26.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/future/helpers/module-loader/node-module-loader.js",
        "/Users/<user>/workspaces/<project>/node_modules/.pnpm/next@14.2.20_@babel+core@7.26.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/future/helpers/module-loader/route-module-loader.js",
        "/Users/<user>/workspaces/<project>/node_modules/.pnpm/next@14.2.20_@babel+core@7.26.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js",
        "/Users/<user>/workspaces/<project>/node_modules/.pnpm/next@14.2.20_@babel+core@7.26.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/dev/next-dev-server.js",
        "/Users/<user>/workspaces/<project>/node_modules/.pnpm/next@14.2.20_@babel+core@7.26.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next.js",
        "/Users/<user>/workspaces/<project>/node_modules/.pnpm/next@14.2.20_@babel+core@7.26.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/start-server.js"
      ]
    }
```

</details>

I have searched around in the issues, discussions and on Google, but haven't found the exact same issue or details as mine.  Here are some findings:
- The error is due to the import `...require('.prisma/client/default')` in `@prisma/client/default.js`
- With npm, `node_modules/.prisma/client/default` is generated even if I am using custom paths, so the import works fine
- With pnpm, it is known that `.prisma/client` won't exist in `node_modules`, but it is also not in `node_modules/.pnpm/@prisma+client@xxx/node_modules/`
- With pnpm, the docker mode works fine, maybe things are bundled differently and properly.

To me this seems to be a bug, as `@prisma/client/default.js` always imports from `.prisma/client/default` (does it?), and a dummy client is properly generated in npm, but not in pnpm.

### How to reproduce

1. Create any code integrate with Prisma
2. Create a Prisma schema with custom output path
3. Use pnpm to install dependencies
4. Run Next.js dev mode `pnpm dev`

--- below is the setup closed to mine ---

1. Create a Next.js project
2. Set up Prisma
3. Import Prisma client in the code that will be run when running Next.js application
4. Create a Prisma schema with custom output path
5. Use pnpm to install dependencies
6. Run Next.js dev mode `pnpm dev`

### Expected behavior

Prisma runs fine with pnpm

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
  output   = "../node_modules/@prisma/xxx-client"
}
...
```

```ts
import "@prisma/xxx-client"
```

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: v22.11.0
- pnpm version: v9.15.0

### Prisma Version

```
prisma                  : 6.0.1
@prisma/client          : 6.0.1
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v22.11.0
Query Engine (Node-API) : libquery-engine 5dbef10bdbfb579e07d35cc85fb1518d357cb99e (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 5dbef10bdbfb579e07d35cc85fb1518d357cb99e (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.23.0-27.5dbef10bdbfb579e07d35cc85fb1518d357cb99e
Default Engines Hash    : 5dbef10bdbfb579e07d35cc85fb1518d357cb99e
Studio                  : 0.503.0
```

**Comment by ErikYu** [comment]
Meeting the same issue. And i find that pnpm works fine with prisma@5.8.1 and @prisma/client@5.8.1。when i update to 5.9.0, it is broken.

**Comment by ludralph** [comment]
Hi @CHC383 and @ErikYu 

Using the custom output path in my schema.prisma file
```prisma
generator client {
  provider = "prisma-client-js"
   output   = "../node_modules/@prisma/xxx-client"
}
```
then running the command on the terminal to generate the prisma client
```
 pnpm exec prisma generate
```
and importing it in my script
```js
const { PrismaClient } = require("./node_modules/@prisma/xxx-client");
```
successfully execute without throwing the error you mentioned.

Can you share the repository so I can investigate further?

This works well on Prisma version 5.9.0 and on 6.0.1

**Comment by ErikYu** [comment]
Hello @ludralph  Thanks for your response. The difference it that i am using 
`output   = "../node_modules/@prisma/client/xxx"`
instead of 
`output   = "../node_modules/@prisma/xxx-client"`.

The previous code does not work in new versions. But anyway after I changed it into the second way, the issue disappears.
Thank you again.

**Comment by shray-sharma** [comment]
Running into this exact same issue using Prisma v5.22.0 with PNPM and NX. It runs when using NPM due to the `.prisma` folder being created but fails when using pnpm for the same reasons as above.

**Comment by shray-sharma** [comment]
@ErikYu have you tried running `pnpm store prune` before installing? We've been just trying anything we could think of to get this working and that seems to solve it. It's intermittent so it'll break again sometimes, but removing `node_modules`, running `pnpm store prune`, and then reinstalling gets it up and running again.

The only difference we could find is that the install step after pruning executes the post-install hook for the Prisma client, which we didn't see it doing before pruning.

Hopefully this works for you as well!

**Comment by huxianghe** [comment]
Node version 22.14.0, pnpm version 9.x, multiple schemas, after running nest start --watch, it always throws an error: Error: Cannot find module '.prisma/client/default' Because the .prisma package was not generated, I eventually switched to npm. It's been so exhausting.

**Comment by wmadden** [comment]
Hi everyone,

This problem is caused by pnpm which in recent versions will not run NPM postinstall lifecycle hooks, which are responsible for triggering `prisma generate` after you run `pnpm install`.

The solution is for you to run `prisma generate` explicitly, wherever in your CI or dev workflow is most convenient for you.

These postinstall hooks will be removed from an upcoming version of Prisma because they flake under so many different circumstances (like this).

**Comment by subvertallchris** [comment]
I understand this is an issue with pnpm, but is it possible there is some additional incompatibility/issue with using client extensions? I'm using the [field encryption extension](https://github.com/47ng/prisma-field-encryption) and running into this error since moving to pnpm. I followed the instructions for workspace setup from [this prisma page](https://www.prisma.io/docs/guides/turborepo). Perhaps I'm still running something in the wrong order?

**Comment by utmishra** [comment]
Since `pnpm v10`, there's a flag to approve `postinstall` for specific packages (otherwise they don't run). Add this to your `package.json`:
```
"pnpm": {
    "onlyBuiltDependencies": [
        "@prisma/client"
    ]
}
```
OR try: [`pnpm approve-builds`](https://pnpm.io/cli/approve-builds), 

Also, CI tools (like Vercel) may cache dependencies, so always better to add `prisma generate` before the build process.

**Comment by Dinuda** [comment]
> Since `pnpm v10`, there's a flag to approve `postinstall` for specific packages (otherwise they don't run). Add this to your `package.json`:
> 
> ```
> "pnpm": {
>     "onlyBuiltDependencies": [
>         "@prisma/client"
>     ]
> }
> ```
> 
> OR try: [`pnpm approve-builds`](https://pnpm.io/cli/approve-builds),
> 
> Also, CI tools (like Vercel) may cache dependencies, so always better to add `prisma generate` before the build process.

For anyone else, this solution works!

**Comment by rafeyhusain** [comment]
I am struggling with the same issue with 

`"@prisma/client": "^6.16.2",`
`"prisma": "^6.17.1", `

I am building Dockerfile `FROM node:20.19.6-alpine AS base`

I am using Nx framework and I do `generate` and then `build` my auth-service which uses `PrismaClient`, but still no use.

```
RUN npm install -g pnpm && \ 
    npx nx run contentwing-db:generate && \
    npx nx build auth-service
```

On Alpine linux it was generating in a strange folder

```
/node_modules/.pnpm/@prisma+client@6.19.0_prisma@6.19.0_typescript@5.9.2__typescript@5.9.2/node_modules/@prisma/client/
```

instead of `/node_modules/@prisma/client/`

My `schema.prisma` is simple

```
generator client {
  provider = "prisma-client-js"
  output=<Any thing here was causing a problem in Linux and Windows>
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
  schemas  = ["cw"]
}

enum tenant_type {
  system
  customer

  @@map("tenant_type")
  @@schema("cw")
}

// other models
```

The issue turns out to be these 2 commented lines. Once I commented them out, `PrismaClient` started to work and no more errors occurred.


```
FROM base AS runner
WORKDIR /app

COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/pnpm-lock.yaml ./pnpm-lock.yaml

# This was causing problem on Linux
# RUN npm install -g pnpm && \
#     pnpm install --frozen-lockfile --prod
```

and in Typescript also worked both on `Windows 11` and `Linux 20.19.6-alpine`

```
import { PrismaClient } from '@prisma/client';
import { DbCore } from '@lib/db-core';
```

**Comment by CHC383** [comment]
@rafeyhusain Prisma <= v6 runs post-install hooks to generate the additional client files (`.prisma/client`) outside of its module folder, which causes problems especially for pnpm. Not sure what's your exact cause, but here are some general suggestions:
1. Upgrade to v7 which doesn't run the implicit post-install scripts (see [release notes](https://github.com/prisma/prisma/releases/tag/7.0.0) and https://github.com/prisma/prisma/commit/df115166abf79abe930d51aefa83ea4397b0d7ed). Also you might want to switch to `prisma-client` if possible, as `prisma-client-js` is deprecated and might not get enough resources on fixing things.
2. If you stick with Prisma v6, try:
    - Approve post-install scripts for specific packages as [mentioned above](https://github.com/prisma/prisma/issues/25833#issuecomment-2724844267). You could figure out the exact list of packages through pnpm install logs in your docker build.
        ```yaml
        # pnpm-workspace.yaml
        onlyBuiltDependencies:
          - "@prisma/client"
        ```
    - The approval above would fix the fresh install case. For the case where `node_modules` folder is deleted and recreated through `pnpm install`, pnpm side cache needs to be disabled. See https://github.com/prisma/prisma/issues/27419
        ```yaml
        # pnpm-workspace.yaml
        sideEffectsCache: False
        ```
