### ISSUE TITLE
Real Time Updates Using Subscriptions not working in Prisma 1.8

### ISSUE THREAD

**Issue by dsoraluz-carecloud** [prisma/prisma#2551]
When implementing real time updates using subscriptions, the following error is thrown when using subscribeToMore(...) on a prop that has been wrapped with the graphql container much like it is laid out in this resource: https://www.howtographql.com/react-apollo/8-subscriptions/ 

The subscription request throws the following error:

`Unhandled GraphQL subscription error TypeError: this.subscriptionClient.request is not a function`

Upon inspecting the flow of the request, I am able to verify that the request is sent through the hybrid link used in the apollo client and what is parsed by the split function is the following :

`{"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"subscription","variableDefinitions":[],"directives":[],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","alias":null,"name":{"kind":"Name","value":"Agent"},"arguments":[],"directives":[],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","alias":null,"name":{"kind":"Name","value":"mutation"},"arguments":[],"directives":[],"selectionSet":null},{"kind":"Field","alias":null,"name":{"kind":"Name","value":"node"},"arguments":[],"directives":[],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","alias":null,"name":{"kind":"Name","value":"id"},"arguments":[],"directives":[],"selectionSet":null},{"kind":"Field","alias":null,"name":{"kind":"Name","value":"name"},"arguments":[],"directives":[],"selectionSet":null},{"kind":"Field","alias":null,"name":{"kind":"Name","value":"status"},"arguments":[],"directives":[],"selectionSet":null},{"kind":"Field","name":{"kind":"Name","value":"__typename"}}]}},{"kind":"Field","name":{"kind":"Name","value":"__typename"}}]}}]}}],"loc":{"start":0,"end":185,"source":{"body":"\n \n subscription{\n Agent{\n mutation\n node {\n id\n name\n status\n }\n }\n }\n\n ","name":"GraphQL"}}}`

Also the Web Socket created returns the following when console logged:

`{"subscriptionClient":{"connectionParams":{"authToken":"AUTH_TOKEN"},"url":"ws://localhost:4466","subscriptions":{},"maxId":0,"subscriptionTimeout":5000,"waitingSubscriptions":{},"unsentMessagesQueue":[],"reconnect":true,"reconnectSubscriptions":{},"reconnecting":false,"reconnectionAttempts":null,"backoff":{"ms":100,"max":10000,"factor":2,"jitter":0.5,"attempts":0},"eventEmitter":{"_events":{},"_eventsCount":0},"client":{}}} `

Can someone help troubleshoot?

**Comment by marktani** [comment]
Thanks for opening this report, @dsoraluz-carecloud!

From your description it sounds like this might be a bug in Apollo Client.
Can you share a small code base that show cases this issue, so we can start looking closer into this problem? 🙂

**Comment by dsoraluz-carecloud** [comment]
Yes, here is a snippet that should help with the debugging...

**Note**: The client application is built in React.

Apollo Client set up: 
```
import { ApolloLink, ApolloClient, InMemoryCache, split } from 'apollo-client-preset';
import { WebSocketLink } from 'apollo-link-ws'
import { getMainDefinition } from 'apollo-utilities'
import { createHttpLink } from 'apollo-link-http';
import { setContext } from 'apollo-link-context';
import fetch from 'isomorphic-fetch';

const httpLink = createHttpLink({
  uri: 'http://localhost:4000',  
  fetch,
});

const authLink = setContext((_, { headers }) => {
  const token = localStorage.getItem('token');
  return {
    headers: {
      ...headers,
      authorization: token ? `Bearer ${token}` : null,
    },
  };
});

const httpLinkWithAuthToken = authLink.concat(httpLink);

const wsLink = new WebSocketLink({
  uri: `ws://localhost:4466`,
  options: {
    reconnect: true,
    connectionParams: {
      authToken: localStorage.getItem('token'),
    }
  }
})

const link = split(
  ({ query }) => {
    const { kind, operation } = getMainDefinition(query)
    return kind === 'OperationDefinition' && operation === 'subscription'
  },
  wsLink,
  httpLinkWithAuthToken,
)

const client = new ApolloClient({
  link,
  cache: new InMemoryCache(),
});

export default client;
```

Then Apollo Client is then imported to the component in the root index file of the application:

```
// Absolute Imports
import React from 'react';
import { render } from 'react-dom';
import { Provider } from 'react-redux';
import { ApolloProvider } from 'react-apollo';
// Relative Imports
import Store from './store';
import ApolloClient from './graphql/ApolloClient';
import MainRouter from './MainRouterComponent';

render(
.
.
.
      <ApolloProvider client={ApolloClient}>
        <Provider store={Store}>
          <MainRouter />
        </Provider>
      </ApolloProvider>
.
.
.
  document.getElementById('root'),
);
```

This makes the Apollo Client available to application from the root level.

The subscription is then being invoked in a component like so:
```
class LoginContainer extends Component {
.
.
.
loginUser = async e => {
    try {
     // Handle login, authenticate user, and save token and load initial data
      this.loadInitialData();
    } catch (error) {
     // Handle error if any 
    }
  };
};
.
.
.
loadInitialData = async _ => {
    try {
      const {
        fetchInitialData,
      } = this.props;
      // Fetch initial data and parse response. 
     // Attempt subscription request
     this.subscribeToAgents(fetchInitialData);
    } catch (error) {
      // Handle error if any
    }
  };

subscribeToAgents = fetchInitialData => {
    fetchInitialData.subscribeToMore({
      document: gql`
    subscription{
        Agent{
            mutation
            node {
                id
                name
                status
            }
        }
    }
`,
      updateQuery: (previous, { subscriptionData }) => {
        // Do something with response data
      },
    });
  };
.
.
.
const enhancer = compose(
  withRouter,
  withApollo,
  connect(mapStateToProps, mapDispatchToProps),
  graphql(FetchInitialData, {
    name: 'fetchInitialData',
    options: ({ contentStore: { start, end } }) => ({ variables: { start, end } }),
  }),
);

export default enhancer(LoginContainer);
```

FetchInitialData is a query that looks like the following:
```
const FetchInitialData = gql`
    query fetchInitialData($start: DateTime!, $end: DateTime!) {
        fetchInitialData(start: $start, end: $end)
    }
`;
```

**Somethings I have been able to inspect:**

The request is sent through the hybrid link used in the apollo client and what is parsed by the split function is the following :
```
{"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"subscription","variableDefinitions":[],"directives":[],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","alias":null,"name":{"kind":"Name","value":"Agent"},"arguments":[],"directives":[],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","alias":null,"name":{"kind":"Name","value":"mutation"},"arguments":[],"directives":[],"selectionSet":null},{"kind":"Field","alias":null,"name":{"kind":"Name","value":"node"},"arguments":[],"directives":[],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","alias":null,"name":{"kind":"Name","value":"id"},"arguments":[],"directives":[],"selectionSet":null},{"kind":"Field","alias":null,"name":{"kind":"Name","value":"name"},"arguments":[],"directives":[],"selectionSet":null},{"kind":"Field","alias":null,"name":{"kind":"Name","value":"status"},"arguments":[],"directives":[],"selectionSet":null},{"kind":"Field","name":{"kind":"Name","value":"__typename"}}]}},{"kind":"Field","name":{"kind":"Name","value":"__typename"}}]}}]}}],"loc":{"start":0,"end":185,"source":{"body":"\n \n subscription{\n Agent{\n mutation\n node {\n id\n name\n status\n }\n }\n }\n\n ","name":"GraphQL"}}}
```
Also the Web Socket created returns the following when console logged:
```
{"subscriptionClient":{"connectionParams":{"authToken":"AUTH_TOKEN"},"url":"ws://localhost:4466","subscriptions":{},"maxId":0,"subscriptionTimeout":5000,"waitingSubscriptions":{},"unsentMessagesQueue":[],"reconnect":true,"reconnectSubscriptions":{},"reconnecting":false,"reconnectionAttempts":null,"backoff":{"ms":100,"max":10000,"factor":2,"jitter":0.5,"attempts":0},"eventEmitter":{"_events":{},"_eventsCount":0},"client":{}}}
```

My apologies if the above is any eyesore but I feel it includes all of the  info that you need to understand the case. I hope this sends you in the right direction.

**Comment by marktani** [comment]
Hey @dsoraluz-carecloud, can you prepare a small project in form of a GitHub repository including an instruction of steps to follow to end up with the error message?

**Comment by dsoraluz-carecloud** [comment]
@marktani Yes, I will prepare that now.
