### ISSUE TITLE
Prisma 6.6.0 TypeError: __banner_node_url

### ISSUE THREAD

**Issue by jjrise** [prisma/prisma#26897]
### Bug description

I upgraded to prisma 6.6.0 and getting this error randomly this morning in my browser. This is specific to 6.6.0 and going back to 6.5.0 is fine again.

I'm using Bun with a turbo monorepo

```
generator client {
    provider     = "prisma-client" // no `-js` at the end
    output       = "./generated/prisma" // `output` is required
    moduleFormat = "esm" // or `"cjs"` for CommonJS
}
```

browser error:
```
@prisma_client_runtime_library.js?v=16686fa7:135 Uncaught (in promise) TypeError: __banner_node_url.
```

### Severity

⚠️ Major: Breaks core functionality (e.g., migrations fail)

### Reproduction

upgraded from 6.5.0 and applied the new generator 

### Expected vs. Actual Behavior

expected to see new 6.6.0 behavior

### Frequency

Consistently reproducible

### Does this occur in development or production?

Both development and production

### Is this a regression?

"Yes, last worked in Prisma 6.5.0, broke in 6.6.0"

### Prisma Schema & Queries

```prisma
// Add relevant schema.prisma snippet
```
```ts
// Add relevant Prisma Client query
```

### Logs & Debug Info

```
// Debug logs here
```

### Environment & Setup

- **OS:** 
- **Database:** 
- **Node.js version:** 

### Prisma Version

```
// Prisma version output
```

**Comment by empirium-steve** [comment]
I am seeing a similar error after updating to 6.6.0. 

Browsers error: 

```
Uncaught TypeError: __banner_node_url.fileURLToPath is not a function at @prisma_client_runtime_library.js?v=84dfa45b:151:36
```

```
generator client {
  provider        = "prisma-client"
  output          = "./generated/prisma"
  previewFeatures = ["prismaSchemaFolder"]
  moduleFormat    = "esm"
}
```

**Comment by nurul3101** [comment]
Hey @jjrise, can you please provide a minimal reproduction repository for us to confirm this bug?

@empirium-steve Are you also using monorepo with Tanstack start?

**Comment by empirium-steve** [comment]
@nurul3101 My apologies, using monorepo, yarn with React Router version 7, framework mode.

**Comment by manuel-84** [comment]
I'm having the same problem with latest Nuxt when I try to import from the generated client 6.6.0

`import { UserRole } from 'prisma/client'` or `import { UserRole } from '@/prisma/client'`

with this config

```
generator client {
  provider        = "prisma-client"
  moduleFormat    = "esm"
  output          = "./client"
  previewFeatures = ["fullTextSearchPostgres"]
}
```

**Comment by jjrise** [comment]
> I'm having the same problem with latest Nuxt when I try to import from the generated client 6.6.0
> 
> `import { UserRole } from 'prisma/client'` or `import { UserRole } from '@/prisma/client'`
> 
> with this config
> 
> ```
> generator client {
>   provider        = "prisma-client"
>   moduleFormat    = "esm"
>   output          = "./client"
>   previewFeatures = ["fullTextSearchPostgres"]
> }
> ```

historically I've had a lot of bizarre issues with Prisma when using the enums in the frontend for types.... I'm assuming UserRole is an enum in your example? I have lots of enums in my Prisma project that I use in my frontend code.

**Comment by manuel-84** [comment]
@jjrise yes it's a enum

**Comment by theskillwithin** [comment]
I am getting the same problem.

in the past this fixed for me
```
export default defineConfig({
  plugins: [reactRouterDevTools(), reactRouter(), tsconfigPaths()],
  resolve: {
    alias: {
      ".prisma/client/index-browser":
        "./node_modules/.prisma/client/index-browser.js",
    },
  },
});

```

not sure if its the same problem, but the same pages break now on 6.6 that fix fixed prev to 6.6

**Comment by FGoessler** [comment]
As you all seem to use the new `prisma-client` generator that is in early access: In the upcoming 6.7.0 we introduce a file splitting for the new generator that will make all user defined enums available in a dedicated file. You can then import this single file `enums.ts` file from the generated output.

The currently generated output in 6.6.0 in the new generator is not suitable to be used in browser environments as is.

**Comment by wsw70** [comment]
I confirm that I get this error when adding 

```typescript
import { mealTimes } from '#imports'
```

where 

```
(alias) const mealTimes: Record<$Enums.MealType, String>
```

Environment: Nuxt 3 with native Prisma installation (not the Nuxt module)

**Comment by jjrise** [comment]
well I'm doubly confused now.... I got rid of all my enum imports (client and server side) and updated to 6.7 with esm and still getting the same error

```
Uncaught (in promise) TypeError: __banner_node_url.fileURLToPath is not a function
    at @prisma_client_runtime_library.js?v=47d97b54:128:36
```

**Comment by wsw70** [comment]
> well I'm doubly confused now.... I got rid of all my enum imports (client and server side) and updated to 6.7 with esm and still getting the same error
> 
> ```
> Uncaught (in promise) TypeError: __banner_node_url.fileURLToPath is not a function
>     at @prisma_client_runtime_library.js?v=47d97b54:128:36
> ```

Same here, I made the mistake of adding an enum, then removed all traces and I am back with this error.
I see the generated `enum.ts` file but there is not really anything to import because the enum is not used.

**Comment by wsw70** [comment]
@FGoessler it must be something else.

I completely removed all enums from my code (notably from `prisma/schema.prisma`) and the errors is back. I removed `.nuxt` and `generated` as well to start from scratch (and upgraded to 6.7.0)

**Comment by wsw70** [comment]
> "Downgrading to Prisma 6.5.0 fixes it"

@jjrise do you lose something major when downgrading?

**Comment by wsw70** [comment]
I had a look at the place where the problem occurs and this is at 

```
var __filename = __banner_node_url.fileURLToPath(import.meta.url);
var __dirname = __banner_node_path.dirname(__filename);
```

This is suspiciously close to the issues with `__dirname` at https://github.com/prisma/prisma/issues/20702

**Comment by cjbland** [comment]
My issue here was that I was including prima code in my client bundle. I specifically had some constants exported from a file that was handling my database interactions. I moved the constants into a different file that I then import from and then these errors went away. vite complained about `node:url` being included in the client bundle which sent me down the path to find this.

**Comment by FGoessler** [comment]
Are you folks trying to import the types into frontend code which has no knowledge of node specific things like file access? 🤔 

If you are barely interested in the types of certain objects and enums you can starting with Prisma 6.7.0 and the new generator import directly from a specific model file. E.g. `import { type UserModel } from '~/generated/prisma/models/User';`.

Does this help?

**Comment by jjrise** [comment]
Mine ultimately was due to the same thing as @cjbland where my prisma exports (prisma client etc) were included in the client bundle. I am using a turbo monorepo and with 6.10 had to split the exports so that I wasn't exporting the prisma client and types in the same file. 

```
{
  "name": "@acme/db",
  "version": "0.1.0",
  "main": "index.ts",
  "type": "module",
  "exports": {
    ".": "./index.ts",
    "./types": "./types.ts",
    "./enums": "./enums.ts"
  },
```

**Comment by jkomyno** [comment]
> I'm having the same problem with latest Nuxt when I try to import from the generated client 6.6.0
> 
> `import { UserRole } from 'prisma/client'` or `import { UserRole } from '@/prisma/client'`
> 
> with this config
> 
> ```
> generator client {
>   provider        = "prisma-client"
>   moduleFormat    = "esm"
>   output          = "./client"
>   previewFeatures = ["fullTextSearchPostgres"]
> }
> ```
> 
> additionally only if i use `import from 'prisma/client'` i see this
> 
> `[plugin:vite:import-analysis] Missing "./client" specifier in "prisma" package`

Hey @manuel-84, please take a look at [this](https://github.com/prisma/prisma/issues/26857#issuecomment-3037254306) for an example of Nuxt 3 + ESM + `prisma-client` + client-side enum usage.

**Comment by jkomyno** [comment]
Hey @jjrise and @empirium-steve, please take a look [here](https://github.com/prisma/prisma-examples/pull/8228) for an example of React Router + ESM + `prisma-client` + client-side enum usage on Node.js. It runs on Prisma 6.11.0. Please let us know if that solves this issue for you. Thanks!

**Comment by WalrusGumboot** [comment]
> Are you folks trying to import the types into frontend code which has no knowledge of node specific things like file access? 🤔
> 
> If you are barely interested in the types of certain objects and enums you can starting with Prisma 6.7.0 and the new generator import directly from a specific model file. E.g. `import { type UserModel } from '~/generated/prisma/models/User';`.
> 
> Does this help?

This solution also resolved my instance of this problem (SvelteKit 5.25, Prisma 6.12.0, Vite 7.0.5). Thanks a ton!

**Comment by jkomyno** [comment]
Closed as resolved.

**Comment by fjcero** [comment]
Is not.

**Comment by tuncatunc** [comment]
In a tanstack-start app
```
    "@prisma/client": "^6.15.0",
    "@prisma/extension-accelerate": "^2.0.2",
    "prisma": "^6.15.0",
```

schema.prisma
```
generator client {
  provider      = "prisma-client"
  binaryTargets = ["native", "rhel-openssl-3.0.x"]
  output        = "../src/generated/prisma-client"
}

```

I'm still getting the same error

```
TypeError: __banner_node_url.fileURLToPath is not a function
    at @prisma_client_runtime_library.js:177:36

__banner_node_url.fileURLToPath is not a function
var __filename = __banner_node_url.fileURLToPath(import.meta.url);
```

**Comment by jkomyno** [comment]
Hey @fjcero @tuncatunc, can you please provide a minimal reproduction of this problem in a new issue?

**Comment by tuncatunc** [comment]
Hi @jkomyno 
I solved the problem. 
I was calling the generated prisma code from static methods in my service class.
Then I moved all class methods outside the class and made them module level exported functions and problem went away.
 
Here is a sample problematic code snippet 

class CustomerService {
static async getAllCutomers(){
return await prisma.customers.find()
}
}

I changed it to 
export async function getAllCustomers(){...}

Then problem went away.

Hope this clarifies my problem.
