### ISSUE TITLE
Move from @prisma/cli (2.14.0) to prisma generate compile time errors

### ISSUE THREAD

**Issue by gkoudjou** [prisma/prisma#10889]
### Bug description

@prisma/cli 2.14.0 is deprecated and when install it, we are invited to move to prisma.

Because I didn't see a migration guide, I just update to prisma 2.15.0

But have a compile time error 

```
error TS2305: Module '"../../../node_modules/@prisma/client"' 
has no exported member 'InputJsonValue'.

7 import type { InputJsonValue, JsonValue, Prisma } from '@prisma/client';
```

Eveerything was working perfectly fine with @prisma/cli:2.14.0

### How to reproduce

In a project using prisma, just move from @prisma/cli 2.14.0 to a prisma.

In this project, just make use of InputJsonValue or JSonValue.

### Expected behavior

Everything work with prisma 2.15.0 (also tried with prisma 3.7.0) as with @prisma/cli 2.14.0

### Prisma information

```
model ApiKey {
  createdAt            DateTime   @default(now())
  id                   Int        @id @default(autoincrement())
  ipRestrictions       Json?
  apiKey               String     @unique
  scopes               Json?
  updatedAt            DateTime   @updatedAt
  userId               Int?
}

```

### Environment & setup

- OS: Windows 10
- Database: MySQL
- Node.js version: v14.18.0

### Prisma Version

```
> npx prisma -v
Environment variables loaded from .env
prisma                : 2.30.3
@prisma/client        : 2.30.3
Current platform      : windows
Query Engine (Binary) : query-engine b8c35d44de987a9691890b3ddf3e2e7effb9bf20 (at node_modules\@prisma\engines\query-engine-windows.exe)
Migration Engine      : migration-engine-cli b8c35d44de987a9691890b3ddf3e2e7effb9bf20 (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine  : introspection-core b8c35d44de987a9691890b3ddf3e2e7effb9bf20 (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary         : prisma-fmt b8c35d44de987a9691890b3ddf3e2e7effb9bf20 (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash  : b8c35d44de987a9691890b3ddf3e2e7effb9bf20
```

**Comment by janpio** [comment]
https://github.com/prisma/prisma/discussions/10888#discussioncomment-1880026

But also your version output indicates you updated both Prisma CLI and Prisma Client to version 2.30.3 already - which does not match the rest of your description.
