### PR TITLE
feat(generator): ORM-883 add ts-nocheck to generated ts files

### LINKED ISSUE #26853: exactOptionalPropertyTypes does not work in 6.6.0
### Bug description

when using the early access Prisma Client generator and the tsconfig setting `exactOptionalPropertyTypes: true` an error is generated  in the client.ts file

```
generator client {
  provider      = "prisma-client"
  binaryTargets = ["native", "linux-musl-openssl-3.0.x"]
  output        = "../src/generated/prisma"
}

```
```
error TS2412: Type 'undefined' is not assignable to type 'EngineWasmLoadingConfig' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the type of the target.

83 config.engineWasm = undefined

error TS2412: Type 'undefined' is not assignable to type 'CompilerWasmLoadingConfig' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the type of the target.

84 config.compilerWasm = undefined
```

### Severity

⚠️ Major: Breaks core functionality (e.g., migrations fail)

### Reproduction

see above

### Expected vs. Actual Behavior

Expect the type to have undefined instead of/as well as optional so that this error isn't flagged by the typescript compiler

### Frequency

Consistently reproducible

### Does this occur in development or production?

Both development and production

### Is this a regression?

Issue is new to 6.6.0 based on changes to prisma client generator

### Workaround

not using the new generator or turning off `exactOptionalPropertyTypes`

### Prisma Schema & Queries

see above

### Logs & Debug Info

```
// Debug logs here
```

### Environment & Setup

- **OS:** macOS
- **Database:** MySQL
- **Node.js version:** 22.14.0

Should be environment agnostic since it is a typescript issue

### Prisma Version

```
6.6.0
```

### LINKED ISSUE #26884: TS6196 error with the new generator
### Bug description

Trying to update Prisma in my project and use the new generator I encountered a curious error:

```
src/generated/prisma-client/client.ts:705:8 - error TS6196: 'Either' is declared but never used.

705   type Either<
           ~~~~~~

src/generated/prisma-client/client.ts:713:8 - error TS6196: 'PatchUndefined' is declared but never used.

713   type PatchUndefined<O extends object, O1 extends object> = {
```

This is due to the typescript configuration I use, it is fixed by removing a few lines of code in the `tsconfig.json`, but that is not the point, that line helps me not to leave unused variables in my code.

### Severity

🔹 Minor: Unexpected behavior, but does not block development

### Reproduction

tsconfig.json:

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": false, // <--- ps: this also causes more errors if set to true
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "target": "ES2021",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "paths": {
      "@/*": ["src/*"]
    },
    "incremental": true,
    "skipLibCheck": true,
    "strictNullChecks": true,
    "noImplicitAny": false,
    "noUnusedLocals": true, // this is the line
    "strictBindCallApply": false,
    "forceConsistentCasingInFileNames": false,
    "noFallthroughCasesInSwitch": false
  }
}
```

prisma schema:
```prisma
generator client {
  provider        = "prisma-client"
  output          = "../../src/generated/prisma-client"
  previewFeatures = ["prismaSchemaFolder"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```

PS: This happens even with ESM

### Expected vs. Actual Behavior

This doesn't really cause any problems in production, but I have a bad feeling about disabling a configuration (which is there for a reason) and leaving variables/types loose.

### Frequency

Consistently reproducible

### Does this occur in development or production?

Only in development (e.g., CLI tools, migrations, Prisma Studio)

### Workaround

Setting `noUnusedLocals` to false in `tsconfig.json`

### Prisma Schema & Queries

```prisma
generator client {
  provider        = "prisma-client"
  output          = "../../src/generated/prisma-client"
  previewFeatures = ["prismaSchemaFolder"]
}
```
```ts
// Add relevant Prisma Client query
```

### Logs & Debug Info

```
// Debug logs here
```

### Environment & Setup

- **OS:** EndeavourOS (Arch Linux)
- **Database:** PostgreSQL
- **Node.js version:** v22.14.0

### Prisma Version

```
prisma                  : 6.6.0
@prisma/client          : 6.6.0
Computed binaryTarget   : debian-openssl-3.0.x
Operating System        : linux
Architecture            : x64
Node.js                 : v22.14.0
TypeScript              : 5.8.3
Query Engine (Node-API) : libquery-engine f676762280b54cd07c770017ed3711ddde35f37a (at node_modules/.pnpm/@prisma+engines@6.6.0/node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node)
Schema Engine           : schema-engine-cli f676762280b54cd07c770017ed3711ddde35f37a (at node_modules/.pnpm/@prisma+engines@6.6.0/node_modules/@prisma/engines/schema-engine-debian-openssl-3.0.x)
Schema Wasm             : @prisma/prisma-schema-wasm 6.6.0-53.f676762280b54cd07c770017ed3711ddde35f37a
Default Engines Hash    : f676762280b54cd07c770017ed3711ddde35f37a
Studio                  : 0.511.0
Preview Features        : prismaSchemaFolder
```

### PR DESCRIPTION
**Pull request by FGoessler**
As user have varying tsconfig settings we disable type checking for our generated files in the users codebases. 

We however do not want to add these ts-nocheck comments when running our test suite so we still typecheck our generated code properly.

Fixes ORM-883
Fixes ORM-887
Fixes #26853 
Fixes #26884

### CODE REVIEW

File: packages/client-generator-ts/src/utils/addPreamble.ts [hunk 1]
```diff
@@ -5,15 +5,18 @@ const generatedCodePreamble = `
 /* eslint-disable */
 `
 
+const tsNoCheckPreamble = `/* @ts-nocheck */`
```
Comment (viktor-ferenczi) [inline packages/client-generator-ts/src/utils/addPreamble.ts:8]: This appears to miss a leading and/or trailing newline.

**Review by viktor-ferenczi — CHANGES_REQUESTED** [review]

File: packages/client-generator-ts/src/utils/addPreamble.ts (hunk 1 above)
Comment (FGoessler) [reply packages/client-generator-ts/src/utils/addPreamble.ts]: Fixed

**Review by viktor-ferenczi — APPROVED** [review]
