### ISSUE TITLE
7.3.0 missing query_compiler_fast*

### ISSUE THREAD

**Issue by RyanPetersClassroomReady** [prisma/prisma#29061]
### Bug description

After updating to 7.3.0, I now get runtime errors:
Error: Cannot find module '@prisma/client/runtime/query_compiler_fast_bg.postgresql.js' from '../src/generated/prisma/internal/class.ts'

And sure enough, node_modules only has query_compiler_bg* and not the _fast variants.

### Severity

🚨 Critical: Data loss, app crash, security issue

### Reproduction

npm install @prisma/client

### Expected vs. Actual Behavior

Look in node_modules/@prisma/client. *_fast*.js should exist but do not.

### Frequency

Consistently reproducible

### Does this occur in development or production?

Both development and production

### Is this a regression?

Yes, it's related to the new _fast compiler option.

### Workaround

Downgrade to 7.2.0, or (untried) use the "small" compilation option.

### Prisma Schema & Queries

N/A

### Prisma Config

generator client {
  provider            = "prisma-client"
}

datasource db {
  provider = "postgresql"
}

### Logs & Debug Info

During jest tests:
Error: Cannot find module '@prisma/client/runtime/query_compiler_fast_bg.postgresql.js' from '../src/generated/prisma/internal/class.ts'

### Environment & Setup

- **OS:** macOS
- **Database:** PostgreSQL
- **Node.js version:** v22.17.1

### Prisma Version

7.3.0

**Comment by RyanPetersClassroomReady** [comment]
Never mind, this was a race condition on the package publications. yarn up somehow upgraded prisma, but not @prisma/client.

With all on 7.3.0, it's good.
