### ISSUE TITLE
Type Generation : returned payload type on upsert not using include

### ISSUE THREAD

**Issue by squirly** [prisma/prisma#2250]
Breaking commit: https://github.com/prisma/prisma/commit/4cee9296e77e63aa856f60b9a33555ab01d9b039#diff-55d3b6703244dc96a4a668b570e5c70d

^^ Issue is caused by the above commit, related to #615. There is not explanation given as to why this change was made. @timsuchanek could you clarify this change? 

## Bug description

The `include` option only expands the result type when the query options passed to the Prisma Client extend the `findMany` options.
 
The following line decides when `includes` will expand the return type:
https://github.com/prisma/prisma/blob/c86af74877d9f39936b18276b3c1db8d5ff7b310/src/packages/client/src/generation/TSClient.ts#L553

## How to reproduce

Add includes to an `upsert`, or `findOne` that uses a `where` with a composite unique lookup, that is not available in `{...}WhereInput`.

Using the blog fixture example:

```
model Like {
  id  String  @default(cuid()) @id

  userId  String
  user    User    @relation(fields: [userId], references: [id])

  postId  String
  post    Post    @relation(fields: [postId], references: [id])

  @@unique([userId, postId])
}
```

```ts
  const like = await prisma.like.upsert({
    where: {
      userId_postId: {
        userId: userId,
        postId: post.id,
      }
    },
    create: {
      post: {connect: {id: post.id}},
      user: {connect: {id: userId}},
    },
    update: {},
    include: {post: true},
  });

  const p = like.post;
                 |--|
                 ^ TS2339: Property 'post' does not exist on type 'Like'.
```

`typeof like` is `Like` despite the includes.

## Expected behavior

The type correctly has the fields specified in `includes`.

In the above example, `typeof like` should be `Like & {post: Post}`.

## Prisma information

Example in https://github.com/squirly/prisma/tree/bug-example/src/packages/client/fixtures/blog

## Environment & setup

- OS: Mac OS & Arch
- Database: PostgreSQL
- Prisma version:
  - Broken in: 2.0.0-beta.2
  - Works in 2.0.0-beta.1
- Node.js version: 12.16.1

**Comment by pantharshit00** [comment]
First of all, thanks for the detailed report, really appreciate that!

> Breaking commit: 4cee929#diff-55d3b6703244dc96a4a668b570e5c70d
> ^^ Issue is caused by the above commit, related to #615. There is not explanation given as to why this change was made. @timsuchanek could you clarify this change?

This actually meant to refer https://github.com/prisma/prisma-client-js/issues/615. We recently moved code from prisma-client-js to this repository and unfortunately, that information is now incorrect.


I can confirm this issue. We need to fix this.
