### ISSUE TITLE
v6.2.0 Breaks Read Replicas

### ISSUE THREAD

**Issue by amoses12** [prisma/prisma#25993]
### Bug description

Prisma client v6.2.0 no longer instantiates with readReplicas option. v6.1.0 works just fine.

### How to reproduce

1. Create and instantiate a prisma client with readReplicas. Make a call to your instantiated client (see code below).
2. See errors around prisma being undefined.

### Expected behavior

Prisma client should instantiate with readReplicas option.

### Prisma information

```prisma.ts
import { PrismaClient } from "@prisma/client";
import { readReplicas } from "@prisma/extension-read-replicas";

const base = new PrismaClient({
  log: [
    {
      emit: "event",
      level: "query",
    },
    {
      emit: "stdout",
      level: "error",
    },
    {
      emit: "stdout",
      level: "info",
    },
    {
      emit: "stdout",
      level: "warn",
    },
  ],
});

let client: unknown = base;

if (
  process.env.DATABASE_READ_REPLICA_URL
) {
  client = base.$extends(
    readReplicas({
      url: process.env.DATABASE_MAIN_READ_REPLICA_URL as string,
    }),
  );
}

export const prisma = client as PrismaClient;
```
```anyFile.ts
import { prisma } from ./prisma

prisma.$connect() // error: prisma.$connect is not a function

prisma.users.findMany() //error: cannot read property 'users' of undefined
```

### Environment & setup

- OS: macOS, linux
- Database: PostgreSQL
- Node.js version: 18.19.0, 20.18.0

### Prisma Version

```
prisma 6.2.0
prisma/extension-read-replicas: 0.3.0, 0.2.1 tested
```

**Comment by shadoworion** [comment]
From the 6.0 version there was only a peer-dependencies conflict.
From the 6.2 it's not working at all.

```bash
TypeError: Cannot read properties of undefined (reading 'findFirst')
    at Array.$allOperations (/backend/node_modules/@prisma/extension-read-replicas/dist/index.js:146:34)
    at /backend/node_modules/@prisma/client-postgresql/runtime/library.js:31:9170
    at i (/backend/node_modules/@prisma/client-postgresql/runtime/library.js:121:1016)
    at PrismaPromise.then (/backend/node_modules/@prisma/client-postgresql/runtime/library.js:121:1091)
```

**Comment by amoses12** [comment]
Tested all versions of prisma/extension-read-replicas from 0.2.1 through 0.4.0. Confirmed none of these versions are working with prisma v6.2.0.

**Comment by lukebelbina** [comment]
Do you know if there are any plans to support or fix this extension?

**Comment by javiSBP** [comment]
Hi everyone! As this seems a breaking change in the constructor passed to `@prisma/extension-read-replicas` in the last client version, we were able to fix the issue by passing the `replicas` option instead of `url` to the extension.

In the example above:

```js
import { PrismaClient } from "@prisma/client";
import { readReplicas } from "@prisma/extension-read-replicas";

const base = new PrismaClient({
  log: [
    {
      emit: "event",
      level: "query",
    },
    {
      emit: "stdout",
      level: "error",
    },
    {
      emit: "stdout",
      level: "info",
    },
    {
      emit: "stdout",
      level: "warn",
    },
  ],
});

let client: unknown = base;

if (
  process.env.DATABASE_READ_REPLICA_URL
) {
  const replicaClient = new PrismaClient({
    datasourceUrl: process.env.DATABASE_MAIN_READ_REPLICA_URL as string,
  });
  client = base.$extends(
    readReplicas({
      replicas: [replicaClient],
    }),
  );
}

export const prisma = client as PrismaClient;
```

**Comment by lukebelbina** [comment]
thanks @javiSBP , confirming that refactoring the connection to the above fixes things for me on prisma 6.2.1

**Comment by wmadden** [comment]
Thank you for the report @amoses12, we'll fix this as soon as we have capacity 👍🏻

**Comment by michael-rzero** [comment]
Confirming issue still exists in 6.4.1

**Comment by brook-digi** [comment]
Issue still exists in 6.5.0
