### ISSUE TITLE
e.map is not a function error with prisma-client generator + queryCompiler

### ISSUE THREAD

**Issue by esemn** [prisma/prisma#27511]
### Bug description

After upgrading from 5.22 to 6.10.1 with the new prisma-client generator, I'm getting "e.map is not a function" errors on some queries involving the existing many-to-many relations and the include property. P.S The expected migration for many-to-many relations (e.g drop index + create PK) has been applied.

### Severity

🚨 Critical: Data loss, app crash, security issue

### Reproduction

Run the provided query on the provided schema.

Note that only when including the relation I get the error.

### Expected vs. Actual Behavior

Expected no error.

Actual "e.map is not a function"

### Frequency

Consistently reproducible

### Does this occur in development or production?

Only in production (e.g., query engine, generated client)

### Is this a regression?

Yes, it used to worked in 5.22. Not working anymore in 6.10 with the new generator.

### Workaround

use with select instead of returning all relation data

```ts
    include: {
      users: {
        select: {
          id: true,
        },
      },
    },
```

### Prisma Schema & Queries

```prisma
model User {
  id                       String                    @id @unique @default(uuid())
  packages                 Package[]
}

model Package {
  id            String      @id @unique @default(uuid())
  type          PackageType
  numOfRequests Int
  users         User[]
}
```
```ts
prisma.package.findFirstOrThrow({
    where: {
      type: "API",
      users: {
        some: {
          id: userId,
        },
      },
    },
    include: {
      users: true,
    },
  });
```

### Prisma Config

```ts
generator client {
  provider            = "prisma-client"
  previewFeatures     = ["queryCompiler", "driverAdapters"]
  output              = "../src/prisma"
  moduleFormat        = "cjs"
  importFileExtension = ""
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}


import { Prisma, PrismaClient } from "../prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const dbClient = new PrismaClient({
  adapter,
});
```

### Logs & Debug Info

```
// Debug logs here
```

### Environment & Setup

- **OS:** MacOs or Docker node:22-alpine
- **Database:**PostgreSQL
- **Node.js version:** 22

### Prisma Version

```
// Prisma version output
prisma                : 6.10.1
@prisma/client        : 6.10.1
Computed binaryTarget : darwin
Operating System      : darwin
Architecture          : x64
Node.js               : v22.16.0
TypeScript            : 5.8.3
Query Compiler        : enabled
PSL                   : @prisma/prisma-schema-wasm 6.10.1-1.9b628578b3b7cae625e8c927178f15a170e74a9c
Schema Engine         : schema-engine-cli 9b628578b3b7cae625e8c927178f15a170e74a9c (at node_modules/@prisma/engines/schema-engine-darwin)
Default Engines Hash  : 9b628578b3b7cae625e8c927178f15a170e74a9c
Studio                : 0.511.0
Preview Features      : driverAdapters, queryCompiler
```

**Comment by jacek-prisma** [comment]
Hi @esemn, can you provide a complete example including example data? I can't reproduce your issue with randomly generated data.

**Comment by jkomyno** [comment]
Hi @esemn, have you seen @jacek-prisma's comment [above](https://github.com/prisma/prisma/issues/27511#issuecomment-3018613785)?

Can you also try again with `previewFeatures = ["driverAdapters"]` and with `previewFeatures = []`?
I suspect this issue is not related to the new `prisma-client`, but rather to either of the preview features you've used.

**Comment by baileywickham** [comment]
We are seeing this same stack trace, it shows up for us when we `include` a table with an enum array on it. I have a repro of the issue [here](https://github.com/baileywickham/prisma-issue-repro). 

I opened a PR [here](https://github.com/prisma/prisma/pull/27747) and I'm happy to work on fixing this.
