### ISSUE TITLE
Prisma Client fluent API does not work with extends anymore on 4.16.1

### ISSUE THREAD

**Issue by yovanoc** [prisma/prisma#19921]
### Bug description

can't use [fluent api](https://www.prisma.io/docs/concepts/components/prisma-client/relation-queries#fluent-api)

since this last 4.16.1 version

```
Property '[REDACTED]' does not exist on type 'PrismaPromise<GetResult<{ ....}
```

### How to reproduce

try to use fluent api and latest version of Prisma

### Prisma information

```ts
prisma.MODEL.findUnique().FLUENT_RELATION()
```

### Environment & setup

on macOS and node 20 but not the problem here

### Prisma Version

4.16.1

**Comment by yovanoc** [comment]
Oh no I was already on 4.16 with this error https://github.com/prisma/prisma/issues/19866

so 4.15 was working great for me, 4.16 gives the error with extends, and 4.16.1 this one

**Comment by millsp** [comment]
Hey @yovanoc, thanks for the report. I opened a PR to fix this, would you mind installing trying version `4.17.0-integration-client-extensions-fluent-api.1` and let us know if the fluent API works for you?

**Comment by yovanoc** [comment]
@millsp Yes, working perfectly!

**Comment by Jolg42** [comment]
:shipit: Note: This fix is now available as [`4.16.2`](https://github.com/prisma/prisma/releases/tag/4.16.2)
