### ISSUE TITLE
Type error in src/generated/prisma/internal/class.ts when upgrading to 6.7.0 with driverAdapters feature

### ISSUE THREAD

**Issue by hornta** [prisma/prisma#27027]
### Bug description

I'm trying to upgrade our app from 6.5.0 to 6.7.0 along with new preview feature `driverAdapters`. When we now try to compile the code we are getting this error from tsc and I'm not sure how to resolve it. I've tried to implement the suggested change in the error which is to add `declare module '@prisma/client/runtime/query_compiler_bg.postgresql.mjs';` in a d.ts file but it didn't help.

```
src/generated/prisma/internal/class.ts:76:40 - error TS7016: Could not find a declaration file for module '@prisma/client/runtime/query_compiler_bg.postgresql.mjs'. 'C:/git/FusionHub/node_modules/.pnpm/@prisma+client@6.7.0_prisma@6.7.0_typescript@5.8.2__typescript@5.8.2/node_modules/@prisma/client/runtime/query_compiler_bg.postgresql.mjs' implicitly has an 'any' type.
  If the '@prisma/client' package actually exposes this module, try adding a new declaration (.d.ts) file containing `declare module '@prisma/client/runtime/query_compiler_bg.postgresql.mjs';`

76   getRuntime: async () => await import("@prisma/client/runtime/query_compiler_bg.postgresql.mjs"),
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/generated/prisma/internal/class.ts:86:27 - error TS7017: Element implicitly has an 'any' type because type 'typeof globalThis' has no index signature.

86     return new globalThis.WebAssembly.Module(wasmModuleBytes)
                             ~~~~~~~~~~~


Found 2 errors in the same file, starting at: src/generated/prisma/internal/class.ts:76
```

### Severity

🔹 Minor: Unexpected behavior, but does not block development

### Expected vs. Actual Behavior

TypeScript should compile without any error.

### Frequency

Consistently reproducible

### Does this occur in development or production?

Only in development (e.g., CLI tools, migrations, Prisma Studio)

### Prisma Schema & Queries

```prisma
generator client {
  provider        = "prisma-client"
  previewFeatures = ["relationJoins", "queryCompiler", "driverAdapters"]
  output          = "../../src/generated/prisma"
}

generator zod {
  provider = "node --experimental-strip-types ./scripts/prisma-zod/prismaZodGenerator.ts"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

// I've excluded all models and enum because I don't think they are relevant.
```

### Prisma Config

```ts
import { defineConfig } from "prisma/config";

export default defineConfig({
  earlyAccess: true,
  schema: "./prisma/schema",
});

```

### Logs & Debug Info

```
// Debug logs here
```

### Environment & Setup

- **OS:** Windows
- **Database:** PostgreSQL
- **Node.js version:** v22.9.0

### Prisma Version

```
6.7.0
```

**Comment by michaelhays** [comment]
I'm getting a type error as well, though a different one:

```ts
src/generated/prisma/internal/class.ts:86:1 - error TS2322: Type 'unknown' is not assignable to type 'RuntimeDataModel'.

86 config.runtimeDataModel = JSON.parse("{\"models\":{...}}
```

**Comment by notDemian** [comment]
+1 on this, very annoying if you have a workflow that typechecks the entire codebase or a git hook

**Comment by hornta** [comment]
> Thanks for the report, could you please post your `tsconfig.json` as well?

I've updated the issue with references to our tsconfig files.

**Comment by RVBastien** [comment]
Prisma client, and more specifically the class.ts that seems to need be ignored from type check use :
`/* @ts-nocheck */` when it should use `// @ts-nocheck`

Here a small script that fix it while waiting for a patch : 

`const fs = require('fs');
const path = require('path');

const filePath = path.join(
  __dirname,
  '../src/app/infrastructure/prisma/client/internal/class.ts',
);

let content = fs.readFileSync(filePath, 'utf8');

content = content.replace(/\/\*\s*@ts-nocheck\s*\*\/\s*\n?/i, '');

if (!content.startsWith('// @ts-nocheck')) {
  content = `// @ts-nocheck\n${content}`;
}

fs.writeFileSync(filePath, content);

console.log(
  '✔ Prisma types have been successfully modified to comply with TypeScript rules',
);
`

**Comment by aqrln** [comment]
@jensmeindertsma on Tuesday

**Comment by jacek-prisma** [comment]
Hi @hornta,
I think this should be resolved in 6.9.0, can you retry?

**Comment by jkomyno** [comment]
Closing this, as it was fixed in https://github.com/prisma/prisma/pull/27063.
