### ISSUE TITLE
Cannot find module './node/integrations/prisma.js' after upgrading from 4.11.0 to 4.12.0

### ISSUE THREAD

**Issue by rcbevans** [prisma/prisma#18538]
### Bug description

I bundle a node express backend using webpack for deployment to a cloud container as part of a lerna monorepo.

After upgrading `prisma` from 4.11.0 to 4.12.0 I can no longer successfully the start the express, either using webpack dev server, or the production build running directly with node due to a prisma related file './node/integrations/prisma.js' not being found that I have never seen mentioned before.

If I can find the file, I probably just need to copy the file to the dist directory during build, but I can't see a `node` directory anywhere in proximity to the server source, or in the monorepo root after running yarn install, or build, to copy.

### How to reproduce

Create a node express backend with prisma 4.12.0 as a dependency.
Install dependencies and try and run the code.

### Expected behavior

There should be no file system dependencies outside of prisma node_modules, OR the file that is required should be on disk so I can copy it as part of the webpack build.

### Prisma information

Unrelated to schema.

### Environment & setup

- OS: Pop_OS! 22.04 TLS
- Database: Postgres 14
- Node.js version: 18.13.0

### Prisma Version

```
./node_modules/.bin/prisma --version
Environment variables loaded from .env
prisma                  : 4.12.0
@prisma/client          : 4.12.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 659ef412370fa3b41cd7bf6e94587c1dfb7f67e7 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 659ef412370fa3b41cd7bf6e94587c1dfb7f67e7 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.12.0-67.659ef412370fa3b41cd7bf6e94587c1dfb7f67e7
Default Engines Hash    : 659ef412370fa3b41cd7bf6e94587c1dfb7f67e7
Studio                  : 0.483.0
Preview Features        : fullTextSearch, fullTextIndex, orderByNulls
```

**Comment by rcbevans** [comment]
Think I might have jumped to conclusion from the file name, looks like it might actually be an issue stemming from a bumped version of Sentry

```
Error: Cannot find module './node/integrations/prisma.js'
Require stack:
- /packages/server/dist/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Function.Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at Module.patchedRequire [as require] (webpack://@meetingflow/server/../../node_modules/diagnostic-channel/dist/src/patchRequire.js?:16:46)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object../node/integrations/prisma.js (/packages/server/dist/index.js:56671:18)
    at __webpack_require__ (/packages/server/dist/index.js:58223:42)
    at eval (webpack://@meetingflow/server/../../node_modules/@sentry-internal/tracing/esm/index.js?:41:87)
    at Module.../../node_modules/@sentry-internal/tracing/esm/index.js (/packages/server/dist/index.js:26396:1)
    at __webpack_require__ (/packages/server/dist/index.js:58223:42)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by rcbevans** [comment]
You're totally right, not a Prisma issue at all, sorry for jumping the gun!

![image](https://user-images.githubusercontent.com/2041260/228348082-ef9c644c-7183-4c4c-ad2b-aed235957bd7.png)
