### ISSUE TITLE
Anyone else getting typescript compilation error on prisma-client .count() ?

### ISSUE THREAD

**Issue by chanlito** [prisma/prisma#3467]
<img width="526" alt="screen shot 2018-11-12 at 2 52 44 pm" src="https://user-images.githubusercontent.com/15667259/48333745-1d3a4200-e68b-11e8-8fd0-1e8ec25fb072.png">

This compilation error appear after I upgraded to 1.20.1

**Expected behavior**
No typescript compilation error.

**Versions (please complete the following information):**
 - OS: MacOS latest
 - `prisma` CLI: [e.g. `prisma/1.20.1 (darwin-x64) node 8 LTS`]
 - Prisma Server: [e.g. `prisma/1.20.1`]

P.S. I've already look through the issues and couldn't find anything related to this.

**Comment by timsuchanek** [comment]
We're sorry for the inconveniences. We just released a fix for this https://github.com/prisma/prisma/releases/tag/1.20.7

When using `prisma-client-lib@1.20.7` this problem should not occur anymore.

In case you're still facing this issue - please let us know and we reopen this issue.
