### ISSUE TITLE
Cleanup old non-$ methods

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma#4206]
We still have a few methods on Prisma Client, like `.transaction` from the pre-$ days.
We deprecated these methods already a few sprints ago, so it's time to clean them up.

**Comment by erawk** [comment]
This conflict on `prisma.transaction` is preventing us from upgrading to `2.11.x`. We have a model and table named `transaction`, so usage of it as say `prisma.transaction.aggregate` throws type errors:

```
src/modules/accounts/modelHelpers.ts:40:44 - error TS2339: Property 'aggregate' does not exist on type '{ <TAll>(values: Iterable<TAll | PromiseLike<TAll>>): Promise<TAll[]>; <T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(values: readonly [T1 | PromiseLike<T1>, T2 | PromiseLike<...>, ... 7 more ..., T10 | PromiseLike<...>]): Promise<...>; <T1, T2, T3, T4, T5, T6, T7, T8, T9>(values: readonly [...]): Promise<...>; <T1, T2, ...'.

40   const { sum } = await prisma.transaction.aggregate({
                                              ~~~~~~~~~
```

This worked fine in `2.10.x`.

**Comment by pantharshit00** [comment]
@erawk You can map the table for now while this clean up happens.

```prisma
model P_Transaction {
 ...
 ...
 @@map("Transaction")
}
```

**Comment by erawk** [comment]
@pantharshit00 Yes, we can do this, but we also have to change _everywhere_ we use the model. For example, in the snippet above, we'd have to change `prisma.transaction` to `prisma.p_transaction` in all places we call it.

Is there an ETA on fixing this collision? Can we help by submitting a pull request for these renames? Where should I look?

**Comment by janpio** [comment]
This is going to be worked on in the next 2 weeks.

**Comment by erawk** [comment]
Appreciate the quick turnaround here 👏
