### ISSUE TITLE
Prisma 6.6 generator not working with Next auth (@auth/prisma-adapter)

### ISSUE THREAD

**Issue by elie222** [prisma/prisma#26901]
### Bug description

Next auth Prisma adapter does not work with the new generator introduced in Prisma v6.6.

### Severity

⚠️ Major: Breaks core functionality (e.g., migrations fail)

### Expected vs. Actual Behavior

Expected: it should continue to work.

Actual: "Type instantiation is excessively deep and possibly infinite.ts(2589)"

### Frequency

Consistently reproducible

### Does this occur in development or production?

Only in development (e.g., CLI tools, migrations, Prisma Studio)

### Is this a regression?

No. This works if not using the generator.

### Workaround

Don't use the generator introduced in Prisma v6.6.

### Prisma Schema & Queries

```prisma
datasource db {
  provider  = "postgresql"
  url       = env("DATABASE_URL")
  directUrl = env("DIRECT_URL")
}

generator client {
  provider     = "prisma-client-js"
  output       = "../generated/prisma"
  moduleFormat = "esm"
}
```
```ts
export const getAuthOptions: (options?: {
  consent: boolean;
}) => NextAuthConfig = (options) => ({
  // debug: true,
  providers: [
    GoogleProvider({
      clientId: env.GOOGLE_CLIENT_ID,
      clientSecret: env.GOOGLE_CLIENT_SECRET,
      authorization: {
        url: "https://accounts.google.com/o/oauth2/v2/auth",
        params: {
          scope: SCOPES.join(" "),
          access_type: "offline",
          response_type: "code",
        },
      },
    }),
  ],
  adapter: PrismaAdapter(prisma),
  session: { strategy: "jwt" },
```

### Logs & Debug Info

```
// Debug logs here
```

### Environment & Setup

- **OS:** macOS
- **Database:** PostgreSQL
- **Node.js version:** v22.10.0

### Prisma Version

```
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
prisma                  : 6.6.0
@prisma/client          : 6.6.0
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v22.10.0
TypeScript              : 5.8.3
Query Engine (Node-API) : libquery-engine f676762280b54cd07c770017ed3711ddde35f37a (at ../../node_modules/.pnpm/@prisma+engines@6.6.0/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli f676762280b54cd07c770017ed3711ddde35f37a (at ../../node_modules/.pnpm/@prisma+engines@6.6.0/node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 6.6.0-53.f676762280b54cd07c770017ed3711ddde35f37a
Default Engines Hash    : f676762280b54cd07c770017ed3711ddde35f37a
Studio                  : 0.511.0
```

**Comment by Dizolivemint** [comment]
This is likely because Next-Auth [prisma adapter](https://github.com/nextauthjs/next-auth/blob/07b7d93c655ba35ac548655f8b71bd8dfeeee652/packages/adapter-prisma/src/index.ts#L12) imports from @prisma/client.

**Comment by jkomyno** [comment]
Hey @elie222, can you please open this issue on [the Next Auth repository](https://github.com/nextauthjs/next-auth)?
We don't maintain that project, and imho it would make sense for them to offer something like:
- `prisma-client-js-adapter`: The existing Next Auth adapter that uses the old `prisma-client-js` generator and imports from `@prisma/client`
- `prisma-client-adapter`: A new Next Auth adapter that uses the new `prisma-client` generator and takes a `PrismaClient` instance as an input

We also provide examples of Next.js + `esm` + `prisma-client` generator + middlewares on `edge-light` runtimes, see [here](https://github.com/prisma/prisma-examples/tree/latest/generator-prisma-client/nextjs-starter-webpack-with-middleware).
We'd be happy to showcase a NextAuth example using `prisma-client` as well, once that adapter will exist.

**Comment by CHC383** [comment]
I didn't run into the same error (`Type instantiation is excessively deep and possibly infinite.ts(2589)`) when I started to test the new `prisma-client` generator (6.9.0). I did get an issue about typing ([details](https://github.com/prisma/prisma/discussions/27378#discussioncomment-13435901)) but it's due to the old generated `prisma-client-js` client, and once `node_modules` is removed and recreated along with the generation of the new `prisma-client` client, compilation wise it works fine with the existing NextAuth adaptor. So my point is the error reported in this issue might not apply to the latest Prisma.

However, the latest problem I ran into is Next.js/Webpack doesn't seem to be able to handle the packaging of the wasm module (required/import [here](https://github.com/prisma/prisma/blob/59fc0106899b518857f119146e61daafaef1360e/packages/client-generator-ts/src/utils/buildGetWasmModule.ts#L69)) and causes module not found error in the Vercel environment, although it is a different topic.

**Comment by jkomyno** [comment]
> However, the latest problem I ran into is Next.js/Webpack doesn't seem to be able to handle the packaging of the wasm module (required/import [here](https://github.com/prisma/prisma/blob/main/packages/client-generator-ts/src/utils/buildGetWasmModule.ts#L69)) and causes module not found error in the Vercel environment, although it is a different topic.

Hey @CHC383, that's been fixed in Prisma 6.11.0. Can you upgrade to the latest version and try again? You can also follow the steps in [this Next.js + Webpack example](https://github.com/prisma/prisma-examples/tree/latest/generator-prisma-client/nextjs-starter-webpack). Thanks

**Comment by CHC383** [comment]
@jkomyno Thanks for checking, I am aware that #27343 is fixed in v6.11.0 and verified that the fix works with Webpack. The error I mentioned above is a new error while loading the wasm module, and the error message is 
```
prisma:error
Invalid `prisma.session.findUnique()` invocation:
Cannot find module '@prisma/client/runtime/query_compiler_bg.postgresql.wasm'
```

But I think it might already be fixed in https://github.com/prisma/prisma/commit/0345aa95702f223c19f7b29852ba5c0b43e4890e and I am assuming it will be released in v6.12.0

**Comment by CHC383** [comment]
@jkomyno Unfortunately I just tried v6.12.0 and still getting the same error, somehow Webpack or Vercel deployment couldn't package the wasm correctly.

**Comment by jkomyno** [comment]
Hey @CHC383, just to be clear:
- Next.js + webpack + `prisma-client` generator works (see [here](https://github.com/jkomyno/nextjs-starter-webpack))
- Next.js Auth can't possibly work with `prisma-client` until their maintainers introduce support for `prisma-client` generator, as explained [above](https://github.com/prisma/prisma/issues/26901#issuecomment-3037285190).

Please share a repository that provides a minimal reproduction of the problem you're facing, and I'll take a look.

**Comment by CHC383** [comment]
@jkomyno Sorry for the confusion, I think for my case it may not be about Next.js + webpack + prisma-client, but about Vercel (AWS Labmda) packaging and deployment, please see the discussions in https://github.com/prisma/prisma/issues/27486#issuecomment-3074857668. However, in my case I did use next-auth and getting the error on that code path (with `prisma-client`), so the issue could be due to the adapter incompatibility which causes the wasm module not being packaged properly.

I will try to see if I could create a minimal reproduction without next-auth running on Vercel.

BTW, the adapter `@auth/prisma-adapter` is simple and only imports type `PrismaClient` from `@prisma/client` ([code](https://github.com/nextauthjs/next-auth/blob/main/packages/adapter-prisma/src/index.ts#L18)), the other parts are independent from `prisma-client` or `prisma-client-js`, and its current input is already a PrismaClient instance (typing wise we could force convert if needed to make TypeScript happy, after all it doesn't affect runtime). Does it really matter to introduce a new adapter?

**Comment by jkomyno** [comment]
> [@jkomyno](https://github.com/jkomyno) Sorry for the confusion, I think for my case it may not be about Next.js + webpack + prisma-client, but about Vercel (AWS Labmda) packaging and deployment, please see the discussions in [#27486 (comment)](https://github.com/prisma/prisma/issues/27486#issuecomment-3074857668).

Uhm, I deployed [the example I shared above](https://github.com/jkomyno/nextjs-starter-webpack) to Vercel just fine (see it online [here](https://nextjs-starter-webpack.vercel.app/)).

Now that I think of it, I guess you are using the Edge Light runtime, which Vercel uses by default in Next.js middlewares.
If that's the case, please check [this other example](https://github.com/prisma/prisma-examples/tree/latest/generator-prisma-client/nextjs-starter-webpack-with-middleware).

**Comment by CHC383** [comment]
Actually I am not using Next.js middleware, but I do use neon adapter which might be the difference? I need to see if I can reproduce it, and thanks for the example, will use it as a start.

**Comment by CHC383** [comment]
@jkomyno Here is the reproduction
- Code: https://github.com/CHC383/nextjs-prisma-vercel-debug
- Website: https://nextsj-prisma-vercel-debug.vercel.app

Besides updating all the dependencies to the latest, which I don't think affects the results, one noticeable change I have done is adding [`await connection();`](https://github.com/CHC383/nextjs-prisma-vercel-debug/blob/8eb01488b13cae5b422ffc6a07dfdd43dffe83c1/components/quotes.tsx#L11) to `Quotes` in `components/quotes.tsx`. This forces the component to be rendered dynamically ([doc1](https://nextjs.org/docs/app/api-reference/functions/connection), [doc2](https://nextjs.org/docs/messages/prerender-error)). Before making this change, I tried to build the app, and found out that Next.js tried to prerender `app/page` and `Quotes` by fetching the database during build time, and I haven't set up my database yet at that moment and ran into prerender error. This might be the reason that you didn't see the error, as Prisma wasn't run during runtime.

**Comment by jkomyno** [comment]
Hey @CHC383, I can reproduce your runtime error, deployment-only error in [this commit](https://github.com/jkomyno/nextjs-starter-webpack/commit/3f1e25af38b9e1befd943d2feb2c5aee2978999f).

The Vercel app prints
> Application error: a server-side exception has occurred while loading nextjs-starter-webpack.vercel.app (see the server logs for more information).

Here's what I see in the runtime logs on Vercel:

```
⨯ Error [PrismaClientKnownRequestError]: 
Invalid `prisma.quotes.findMany()` invocation:


Cannot find module '@prisma/client/runtime/query_compiler_bg.postgresql.wasm'
Require stack:
- /vercel/path0/lib/generated/prisma/internal/class.ts
    at async l (.next/server/app/page.js:1:21478) {
  code: 'MODULE_NOT_FOUND',
  meta: [Object],
  clientVersion: '6.12.0',
  digest: '2339700909'
}
```

We'll investigate this further.

**Comment by LZL0** [comment]
> We'll investigate this further.

Thank you!

**Comment by cipriancaba** [comment]
This absolutely doesn't work on Vercel with 6.12.0

**Comment by jkomyno** [comment]
Hi @CHC383, @LZL0 and others, can you please try this integration version of Prisma: [prisma@6.14.0-integration-feat-client-wasm-base64-on-nodejs.6](https://www.npmjs.com/package/prisma/v/6.14.0-integration-feat-client-wasm-base64-on-nodejs.6) (from https://github.com/prisma/prisma/pull/27795) and report back?

Make sure to re-run `prisma generate` after the update.

Handy update script for your projects:
```
pnpm update "@prisma/*"@6.14.0-integration-feat-client-wasm-base64-on-nodejs.6
pnpm update "prisma"@6.14.0-integration-feat-client-wasm-base64-on-nodejs.6
pnpm prisma generate
```

We aim to stabilize the `prisma-client` generator as "generally available" within the next 3 weeks, so your feedback is helpful!
Thanks

**Comment by CHC383** [comment]
Thanks @jkomyno, I tested the the integration version and it works for my Vercel deployment

**Comment by jkomyno** [comment]
Closing this as fixed via https://github.com/prisma/prisma/pull/27795.
