### PR TITLE
feat: add useExternalRuntime option for Lambda environments

### LINKED ISSUE #28471: Cannot find module '/opt/nodejs/node_modules/@prisma/client/runtime/client'
### Bug description

We have a monorepo that we are converting to use the new Rust-free version (v6.18.0) because of the promised bundle size reduction as we have hit lambda+layer sizing issues in the past with prisma.

We created a package that holds the new generated client and models, and are using that as dependency in other packages and lambdas. Previously, we had the @prisma/client in our lambda layer

We are getting this error below. The generated client needs the runtime, but its treated as an external dependency and not bundled with our code.
Cannot find module '/opt/nodejs/node_modules/@prisma/client/runtime/client'

### Severity

🔹 Minor: Unexpected behavior, but does not block development

### Expected vs. Actual Behavior

Expect that the generated client is able to work out of the box

### Frequency

Consistently reproducible

### Does this occur in development or production?

Only in production (e.g., query engine, generated client)

### Is this a regression?

Worked in rust version of prisma (v6.0.1) and is broken with rust-free version (v6.18.0)

### Workaround

Our solution was to bundle the @prisma/client/runtime with our code, but that seems like a workaround rather than a proper solution

### Prisma Schema & Queries

```prisma
// Add relevant schema.prisma snippet
generator client {
  provider     = "prisma-client"
  output       = "./generated"
  engineType   = "client"
  moduleFormat = "cjs"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

...models...
```
```ts
// Add relevant Prisma Client query
```

### Prisma Config

```ts
// Add your `prisma.config.ts`
```

### Logs & Debug Info

```
// Debug logs here
```

### Environment & Setup

- **OS:**  macOS and AWS
- **Database:**  PostgreSQL
- **Node.js version:**  v20.19.4 local, >20 on AWS

### Prisma Version

```
// Prisma version output
prisma                  : 6.18.0
@prisma/client          : 6.18.0
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v20.19.4
TypeScript              : 5.9.3
Query Engine (Node-API) : libquery-engine 34b5a692b7bd79939a9a2c3ef97d816e749cda2f (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
PSL                     : @prisma/prisma-schema-wasm 6.18.0-8.34b5a692b7bd79939a9a2c3ef97d816e749cda2f
Schema Engine           : schema-engine-cli 34b5a692b7bd79939a9a2c3ef97d816e749cda2f (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Default Engines Hash    : 34b5a692b7bd79939a9a2c3ef97d816e749cda2f
Studio                  : 0.511.0
```

### PR DESCRIPTION
**Pull request by ish1416**
- Add useExternalRuntime generator config option
- Use @prisma/client/runtime imports when useExternalRuntime=true
- Skip copying runtime files when using external runtime
- Fixes #28471 - Lambda runtime import resolution issue

### CODE REVIEW

**Review by rmoss-nutrien — APPROVED** [review]

**Comment by daifuyang** [comment]
持续关注中

**Comment by tensordreams** [comment]
Hi @ish1416 — thanks for this, and apologies for the slow reply.

We're clearing the open PR backlog ahead of moving this codebase to a `v7` branch, with the [Prisma Next](https://github.com/prisma/prisma-next) rewrite taking over `main`.

We are closing this one: the option is added only to the legacy `client-generator-js`, undocumented and without tests, and whether an external-runtime escape hatch should exist at all is a design decision in its own right.

Thanks for the time you put into it.
