### ISSUE TITLE
exactOptionalPropertyTypes does not work in 6.6.0

### ISSUE THREAD

**Issue by dan2kx** [prisma/prisma#26853]
### Bug description

when using the early access Prisma Client generator and the tsconfig setting `exactOptionalPropertyTypes: true` an error is generated  in the client.ts file

```
generator client {
  provider      = "prisma-client"
  binaryTargets = ["native", "linux-musl-openssl-3.0.x"]
  output        = "../src/generated/prisma"
}

```
```
error TS2412: Type 'undefined' is not assignable to type 'EngineWasmLoadingConfig' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the type of the target.

83 config.engineWasm = undefined

error TS2412: Type 'undefined' is not assignable to type 'CompilerWasmLoadingConfig' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the type of the target.

84 config.compilerWasm = undefined
```

### Severity

⚠️ Major: Breaks core functionality (e.g., migrations fail)

### Reproduction

see above

### Expected vs. Actual Behavior

Expect the type to have undefined instead of/as well as optional so that this error isn't flagged by the typescript compiler

### Frequency

Consistently reproducible

### Does this occur in development or production?

Both development and production

### Is this a regression?

Issue is new to 6.6.0 based on changes to prisma client generator

### Workaround

not using the new generator or turning off `exactOptionalPropertyTypes`

### Prisma Schema & Queries

see above

### Logs & Debug Info

```
// Debug logs here
```

### Environment & Setup

- **OS:** macOS
- **Database:** MySQL
- **Node.js version:** 22.14.0

Should be environment agnostic since it is a typescript issue

### Prisma Version

```
6.6.0
```

**Comment by FGoessler** [comment]
Starting with 6.7.0. (scheduled for next week) we'll add `eslint-ignore` and `@ts-nocheck` comments to the generated files to avoid issues with users custom typescript settings that our generated code violates.
