### ISSUE TITLE
Prisma 6.8.0 init error on Windows - Only URLs with a scheme in: file, data, and node are supported by the default ESM loader

### ISSUE THREAD

**Issue by lonadels** [prisma/prisma#27192]
### Bug description

on 6.8.0 it is impossible to use prisma:
```
> npx prisma@6.8.0 init
Error: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
```

but on versions below everything works:
```
>npx prisma@6.7.0 init
Need to install the following packages:
prisma@6.7.0
Ok to proceed? (y) y


✔ Your Prisma schema was created at prisma/schema.prisma
  You can now open it in your favorite editor.

warn Prisma would have added DATABASE_URL but it already exists in .env
warn You already have a .gitignore file. Don't forget to add `.env` in it to not commit any private information.

Next steps:
1. Set the DATABASE_URL in the .env file to point to your existing database. If your database has no tables yet, read https://pris.ly/d/getting-started
2. Set the provider of the datasource block in schema.prisma to match your database: postgresql, mysql, sqlite, sqlserver, mongodb or cockroachdb.
3. Run npx prisma db pull to turn your database schema into a Prisma schema.
4. Run npx prisma generate to generate the Prisma Client. You can then start querying your database.
5. Tip: Explore how you can extend the ORM with scalable connection pooling, global caching, and real-time database events. Read: https://pris.ly/cli/beyond-orm

More information in our documentation:
https://pris.ly/d/getting-started
```

NodeJS `v22.15.1`
NPM `11.3.0`
Windows 11 24H2 (build 26100.4061)

### Severity

🚨 Critical: Data loss, app crash, security issue

### Reproduction

`> npx  prisma@6.8.0 init`

### Expected vs. Actual Behavior

instead of an error there should be successful initialize

### Frequency

Consistently reproducible

### Does this occur in development or production?

Only in development (e.g., CLI tools, migrations, Prisma Studio)

### Is this a regression?

Yes, last worked in Prisma 6.7.0, broke in 6.8.0

### Workaround

Downgrading to Prisma 6.7.0 fixes it

### Prisma Schema & Queries

empty

### Prisma Config

empty

### Environment & Setup

- **OS:** Windows
- **Database:** any
- **Node.js version:** 22.12.1

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 6.8.0
@prisma/client          : Not found
Computed binaryTarget   : windows
Operating System        : win32
Architecture            : x64
Node.js                 : v22.15.1
TypeScript              : unknown
Query Engine (Node-API) : libquery-engine 2060c79ba17c6bb9f5823312b6f6b7f4a845738e (at ..\..\Users\vladislav.shinkaruk\AppData\Roaming\npm\node_modules\prisma\node_modules\@prisma\engines\query_engine-windows.dll.node)
Schema Engine           : schema-engine-cli 2060c79ba17c6bb9f5823312b6f6b7f4a845738e (at ..\..\Users\vladislav.shinkaruk\AppData\Roaming\npm\node_modules\prisma\node_modules\@prisma\engines\schema-engine-windows.exe)
Schema Wasm             : @prisma/prisma-schema-wasm 6.8.0-43.2060c79ba17c6bb9f5823312b6f6b7f4a845738e
Default Engines Hash    : 2060c79ba17c6bb9f5823312b6f6b7f4a845738e
Studio                  : 0.511.0
```

**Comment by FGoessler** [comment]
Thanks for reporting this @lonadels! We did a change in the way the `prisma init` command is run and it is now a separate package that we load on demand. Maybe this on demand loading logic isn't working as expected in your case. 🤔 

Can you check whether other commands that use that same on-demand loading logic work or error with the same failure. An example being `prisma dev`.

**Comment by gregreydev** [comment]
> Thanks for reporting this [@lonadels](https://github.com/lonadels)! We did a change in the way the `prisma init` command is run and it is now a separate package that we load on demand. Maybe this on demand loading logic isn't working as expected in your case. 🤔
> 
> Can you check whether other commands that use that same on-demand loading logic work or error with the same failure. An example being `prisma dev`.

For me, running the `prisma dev` gives the same error message

**Comment by tan911** [comment]
I’m encountering the same issue with the `pnpm prisma init --db --output ../generated/prisma` command on Windows. I also tried the `prisma init --datasource-provider postgresql --output ../generated/prisma` command, but I still get the same error:

```bash
Error: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
```

- prisma version: `^6.8.0`
- node version: `v20.12.0`
- os: `windows 10`


To reproduce: [turborepo with prisma](https://www.prisma.io/docs/guides/turborepo)

**Comment by sapondanaisriwan** [comment]
I also facing this issue

**Comment by YucelCakir** [comment]
also facing it. 
Prisma Version: 6.8.0 (fails), 6.7.0 (works)
Node.js Version: v20.18.0
Operating System: windows

**Comment by FGoessler** [comment]
We are working on a fix and are issuing a 6.8.1 hotfix for this.

@jpedrosouza your issue regarding `prisma generate` is due to a missing `@prisma/client` package. Ensure you ahve not only the `prisma` cli installed as a devDependency but also `@prisma/client` in the matching version as a regular dependency. :)

**Comment by umarbashirr** [comment]
I am also facing the same issue. Was setting up the new project and got this error:

$ pnpm dlx prisma init
Error: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:

**Comment by FGoessler** [comment]
Prisma `6.8.1` is released now and fixes this issue on windows. Thanks again for reporting this and sorry for the inconvenience! 🙏

**Comment by nightydev** [comment]
> Prisma `6.8.1` is released now and fixes this issue on windows. Thanks again for reporting this and sorry for the inconvenience! 🙏

I installed 6.8.1 and this happen
npx prisma init
Error: Cannot find module 'C:\Users\shoha\AppData\Local\Temp\@prisma\cli-init@latest-1747285200000\node_modules\@prisma\cli-init\dist\index.js' imported from C:\Users\shoha\OneDrive\Escritorio\Software\Next-JS\nextjs-prisma\node_modules\prisma\build\index.js

**Comment by nightydev** [comment]
> Prisma `6.8.1` is released now and fixes this issue on windows. Thanks again for reporting this and sorry for the inconvenience! 🙏

I tried with 6.7.0 and works, later npm i --save-dev prisma@latest with the 6.8.1 and this happen:
PS C:\Users\shoha\OneDrive\Escritorio\Software\Next-JS\nextjs-prisma> npx prisma init --datasource-provider sqlite
Error: Cannot find module 'C:\Users\shoha\AppData\Local\Temp\@prisma\cli-init@latest-1747285200000\node_modules\@prisma\cli-init\dist\index.js' imported from C:\Users\shoha\OneDrive\Escritorio\Software\Next-JS\nextjs-prisma\node_modules\prisma\build\index.js
