### ISSUE TITLE
Schema ignored

### ISSUE THREAD

**Issue by lukasa1993** [prisma/prisma#27037]
### Bug description

```
const adapter = new PrismaPg(
  {
    connectionString: `${process.env.DATABASE_URL}`,
  },
  {
    schema: searchPath,
  }
);
```

trying to set schema like this tried in database_url ?schema and ?search_path all default to public anyway

### Severity

⚠️ Major: Breaks core functionality (e.g., migrations fail)

### Reproduction

```
const adapter = new PrismaPg(
  {
    connectionString: `${process.env.DATABASE_URL}`,
  },
  {
    schema: 'non_public_schema',
  }
);
```

### Expected vs. Actual Behavior

passed schema must be used

### Frequency

Consistently reproducible

### Does this occur in development or production?

Both development and production

### Is this a regression?

this happens on 6.7.0 `"queryCompiler", "driverAdapters"` with no rust flow

### Workaround

6.6.0 works without pg-adapter

### Prisma Schema & Queries

```
generator client {
  previewFeatures = ["relationJoins", "nativeDistinct", "fullTextSearchPostgres", "postgresqlExtensions", "queryCompiler", "driverAdapters"]
  provider        = "prisma-client"
  output          = "../app/generated/db"
}
```

### Prisma Config

```ts
// Add your `prisma.config.ts`
```

### Logs & Debug Info

```
// Debug logs here
```

### Environment & Setup

macos 15.4.1 (24E263)
node v22.14.0

### Prisma Version

Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
prisma                  : 6.7.0
@prisma/client          : 6.7.0
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v22.14.0
TypeScript              : 5.8.3
Query Engine (Node-API) : libquery-engine 3cff47a7f5d65c3ea74883f1d736e41d68ce91ed (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 3cff47a7f5d65c3ea74883f1d736e41d68ce91ed (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 6.7.0-36.3cff47a7f5d65c3ea74883f1d736e41d68ce91ed
Default Engines Hash    : 3cff47a7f5d65c3ea74883f1d736e41d68ce91ed
Studio                  : 0.511.0
Preview Features        : driverAdapters, fullTextSearchPostgres, nativeDistinct, postgresqlExtensions, queryCompiler, relationJoins

**Comment by 0-vortex** [comment]
Can reproduce without `queryCompiler` turned on, just `driverAdapters` 🤔

**Comment by JosefBud** [comment]
This is happening in my project as well, the only preview features I'm using are `queryCompiler` and `driverAdapters`. However, removing `queryCompiler` and keeping `driverAdapters` fixes the problem for me.

**Comment by sjlutterbie** [comment]
Replicated with `6.8.2` - this is blocking our efforts to use `queryCompiler`

**Comment by jacek-prisma** [comment]
Hi @sjlutterbie @lukasa1993 , can you retry on 6.9.0?

**Comment by lukasa1993** [comment]
> Hi [@sjlutterbie](https://github.com/sjlutterbie) [@lukasa1993](https://github.com/lukasa1993) , can you retry on 6.9.0?

i did try, forgot to report it still same issue only queries public schema

**Comment by jacek-prisma** [comment]
Hi @lukasa1993 @sjlutterbie 
Apologies, I thought the fix for this went out in 6.9.0, but it has not released yet, it should work correctly on the dev version though: `6.10.0-dev.17`

**Comment by lukasa1993** [comment]
> Hi [@lukasa1993](https://github.com/lukasa1993) [@sjlutterbie](https://github.com/sjlutterbie) Apologies, I thought the fix for this went out in 6.9.0, but it has not released yet, it should work correctly on the dev version though: `6.10.0-dev.17`

great i'll still wait for 6.10 to come out

**Comment by lukasa1993** [comment]
> Hi [@lukasa1993](https://github.com/lukasa1993) [@sjlutterbie](https://github.com/sjlutterbie) Apologies, I thought the fix for this went out in 6.9.0, but it has not released yet, it should work correctly on the dev version though: `6.10.0-dev.17`

i upgraded to 6.10.0 but it still queries public schema, i am using same `DATABASE_URL` env do we need to passs schema differently ?

**Comment by jacek-prisma** [comment]
Hi @lukasa1993, if you're using the second adapter parameter with the `schema` field, that parameter should now be used, e.g.:
```ts
const adapter = new PrismaPg({ connectionString: `${process.env.DATABASE_URL}` },{ schema });
```

**Comment by lukasa1993** [comment]
> Hi [@lukasa1993](https://github.com/lukasa1993), if you're using the second adapter parameter with the `schema` field, that parameter should now be used, e.g.:
> 
> const adapter = new PrismaPg({ connectionString: `${process.env.DATABASE_URL}` },{ schema });

that worked on local but on prod 

`Cannot find module '@prisma/client/runtime/query_compiler_bg.postgresql.wasm'`
 this error comes up

if  this wasm is needed should it be moved to `output          = "../app/generated/db"` as was .node file before? or even better if we don't need wasm and can be with JS fully

**Comment by lukasa1993** [comment]
@jacek-prisma managed to bundle this .wasm manually but now i am encountering ssl issues with aws rds how i can tell it to use ssl ?

**Comment by s-montigny-desautels** [comment]
As of 6.10.0, it's working, but only partially.

I'm using the snippet that @jacek-prisma provided
```ts
const adapter = new PrismaPg({ connectionString: `${process.env.DATABASE_URL}` },{ schema });
```

It works for the queries. The schema is properly appended to the start of each table. However, the `search_path` is not properly set for postgres. In my case, I have a trigger function in my database and it is looking at the wrong schema.

Here is the code sample

```ts
		const adapter = new PrismaPg(
			{ connectionString: this.dbUrl },
			{
				schema: this.schema,
			},
		);
		const prisma = new PrismaClient({ adapter, log: ["query"] });
		await prisma.$connect();

		console.log(await prisma.$queryRaw`SHOW search_path`);
```

It output
`[ { search_path: '"$user", public' } ]`

To make it work, we still need to provide the schema in the connection uri, like this:

```ts
		const adapter = new PrismaPg(
			{ connectionString: `${this.dbUrl}?options= -c search_path="${this.schema}"` },
			{
				schema: this.schema,
			},
		);
		const prisma = new PrismaClient({ adapter, log: ["query"] });
		await prisma.$connect();

		console.log(await prisma.$queryRaw`SHOW search_path`);
```

Now it output the good schema.

Maybe the driver should set the good schema when opening a connection ?

**Comment by jacek-prisma** [comment]
Hi @s-montigny-desautels,
The driver adapters currently do not set the search path, that's not behavior specific to the query compiler. That's what's currently expected with driver adapters but we might change it at some point; another user has already created an issue about this: https://github.com/prisma/prisma/issues/26930

**Comment by lukasa1993** [comment]
okay my issue is solved anyway thanks
