### ISSUE TITLE
Regression in Prisma 6.8.1 on Windows: `Cannot find module '@prisma/cli-init'` when running `prisma init`

### ISSUE THREAD

**Issue by nightydev** [prisma/prisma#27196]
### Bug description

After upgrading to Prisma version 6.8.1, I am encountering a new error on Windows when running the `prisma init` command:

```
Error: Cannot find module '...@prisma/cli-init@latest...\index.js' imported from ...\node_modules\prisma\build\index.js
```

This issue is different from the known 6.8.0 bug related to URL scheme parsing on Windows, but it appears to be a regression introduced in 6.8.1.

## Additional notes
* The problem seems related to dynamic loading of the `@prisma/cli-init` package on Windows.
* The known 6.8.0 issue (#27192) was resolved in 6.8.1, but this appears to be a new Windows-specific regression.

### Severity

🚨 Critical: Data loss, app crash, security issue

### Reproduction

1. Use Prisma CLI version 6.8.1 on Windows 11 (24H2, build 26100.4061).
2. Run `npx prisma init --db` or `npx prisma init` in a new or existing Next.js project.
3. Observe the error above.

## Expected behavior
The `prisma init` command should successfully create the `prisma/schema.prisma` file and `.env` file with the appropriate template.

## Actual behavior
The command fails with the "Cannot find module '@prisma/cli-init'" error.

### Frequency

Consistently reproducible

### Does this occur in development or production?

Only in development (e.g., CLI tools, migrations, Prisma Studio)

### Is this a regression?

Yes, last worked in Prisma 6.7.0, broke in 6.8.0 and 6.8.1

### Workaround

Downgrading to Prisma 6.7.0 resolves the issue:

```bash
npm install prisma@6.7.0 @prisma/client@6.7.0
```

### Prisma Schema & Queries

N/A, npx prisma init don't work

### Environment & Setup

* OS: Windows 11 24H2 (build 26100.4061)
* Node.js: v22.15.1
* Prisma CLI & Client version: 6.8.1 (failing), 6.7.0 (working)
* Database: N/A (issue occurs on init command)

### Prisma Version

6.8.1

**Comment by FGoessler** [comment]
Hi @nightydev 👋 

Sorry to hear that this is still an issue for you on windows. :/

Do you have a similar multi-drive setup as the users in this issue: https://github.com/prisma/prisma/issues/27195? Aka your project directory on a different hard drive than your vscode/terminal? 🤔

**Comment by nightydev** [comment]
> Hi [@nightydev](https://github.com/nightydev) 👋
> 
> Sorry to hear that this is still an issue for you on windows. :/
> 
> Do you have a similar multi-drive setup as the users in this issue: [#27195](https://github.com/prisma/prisma/issues/27195)? Aka your project directory on a different hard drive than your vscode/terminal? 🤔

In my case, both the project and my terminal/VSCode are on the same drive (`C:`), so it might not be exactly the same scenario as #27195 — but it might still be related to how Prisma resolves paths on Windows, idk

**Comment by nightydev** [comment]
Oh, it just worked, I tried several times in the afternoon uninstalling and installing 6.7.0 and 6.8.1, now I tried again uninstalling and installing once more the last one and it just worked 

PS C:\Users\shoha\OneDrive\Escritorio\Software\Next-JS\nextjs-prisma> npx prisma init

Fetching latest updates for this subcommand...
✔ Your Prisma schema was created at prisma/schema.prisma
  You can now open it in your favorite editor.

**Comment by FGoessler** [comment]
> Oh, it just worked, I tried several times in the afternoon uninstalling and installing 6.7.0 and 6.8.1, now I tried again uninstalling and installing once more the last one and it just worked
> 
> PS C:\Users\shoha\OneDrive\Escritorio\Software\Next-JS\nextjs-prisma> npx prisma init
> 
> Fetching latest updates for this subcommand... ✔ Your Prisma schema was created at prisma/schema.prisma You can now open it in your favorite editor.

Happy to hear that! Maybe a caching issue and somehow it actually still used 6.8.0 before? 🤔 

Can I close this issue for now? (We'll still investigate https://github.com/prisma/prisma/issues/27195)

**Comment by TimKochDev** [comment]
I am sorry to inform you that this bug still persists. I followed https://www.prisma.io/docs/guides/react-router-7 and got the same error with prisma@6.8.2 on Windows. Downgrading to 6.7.0 worked.

Since this error occurred in a fresh repository, it can't be a cache issue if I am not mistaken.

My workaround will be to use WSL as you recommended in your Contributing Guidelines.

**Comment by FGoessler** [comment]
Hi @TimKochDev,

Sorry to hear that. Can you provide more information about your specific setup please? Output of `prisma version`, which package manager you use, and your setup of directories would be especially helpful for us to be able to reproduce this.

**Comment by FGoessler** [comment]
@TimKochDev maybe you also suffer from a "corrupted" cache directory of the init cli cache. Can you try to clear the cache directory similar to what I just described here: https://github.com/prisma/prisma/issues/27202#issuecomment-2889413273

**Comment by FGoessler** [comment]
FYI: With 6.10.0 we added some logic that will automatically delete a broken install and retry the installation.
