### ISSUE TITLE
[Prisma 7.0.0] TypeScript TS2742 errors with pnpm monorepo - cannot resolve @prisma/client-runtime-utils types

### ISSUE THREAD

**Issue by fsmm19** [prisma/prisma#28581]
## Bug description

After upgrading from Prisma 6.19.0 to Prisma 7.0.0 (released today, Nov 19, 2024), TypeScript compilation fails with `TS2742` errors in a pnpm monorepo setup with NestJS. The generated Prisma Client code cannot resolve types from `@prisma/client-runtime-utils` through pnpm's symlink structure.

### Project Structure
```
library-system/
├── apps/
│   └── api/                    # NestJS app
│       ├── prisma/
│       │   └── schema.prisma
│       ├── generated/prisma/   # Custom output location
│       └── package.json
├── package.json
├── pnpm-workspace.yaml
└── .npmrc
```

### Steps to reproduce
1. Set up a pnpm monorepo with NestJS
2. Configure Prisma with custom output:
```prisma
   generator client {
     provider     = "prisma-client"
     output       = "../generated/prisma"
     moduleFormat = "cjs"
   }
```
3. Upgrade to Prisma 7.0.0:
```bash
   pnpm add @prisma/client@7.0.0 prisma@7.0.0 -D
```
4. Run migrations and generate:
```bash
   pnpm exec prisma migrate dev
   pnpm exec prisma generate
```
5. Try to start the NestJS dev server:
```bash
   pnpm run dev
```

## Expected behavior

The NestJS server should start without TypeScript compilation errors, as it did with Prisma 6.19.0.

## Actual behavior

TypeScript compilation fails with multiple TS2742 errors:
```
apps/api dev: generated/prisma/internal/prismaNamespace.ts:114:14 - error TS2742: The inferred type of 'DbNull' cannot be named without a reference to '.pnpm/@prisma+client-runtime-utils@7.0.0/node_modules/@prisma/client-runtime-utils'. This is likely not portable. A type annotation is necessary.

apps/api dev: 114 export const DbNull = runtime.DbNull
apps/api dev:                  ~~~~~~

apps/api dev: generated/prisma/internal/prismaNamespace.ts:121:14 - error TS2742: The inferred type of 'JsonNull' cannot be named without a reference to '.pnpm/@prisma+client-runtime-utils@7.0.0/node_modules/@prisma/client-runtime-utils'. This is likely not portable. A type annotation is necessary.

apps/api dev: 121 export const JsonNull = runtime.JsonNull
apps/api dev:                  ~~~~~~~~

apps/api dev: generated/prisma/internal/prismaNamespace.ts:128:14 - error TS2742: The inferred type of 'AnyNull' cannot be named without a reference to '.pnpm/@prisma+client-runtime-utils@7.0.0/node_modules/@prisma/client-runtime-utils'. This is likely not portable. A type annotation is necessary.

apps/api dev: 128 export const AnyNull = runtime.AnyNull
apps/api dev:                  ~~~~~~~
```

Similar errors occur in `prismaNamespaceBrowser.ts`.

## Environment & Setup
```bash
prisma                  : 7.0.0
@prisma/client          : 7.0.0
Computed binaryTarget   : native
Operating System        : WSL2 (Ubuntu)
Database                : PostgreSQL
Node.js                 : v22.11.1
Package Manager         : pnpm 10.22.0
```

### Prisma Schema
```prisma
generator client {
  provider     = "prisma-client"
  output       = "../generated/prisma"
  moduleFormat = "cjs"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

// ... models
```

### pnpm Configuration
**pnpm-workspace.yaml:**
```yaml
packages:
  - 'apps/*'
```

**.npmrc** (attempted workarounds):
```ini
public-hoist-pattern[]=@prisma/client-runtime-utils
public-hoist-pattern[]=@prisma/client
```

### TypeScript Configuration
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "moduleResolution": "node",
    "target": "ES2021",
    "preserveSymlinks": true,
    "skipLibCheck": true
  }
}
```

## Investigation

The issue appears to be related to how TypeScript resolves types through pnpm's symlink structure. Running `ls -la node_modules/@prisma/client-runtime-utils` shows:
```bash
lrwxrwxrwx ... node_modules/@prisma/client-runtime-utils -> ../.pnpm/@prisma+client-runtime-utils@7.0.0/node_modules/@prisma/client-runtime-utils
```

The symlink exists and hoisting worked, but TypeScript cannot resolve the types through it when referenced in the generated client code.

## Attempted Workarounds

1. ✅ **Hoisting via `.npmrc`** - Symlink created but TS still fails
2. ❌ **`preserveSymlinks: true`** in tsconfig - No effect
3. ❌ **Installing `@prisma/client-runtime-utils` directly** - Still fails
4. ⚠️ **`node-linker=hoisted`** in `.npmrc` - Would work but defeats the purpose of pnpm

## Temporary Solution

Downgrading to Prisma 6.19.0 resolves all issues immediately:
```bash
pnpm add @prisma/client@6.19.0 prisma@6.19.0 -D
pnpm exec prisma generate
```

## Additional Context

- This issue appears immediately after upgrading to Prisma 7.0.0 (released Nov 19, 2024)
- The same setup works perfectly with Prisma 6.19.0
- Similar TS2742 issues with pnpm have been reported for years but this specific error with `@prisma/client-runtime-utils` is new to Prisma 7
- Related to the architectural changes in Prisma 7 (Rust-free, new code generation location)

## Related Issues

- #47663 (microsoft/TypeScript)
- Various pnpm + Prisma monorepo issues (#6603, #10813, #24199)

---

**Is this a known limitation or is there a recommended configuration for pnpm monorepos with Prisma 7?** The documentation doesn't mention pnpm-specific requirements for version 7.

Thank you for your time!

**Comment by brian-lou** [comment]
I'm getting the same issue but with this tsconfig:
```
"compilerOptions": {
  "allowSyntheticDefaultImports": true,
  "jsx": "react",
  "sourceRoot": "/packages/node",
  "rootDir": ".",
  "outDir": "dist",
  "paths": {
    "#prisma/*": ["./generated/*"],
    "@/*": ["./src/*"]
  }
},
"include": ["src", "prisma.config.ts", "generated"],
```

**Comment by vpmedia** [comment]
I don't use monorepos, a simple `pnpm install @prisma/client-runtime-utils` solved the issue for me.

**Comment by riordanpawley** [comment]
I reckon you can workaround this with a patch like https://gist.github.com/riordanpawley/0fe02462ea5c23f051b1e2fa358271a5
Add that file to your repo, chmod +x it, in package.json scripts have a generate script like "pnpm prisma generate && ./scripts/patch-prisma-types.sh"

**Comment by Sigabiel** [comment]
Having the same issue and hoping for a fix soon. I don't want to use the workaround with the patch file 😢

**Comment by ryanzen9** [comment]
haha When I received the Prisma 7 update today, I migrated my project accordingly. Unfortunately, this issue has cost both me and ChatGPT an entire afternoon. It would be great if the relevant team members could help resolve it;😢

**Comment by ryanzen9** [comment]
I disabled "declaration" by setting "declaration": false in my application's tsconfig.json, and that solved the issue. However, I'm not sure if this is actually a good approach or just a workaround.

**Comment by wjixiang** [comment]
I use nx with monorepo, `pnpm install @prisma/client-runtime-utils` also solved the problem.

**Comment by ads6495** [comment]
Installing `@prisma/client-runtime-utils` in my db package (where client is instantiated) in monorepo solved it for me. Thanks @wjixiang and @vpmedia

**Comment by chmodami** [comment]
Install `pnpm install @prisma/client-runtime-utils` remove `"type": "module"` from `package.json ` and set `"module": "commonjs", "moduleResolution": "node"` in your tsconfig.json

**Comment by brmorillo** [comment]
> Install `pnpm install @prisma/client-runtime-utils` remove `"type": "module"` from `package.json ` and set `"module": "commonjs", "moduleResolution": "node"` in your tsconfig.json

Worked!

**Comment by fsmm19** [comment]
## Update: Multiple issues encountered, reverted to Prisma 6

After further investigation and troubleshooting, I encountered multiple critical issues with Prisma 7.0.0 in our pnpm monorepo setup:

### Issue #1: TypeScript compilation errors (TS2742)
Initial error with `@prisma/client-runtime-utils` types not being resolvable through pnpm symlinks, even after applying recommended workarounds (hoisting, `preserveSymlinks`, etc.)

### Issue #2: Runtime error after workaround
Installing `@prisma/client-runtime-utils` directly resolved the TS2742 errors but introduced a new runtime error:
```
TypeError: Cannot read properties of undefined (reading '__internal')
    at new PrismaClient
```

This suggests the generated client code and runtime are out of sync or incompatible.

### Issue #3: CLI incompatibility
The Prisma 7 CLI rejects Prisma 6 schema format:
```
Error: The datasource property `url` is no longer supported in schema files
```

This makes it difficult to maintain projects that need to stay on v6 when the CLI gets globally updated.

### Resolution
Reverted to **Prisma 6.19.0** and everything works perfectly again:
- No TypeScript errors
- No runtime errors  
- Stable and production-ready

### Recommendation
For teams using **pnpm monorepos**, I strongly recommend staying on Prisma 6.x until these issues are resolved. The combination of:
- New architecture (Rust-free)
- Generated code location changes
- pnpm's symlink structure
- TypeScript's module resolution

...creates multiple failure points that aren't present in Prisma 6.

I'll gladly test future patch releases (7.0.1, 7.1.0) but for now, Prisma 6 is the stable choice for pnpm users.

---

**Environment:**
- pnpm: 10.22.0
- NestJS: 11.1.9
- Node.js: 24.11.1
- Monorepo structure with custom output location

**Comment by drewteachout** [comment]
I cannot use commonjs, so these workarounds/fixes are not working for me. Looking forward to a resolution. Also using a pnpm workspaces monorepo with nx

**Comment by OTrigo** [comment]
i had the same typeError during the runtime that @fsmm19 mentioned, i'm in a NestJS project too: `[Nest] 10712  - 2025-11-21, 3:11:14 p.m.   ERROR [ExceptionHandler] TypeError: Cannot read properties of undefined (reading '__internal')`

**Comment by slonweiss** [comment]
## Working Solution for pnpm Monorepo + Prisma 7.0.0

  Successfully migrated production monorepo from Prisma 6.16.2 → 7.0.0. Here's the fix for TS2742 errors:

  ### Quick Fix

  Add to workspace root `.npmrc`:

  ```ini
  public-hoist-pattern[]=*prisma*
```
  This hoists Prisma packages to root node_modules, making @prisma/client-runtime-utils resolvable by TypeScript.

  Environment
```
  - pnpm 9.x workspaces, TypeScript 5.9.3, Turborepo monorepo
  - Database: PostgreSQL with @prisma/adapter-pg
```

**Comment by fruitsdrink** [comment]
Facing the same error.  Reverted to Prisma 6.19.0

**Comment by mateusdata** [comment]
# Solutions for Prisma 7 with NestJS

There are two simple ways to fix compatibility issues between Prisma 7 and NestJS:

## Method 1: Modifying tsconfig.json

Modify the following properties in your `tsconfig.json`:

```json
{
  "module": "commonjs",
  "moduleResolution": "node",
  "resolvePackageJsonExports": false
}
```

### Prisma Schema for Method 1

```prisma
generator client {
  provider = "prisma-client"
  output   = "../src/generated/prisma"
}

datasource db {
  provider = "postgresql"
}
```

## Method 2: Only modifying schema.prisma

Add `moduleFormat = "cjs"` to the generator:

```prisma
generator client {
  provider     = "prisma-client"
  output       = "../src/generated/prisma"
  moduleFormat = "cjs"
}

datasource db {
  provider = "postgresql"
}
```

> **Note:** With Method 2, you don't need to modify `tsconfig.json`

## Benefits

- ✅ Works with Prisma 7
- ✅ Compatible with NestJS
- ✅ Unit tests work correctly
- ✅ No version rollback required
- ✅ **Method 1**: Unit tests work normally
- ⚠️ **Method 2**: Unit tests may not work correctly

## Recommendation

Use **Method 1** if you need to run unit tests. **Method 2** is simpler but may cause issues with tests.

**Comment by ahp98** [comment]
For those who sill strugle, if you use postgres check this page out, no matter using nestjs or pure nodejs it worked for me add adapter

https://www.prisma.io/docs/getting-started/prisma-orm/quickstart/prisma-postgres

**Comment by codepunkt** [comment]
None of the potential solutions outlined as part of this issue worked for me using pnpm with prisma 7, except for adding `@prisma/client-runtime-utils` as a direct dependency to the workspace that has my generated prisma client.

**Comment by Vedant-Scripts** [comment]
"@prisma/client-runtime-utils": "^7.0.0", 

With pnpm, dependencies are isolated and symlinked, so the generated client cannot resolve the runtime-utils package unless it exists as a top-level dependency.

Installing it manually fixes the issue

> node v24.11.1
pnpm v10.23.0
prisma v7.0.0
@prisma/client v7.0.0
ts -v5.9.3

**Comment by shivsarthak** [comment]
> Install pnpm install @prisma/client-runtime-utils remove "type": "module" from package.json  and set "module": "commonjs", "moduleResolution": "node" in your tsconfig.json

This worked for me as well 👍

**Comment by esoh** [comment]
I have this problem, but with yarn workspaces instead of pnpm. Installing `@prisma/client-runtime-utils` as a root level dependency didn't work for me, and no way I'm going to attempt to convert to cjs. Temporarily fixed it by running `yarn patch @prisma/client` and updated both `runtime/index-browser.d.ts` and `runtime/client.d.ts` to include the lines below:

```typescript
export { AnyNullClass } from '@prisma/client-runtime-utils';
export { DbNullClass } from '@prisma/client-runtime-utils';
export { JsonNullClass } from '@prisma/client-runtime-utils';
```

Have some suspicions it might be specific to my yarn workspace configuration since I didn't see any other posts about yarn. Maybe it's due to `runtime.DbNull` trying to resolve to the type of `DbNullClass` but my project can't find `DbNullClass` because it's defined in `/node_modules/@prisma/client/node_modules/@prisma/client-runtime-utils/dist/index.d.ts`. I'm no typescript expert, but re-exporting `DbNullClass` and etc from `@prisma/client/runtime/<client.d.ts/index-browser.d.ts>` worked for me.

**Comment by ryanzen9** [comment]
When upgrading Prisma to 7.0.1, please don't forget to update `@prisma/client-runtime-utils` as well. 
It's quite inconvenient to manage this manually—hopefully this can be improved soon.

**Comment by rynvelt** [comment]
Also reverted to Reverted to Prisma 6.19.0 because of that, using Bun 1.3.3

**Comment by mateusdata** [comment]
Prisma 7 no NestJS: solução do erro ESM/CJS

Hey everyone! I made a video showing two different ways to fix the Prisma 7 error when using it with NestJS, especially the exports is not defined in ES module scope issue.

🎥 Watch the video here:
https://www.youtube.com/watch?v=VvrVPrifRUw

**Comment by davidjbng** [comment]
> I have this problem, but with yarn workspaces instead of pnpm. Installing `@prisma/client-runtime-utils` as a root level dependency didn't work for me, and no way I'm going to attempt to convert to cjs. Temporarily fixed it by running `yarn patch @prisma/client` and updated both `runtime/index-browser.d.ts` and `runtime/client.d.ts` to include the lines below:
> 
> export { AnyNullClass } from '@prisma/client-runtime-utils';
> export { DbNullClass } from '@prisma/client-runtime-utils';
> export { JsonNullClass } from '@prisma/client-runtime-utils';

This worked for me as well.

Here is the patch file:
[@prisma__client.patch](https://github.com/user-attachments/files/23794834/%40prisma__client.patch)

**Comment by Wasim-Zaman** [comment]
pnpm add prisma/client-runtime-utils solved mine issue too
Thanks for pointing out

**Comment by kyle4real** [comment]
only getting TS2742 errors when my schema contains JSON type

**Comment by Akash1000x** [comment]
please fix this asap

**Comment by AbbasAlibhaiER** [comment]
I had the same issue in my NestJS project with pnpm. Two things fixed it:

  ### 1. Add `moduleResolution` to tsconfig.json

  ```json
  {
    "compilerOptions": {
      "module": "commonjs",
      "moduleResolution": "node",  // Add this line
      "declaration": true,
      // ...rest of your config
    }
  }
```

 ### 2. Installing `@prisma/client-runtime-utils` and manually moving it to `dependencies`

  The key issue is that `@prisma/client-runtime-utils` needs to be in `dependencies`, NOT `devDependencies`.

  In my case, it was already installed but in the wrong section. I moved it from `devDependencies` to dependencies in `package.json`:

```json
  {
    "dependencies": {
      "@prisma/client": "^7.0.1",
      "@prisma/client-runtime-utils": "7.0.1"  // Move here, not in devDependencies
    }
  }
```
  Then run `pnpm install` to update the lockfile.

  After these two changes, `tsc --noEmit` passed without errors!

**Comment by aarhusgregersen** [comment]
I have succesfully upgraded to Prisma 7 in both a NestJS application, and a pnpm monorepo, admittedly the monorepo doesn't use NestJS.
I had no issues with neither.

I'm happy to provide any assistance I can, so maybe this can be solved - or we can discover if there is an actual issue.

I notice several things, that might indicate something being wrong. Among other, having to install the runtime utils.

Disclaimer: I may be totally wrong, but just thought I'd try to be helpful, since I see many people experiencing a problem I never came close to, despite numerous upgrades to Prisma 7.

### 1. The `client` configuration:
```
   generator client {
     provider     = "prisma-client"
     output       = "../generated/prisma"
     moduleFormat = "cjs"
   }
```

Why do you provide the `moduleFormat` here? It should not be necessary.
It's also possible to entirely omit the `"type": "module"` from `package.json`, I do that in my NestJS reproduction repository, and I still don't need to declare `moduleFormat` for things to work. 
Here´s a working sample:
```
generator client {
  provider   = "prisma-client"
  engineType = "client"
  output     = "../../generated/client"
}
```
And you don't even have to provide the `engineType` if you don't want to. 

### 2. The `db` configuration:
```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```

The [prisma 7.0.0 upgrade guide](https://www.prisma.io/docs/orm/more/upgrade-guides/upgrading-versions/upgrading-to-prisma-7) explicitly states that we should remove the `url` property from here.
It should be removed and instead moved to the new configuration file (see 4.) 

### 3. The `tsconfig.json` configuration:
Given the thoroughness of running build and a typecheck in a monorepo, it may be wise to add the `generated` output folder to the `excludes` section of your `tsconfig.json`.
This ensures that you don't try to typecheck the Prisma output. We should be able to trust the generated output, the same way we would trust any other external package.

Additionally, it's important we configure typescript to properly consume ESM packages (`esModuleInterop`), which I don't see in your configuration either..

Here is my working `tsconfig.json` from a monorepo setup:

```
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "compilerOptions": {
    "esModuleInterop": true,
    "skipLibCheck": true,
    "target": "ES2022",
    "lib": ["ES2022"],
    "allowJs": true,
    "resolveJsonModule": true,
    "moduleDetection": "force",
    "isolatedModules": true,
    "jsx": "react-jsx",

    "incremental": true,
    "disableSourceOfProjectReferenceRedirect": true,
    "tsBuildInfoFile": "${configDir}/.cache/tsbuildinfo.json",

    "strict": true,
    "noUncheckedIndexedAccess": true,
    "checkJs": true,

    "module": "Preserve",
    "moduleResolution": "Bundler",
    "noEmit": true
  },
  "include": ["src"],
  "exclude": ["node_modules", "build", "dist", ".next", ".expo", "generated"]
}
```

### 4. The `prisma.config.ts` configuration:
I see no mention of a `prisma.config.ts`. Did you not migrate the configuration to [the new configuration file format](https://www.prisma.io/docs/orm/reference/prisma-config-reference)?
A simple example might look like this:
```
import * as path from 'node:path';
import dotenv from 'dotenv';
import type { PrismaConfig } from 'prisma';

dotenv.config();

export default {
  /**
   * The path to the Prisma schema file.
   */
  schema: path.join('prisma', 'schema'),
  migrations: {
    path: path.join('prisma', 'migrations'),
    seed: 'ts-node -r tsconfig-paths/register src/config/database/seed.ts',
  },
} satisfies PrismaConfig;
```

I have [a minimal reproduction repo with NestJS monolithic repository right here](https://github.com/aarhusgregersen/prisma7-nestjs-template).

Alternatively, I also have [a minimal reproduction repo for Prisma in a monorepo](https://github.com/aarhusgregersen/prisma-seed-minimal-reproduction/tree/feat/prisma-7), however it's not using NestJS.

Hopefully this is helpful!

**Comment by yovanoc** [comment]
> > I have this problem, but with yarn workspaces instead of pnpm. Installing `@prisma/client-runtime-utils` as a root level dependency didn't work for me, and no way I'm going to attempt to convert to cjs. Temporarily fixed it by running `yarn patch @prisma/client` and updated both `runtime/index-browser.d.ts` and `runtime/client.d.ts` to include the lines below:
> > export { AnyNullClass } from '@prisma/client-runtime-utils';
> > export { DbNullClass } from '@prisma/client-runtime-utils';
> > export { JsonNullClass } from '@prisma/client-runtime-utils';
> 
> This worked for me as well.
> 
> Here is the patch file: [@prisma__client.patch](https://github.com/user-attachments/files/23794834/%40prisma__client.patch)

for me this is the best temporary solution so far 👍🏻

**Comment by manojdcoder** [comment]
Using Nx mono repo + pnpm, it appears this issue is resolved in Prisma 7.1.0.

**Comment by artursudnik** [comment]
Even after upgrading to v7.1 I still have this issue. Compiled code is not able to import `@prisma/client-runtime-utils`
```
> node apps/rest-api-backend/dist/main.js
node:internal/modules/cjs/loader:1424
  throw err;
  ^

Error: Cannot find module '@prisma/client-runtime-utils'
Require stack:
- /my-project/packages/prisma/generated/prisma/runtime/client.js
- /my-project/packages/prisma/generated/prisma/index.js
- /my-project/packages/prisma/dist/prisma.service.js
- /my-project/packages/prisma/dist/prisma.module.js
- /my-project/packages/prisma/dist/main.js
- /my-project/packages/crypto/dist/application/use-cases/crypto.service.js
- /my-project/packages/crypto/dist/application/use-cases/index.js
- /my-project/packages/crypto/dist/main.js
- /my-project/packages/business-process/dist/application/use-cases/business-process.service.js
- /my-project/packages/business-process/dist/application/use-cases/index.js
- /my-project/packages/business-process/dist/public/business-process.module.js
- /my-project/packages/business-process/dist/main.js
- /my-project/apps/rest-api-backend/dist/app.module.js
- /my-project/apps/rest-api-backend/dist/main.js
```

However, it works fine when executed from within `apps/rest-api-backend` folder with `pnpm nest src/main.ts`

Installing `@prisma/client-runtime-utils` explicitly as a dependency of the prisma package helps.

**Comment by drewteachout** [comment]
Can confirm that upgrading to v7.1.0 resolved this problem. Thanks!

**Comment by kayp514** [comment]
I can confirm that I have also experienced the same issue. it it was resolved by simply reverting  Prisma 6.19.0

**Comment by rynvelt** [comment]
Still seeing this in 7.2.0 with Bun 1.3.5 monorepo and linker = "isolated"

**Comment by gabrielbryk** [comment]
Also seeing this issue on 7.2.0 in nx monorepo using pnpm

**Comment by simonstaffgenius** [comment]
Seeing this issue with prisma version 7.2.0 in a pnpm workspace repo.
`Error: Cannot find module '.prisma/client/default'`

**Comment by elad-mizrahi** [comment]
hoisting the module solved the issue for me:
.npmrc:
```wipublic-hoist-pattern[]=@prisma/client-runtime-utils```

and tsconfig.json  
```{
  "compilerOptions": {
    "target": "ES2024",
    "lib": ["dom", "dom.iterable", "esnext"],
    "strict": true,
    "noEmit": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "skipLibCheck": true,
    "incremental": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    },
    "plugins": [{ "name": "next" }],
    "allowJs": false
  },
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx",
    ".next/types/**/*.ts",
    "**/*.mts"
  ],
  "exclude": ["node_modules"]
}

**Comment by shmidt-i** [comment]
`public-hoist-pattern[]=@prisma/client-runtime-utils` inside `.npmrc` file was enough for me

**Comment by pepeteg** [comment]
Migrated a Prisma 6 → 7 monorepo (npm workspaces, not pnpm) end-to-end without needing to revert, but it took a few non-obvious steps beyond the official guide. Writing up the whole thing in case it saves someone else the afternoon — no `@prisma/client-runtime-utils` patch, no CommonJS downgrade needed, at least in this setup.

**Setup:** npm workspaces monorepo, PostgreSQL. Schema originally at the repo root (`prisma/schema.prisma`), consumed by a `packages/core` workspace package.

## 1. The mandatory driver adapter (expected, per the guide)

Prisma 7 drops the Rust query engine, so `new PrismaClient()` with no arguments no longer works — it now requires an adapter:

```ts
// Before (v6)
const prisma = new PrismaClient({ log: [...] });

// After (v7)
import { PrismaPg } from "@prisma/adapter-pg";
const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter, log: [...] });
```
This part matched the docs exactly, no surprises.

## 2. `datasource.url` in schema.prisma is now rejected outright

```
error: The datasource property `url` is no longer supported in schema files.
```
Also expected per the guide — the URL now lives only in `prisma.config.ts`'s `datasource.url`, resolved via `env(...)`.

## 3. The generator output crossing a workspace-package boundary breaks tsconfig lookup (not documented)

With schema at the monorepo root and `output` pointing into a *different* workspace package (`packages/core/generated/prisma`), `prisma generate` failed with:
```
Error:
File '../../../tsconfig.json' not found.
```
regardless of the exact output path, and regardless of setting `moduleFormat`/`importFileExtension` explicitly in the generator block (which per the docs should bypass tsconfig-based inference for those two settings specifically — it didn't stop this particular lookup).

**Fix:** stop crossing the package boundary. Co-locate `schema.prisma`, `prisma.config.ts`, and the generated `output` all *inside the same package* that consumes them — mirroring a sibling monorepo of mine that already runs Prisma 7 successfully. Root-level `db:*` scripts now just delegate with `npm run db:migrate --workspace=packages/core` etc. instead of running Prisma directly from the root.

## 4. Even fully co-located, a two-hop tsconfig `extends` chain still broke it (the real root cause)

After co-locating everything, the *exact same* `File '../../../tsconfig.json' not found` error persisted. Turned out unrelated to the output path — it was our shared TS config:

```jsonc
// packages/core/tsconfig.json
{ "extends": "@myorg/config/typescript/base.json", ... }

// packages/config/typescript/base.json  (resolved via node_modules)
{ "extends": "../../../tsconfig.json", ... }  // 👈 second hop, relative path
```

Real `tsc` resolves that `../../../` correctly — relative to `base.json`'s *own* file location on disk, regardless of who ultimately extends it. Prisma's internal tsconfig reader doesn't seem to track "the current file's own directory" through a nested extends hop the same way; it looks like it re-resolves the second relative `extends` against the wrong base, producing a path that doesn't correspond to anything real.

**Fix:** inline the root tsconfig's `compilerOptions` directly into `base.json` and drop the second `extends` hop. Single-hop chains (package-name → literal options, no further relative `extends`) work fine — it's specifically the *nested* relative extends that breaks.

## Result

With all four fixed, `prisma generate`, `prisma migrate status`, and the actual runtime client (via `@prisma/adapter-pg`) all work cleanly against a real local Postgres — verified with real queries, not just a successful generate. No TS2742, no runtime `__internal` crash.

Might be worth the tsconfig reader replicating `tsc`'s own extends-resolution behavior for nested chains, since shared/monorepo TS configs commonly look exactly like #4 above.
