### ISSUE TITLE
Prisma 6.14.0 adds breaking change for extending of PrismaClient

### ISSUE THREAD

**Issue by pasha-vuiko** [prisma/prisma#27894]
### Bug description

After update to Prisma v6.14.0 I face the TS error when I try to extend the PrismaClient:
`TS2508: No base constructor has the specified number of type arguments.`

### Severity

🚨 Critical: Data loss, app crash, security issue

### Reproduction

The simple code causes TS compilation error:
```ts
class PrismaService extends PrismaClient {}
```

Prisma generator defenition:

```prisma
generator client {
  provider        = "prisma-client"
  previewFeatures = ["relationJoins", "driverAdapters", "queryCompiler"]
  output          = "./client"
  moduleFormat    = "cjs"
}
```

### Expected vs. Actual Behavior

I expect PrismaClient to not require additional generics to make TS compile as it was before

### Frequency

Consistently reproducible

### Does this occur in development or production?

Only in development (e.g., CLI tools, migrations, Prisma Studio)

### Is this a regression?

Yes, worked in Prisma v6.13.0, broke in v6.14.0

### Workaround

Making change in `class.ts` (generated by `prisma generate`) from this:

```ts
export interface PrismaClientConstructor {
    /**
   * ## Prisma Client
   * 
   * Type-safe database client for TypeScript
   * @example
   * ```
   * const prisma = new PrismaClient()
   * // Fetch zero or more Customers
   * const customers = await prisma.customer.findMany()
   * ```
   * 
   * Read more in our [docs](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client).
   */

  new <
    Options extends Prisma.PrismaClientOptions,
    LogOpts extends LogOptions<Options>,
    OmitOpts extends Prisma.PrismaClientOptions['omit'] = Options extends { omit: infer U } ? U : Prisma.PrismaClientOptions['omit'],
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
  >(options?: Prisma.Subset<Options, Prisma.PrismaClientOptions> ): PrismaClient<LogOpts, OmitOpts, ExtArgs>
}
```

to this (setting default values for the generics):
```ts
export interface PrismaClientConstructor {
    /**
   * ## Prisma Client
   * 
   * Type-safe database client for TypeScript
   * @example
   * ```
   * const prisma = new PrismaClient()
   * // Fetch zero or more Customers
   * const customers = await prisma.customer.findMany()
   * ```
   * 
   * Read more in our [docs](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client).
   */

  new <
    Options extends Prisma.PrismaClientOptions = Prisma.PrismaClientOptions,
    LogOpts extends LogOptions<Options> = LogOptions<Options>,
    OmitOpts extends Prisma.PrismaClientOptions['omit'] = Options extends { omit: infer U } ? U : Prisma.PrismaClientOptions['omit'],
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
  >(options?: Prisma.Subset<Options, Prisma.PrismaClientOptions> ): PrismaClient<LogOpts, OmitOpts, ExtArgs>
}
```

or as alternative changing from
```ts
class PrismaService extends PrismaClient {}
```
to

```ts
class PrismaService extends PrismaClient<PrismaClientOptions, LogOptions<PrismaClientOptions>> {}
```

### Prisma Schema & Queries

```prisma
// Add relevant schema.prisma snippet
```
```ts
// Add relevant Prisma Client query
```

### Prisma Config

```ts
// Add your `prisma.config.ts`
```

### Logs & Debug Info

```
// Debug logs here
```

### Environment & Setup

- **OS:** 
- **Database:** 
- **Node.js version:** 
I think it is reproducible in any OS with any Node.js version

### Prisma Version

```
// Prisma version output
```
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
prisma                : 6.14.0
@prisma/client        : 6.14.0
Computed binaryTarget : darwin-arm64
Operating System      : darwin
Architecture          : arm64
Node.js               : v22.18.0
TypeScript            : 5.9.2
Query Compiler        : enabled
PSL                   : @prisma/prisma-schema-wasm 6.14.0-25.717184b7b35ea05dfa71a3236b7af656013e1e49
Schema Engine         : schema-engine-cli 717184b7b35ea05dfa71a3236b7af656013e1e49 (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Default Engines Hash  : 717184b7b35ea05dfa71a3236b7af656013e1e49
Studio                : 0.511.0
Preview Features      : driverAdapters, queryCompiler, relationJoins

**Comment by mag123c** [comment]
The problem seems to be that when the PrismaClient class was refactored in v6.14.0, the generic parameters in the constructor lost their default values. This breaks the common pattern of extending PrismaClient without specifying generics.

I've opened [PR](https://github.com/prisma/prisma/pull/27897) with a minimal fix - just adds back the default values to the generic parameters.

**Comment by bhalperin** [comment]
See [here](https://dev.to/bhalperin/breaking-changes-in-prisma-client-v614-45k0) how I worked around it. Or maybe it should be the practice from 6.14 on.

**Comment by skworden** [comment]
A few people on my team had the same issue after updating to 6.14. Clearing cache and calling `prisma generate` alone were not enough.  

Some could call `prisma generate` after deleting `node_modules` and _**relaunching their IDE**_. Other's had to delete the codebase completely, restart their computer, reclone, and call `prisma generate`.

 It's working for everyone without any code changes.

**Comment by eluchsinger** [comment]
Not sure why that should work. Anyways, I did that, but our code plain and simple doesn't compile anymore. Not an issue with the IDE's linter, but compilation via CLI doesn't work.

The breaking change was highlighted in https://github.com/prisma/prisma/pull/27777. It just looks like it didn't make it into the changelog.

**Comment by Mreddi1** [comment]
Has any solution or fix been found for this problem?

**Comment by pasha-vuiko** [comment]
> Has any solution or fix been found for this problem?

Сhanging from

```ts
class PrismaService extends PrismaClient {}
```

to

```ts
class PrismaService extends PrismaClient<PrismaClientOptions, LogOptions<PrismaClientOptions>> {}
```

**Comment by a-rekkusu** [comment]
I'd prefer prisma using default type params here again. Using the workaround, I'd need to import `LogOptions` from `prisma/client/internal/class`, and that makes very clear it does not want to be imported directly: `Under no circumstances should you import this file directly!`

**Comment by mbaldi-orangeloops** [comment]
> I'd prefer prisma using default type params here again. Using the workaround, I'd need to import `LogOptions` from `prisma/client/internal/class`, and that makes very clear it does not want to be imported directly: `Under no circumstances should you import this file directly!`

To add up to this: a minor should not add breaking changes...

**Comment by TCarmine** [comment]
How this is considering closed is a mistery. The PrismaClient is still with now default.
