### ISSUE TITLE
"Prisma cannot obtain the TypeScript type of the transaction tx."

### ISSUE THREAD

**Issue by thresh111** [prisma/prisma#28543]
### Bug description

"When I write a transaction, Prisma does not provide type hints for tx, and following the official documentation and asking AI also cannot fix the issue."

<img width="1404" height="784" alt="Image" src="https://github.com/user-attachments/assets/adf8d8ff-77a0-4cc0-853b-6b327bd4c772" />

<img width="1596" height="1332" alt="Image" src="https://github.com/user-attachments/assets/f23f21c2-916f-4696-afe8-2e33997f44eb" />

### Severity

🚨 Critical: Data loss, app crash, security issue

### Expected vs. Actual Behavior

like this 

<img width="1502" height="738" alt="Image" src="https://github.com/user-attachments/assets/06030115-e54b-4696-9d18-96163d937747" />

but 

<img width="1302" height="524" alt="Image" src="https://github.com/user-attachments/assets/1bc3531e-4c82-40d1-aed7-dee4b0c82f83" />

### Frequency

Consistently reproducible

### Does this occur in development or production?

Only in development (e.g., CLI tools, migrations, Prisma Studio)

### Is this a regression?

    "prisma": "^6.18.0",

### Prisma Schema & Queries

generator client {
  provider        = "prisma-client"
  output          = "../generated/prisma"
  previewFeatures = ["interactiveTransactions"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

enum UserStatus {
  INACTIVE // 未激活（等待邮箱验证）
  ACTIVE // 已激活
  SUSPENDED // 已封禁
}

enum DeviceType {
  WEB // 网页浏览器
  DESKTOP // Electron 桌面应用
  IOS // iOS 设备
  ANDROID // Android 设备
  MOBILE // 移动端浏览器（通用）
  UNKNOWN // 未知设备
}

// 成员状态枚举（规范成员状态管理）
enum MemberStatus {
  ACTIVE // 激活（正常使用）
  DISABLED // 禁用（组织管理员操作）
  PENDING // 待审核（邀请后未确认）
  QUIT // 已退出（主动退出）
}

// 会话表
model Session {
  id           String     @id @default(cuid())
  userId       String
  token        String     @unique
  deviceType   DeviceType @default(UNKNOWN)
  ipAddress    String?
  userAgent    String?
  expiresAt    DateTime
  createdAt    DateTime   @default(now())
  lastActiveAt DateTime   @default(now())

  user User @relation(fields: [userId], references: [id])

  @@index([userId])
  @@index([expiresAt])
  @@map("session")
}

// 用户表
model User {
  id        String   @id @default(cuid())
  email     String   @unique
  username  String   @unique
  password  String
  avatar    String?
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  tokenVersion Int @default(1)

  // 账号状态
  status UserStatus @default(INACTIVE) // INACTIVE | ACTIVE | SUSPENDED

  sessions Session[]

  // 关联：用户加入的所有组织成员记录（1:N）
  organizationMembers OrganizationMember[]

  // 关联：用户拥有的所有组织（1:N）
  ownedOrganizations Organization[] @relation("OrganizationOwner")

  // 索引：优化用户查询（按邮箱/用户名检索）
  @@index([username])
  @@map("user")
}

// 组织表：存储组织核心信息
model Organization {
  id          String    @id @default(cuid())
  name        String // 组织名称
  slug        String    @unique @db.VarChar(64) // 组织唯一标识（用于URL/API）
  description String? // 组织描述
  logo        String? // 组织Logo URL
  createdAt   DateTime  @default(now()) // 创建时间
  updatedAt   DateTime  @updatedAt // 更新时间
  deletedAt   DateTime? // 软删除时间（逻辑删除）

  ownerId String // 组织所有者ID
  owner   User   @relation("OrganizationOwner", fields: [ownerId], references: [id])

  // 关联：组织下的成员（1:N）
  organizationMembers OrganizationMember[]
  // 关联：组织下的角色（1:N）
  roles               OrganizationRole[]
  // 关联：组织下的权限（1:N）
  permissions         OrganizationPermission[]

  // 索引：优化组织查询（按slug/名称检索）
  @@index([name])
  @@index([slug])
  @@map("organization")
}

// 组织成员表：用户与组织的关联表（1个用户在1个组织对应1条记录）
model OrganizationMember {
  id             String       @id @default(cuid())
  userId         String // 关联用户ID
  organizationId String // 关联组织ID
  joinedAt       DateTime     @default(now()) // 加入组织时间
  lastActiveAt   DateTime? // 最后活跃时间（用于成员活跃度统计）
  status         MemberStatus @default(ACTIVE) // 成员状态（激活/禁用/待审核）
  createdAt      DateTime     @default(now())
  updatedAt      DateTime     @updatedAt
  deletedAt      DateTime? // 软删除（退出组织）

  // 关联：所属用户（N:1）
  user            User                     @relation(fields: [userId], references: [id], onDelete: Cascade)
  // 关联：所属组织（N:1）
  organization    Organization             @relation(fields: [organizationId], references: [id], onDelete: Cascade)
  // 关联：成员的角色分配记录（1:N）
  roleAssignments OrganizationMemberRole[]

  // 核心约束：组织内成员唯一（1个用户在1个组织只能有1条成员记录）
  @@unique([userId, organizationId])
  // 索引：优化成员查询（按组织ID/用户ID/状态检索）
  @@index([organizationId])
  @@index([userId])
  @@index([organizationId, status])
  @@map("organization_member")
}

// 组织角色表：组织自定义角色（每个组织可独立定义角色）
model OrganizationRole {
  id          String  @id @default(cuid())
  name        String // 角色名称（如：管理员、编辑、只读成员）
  code        String // 角色唯一标识（如：ADMIN、MEMBER、GUEST）
  description String? // 角色描述
  // permissions Json[]                 // 角色权限列表（如：["ORG_MANAGE", "MEMBER_INVITE", "CONTENT_EDIT"]）
  isDefault   Boolean @default(false) // 是否为组织默认角色（新成员自动分配）

  organizationId String // 关联组织ID
  createdAt      DateTime  @default(now())
  updatedAt      DateTime  @updatedAt
  deletedAt      DateTime? // 软删除

  // 关联：所属组织（N:1）
  organization          Organization                 @relation(fields: [organizationId], references: [id], onDelete: Cascade)
  // 关联：角色的成员分配记录（1:N）
  roleAssignments       OrganizationMemberRole[]
  // 关联：角色的权限分配记录（1:N）
  permissionAssignments OrganizationRolePermission[]

  // 核心约束：组织内角色名称唯一（不同组织可重名）
  @@unique([organizationId, name])
  // 核心约束：组织内角色唯一（不同组织可重名code）
  @@unique([organizationId, code])
  // 索引：优化角色查询（按组织ID检索）
  @@index([organizationId])
  @@map("organization_role")
}

// 组织成员-角色关联表：实现「成员多角色」的多对多关联（带扩展字段）
model OrganizationMemberRole {
  id                   String   @id @default(cuid())
  organizationMemberId String // 关联组织成员ID
  organizationRoleId   String // 关联组织角色ID
  assignedBy           String? // 分配人ID（关联User.id）
  assignedAt           DateTime @default(now()) // 角色分配时间
  createdAt            DateTime @default(now())
  updatedAt            DateTime @updatedAt

  // 关联：所属组织成员（N:1）
  organizationMember OrganizationMember @relation(fields: [organizationMemberId], references: [id], onDelete: Cascade)
  // 关联：所属组织角色（N:1）
  organizationRole   OrganizationRole   @relation(fields: [organizationRoleId], references: [id], onDelete: Cascade)

  // 约束：1个成员在1个组织下不能重复分配同一个角色
  @@unique([organizationMemberId, organizationRoleId])
  // 索引：优化角色分配查询
  @@index([organizationMemberId])
  @@index([organizationRoleId])
  @@map("organization_member_role")
}

// 组织权限表：组织自定义权限（每个组织可独立定义权限）
model OrganizationPermission {
  id          String   @id @default(cuid())
  code        String // 权限唯一标识（如 "ORG_MANAGE", "MEMBER_INVITE", "ROLE_EDIT"）
  name        String // 权限名称（如 "组织管理", "成员邀请", "角色编辑"）
  description String? // 权限描述
  isSystem    Boolean  @default(false) // 是否为系统内置权限（不可删除）
  createdAt   DateTime @default(now())
  updatedAt   DateTime @updatedAt

  // 关联：所属组织（N:1）
  organizationId  String // 关联组织ID（外键）
  organization    Organization                 @relation(fields: [organizationId], references: [id], onDelete: Cascade)
  // 关联：拥有该权限的所有角色（1:N，通过中间表关联）
  roleAssignments OrganizationRolePermission[]

  // 唯一约束：同一组织内权限code唯一（不同组织可重名code）
  @@unique([code, organizationId])
  @@index([organizationId])
  @@map("organization_permission")
}

// 组织角色-权限关联表：实现「角色多权限」的多对多关联（带扩展字段）
model OrganizationRolePermission {
  id                       String   @id @default(cuid())
  organizationRoleId       String // 关联组织角色ID
  organizationPermissionId String // 关联组织权限ID
  assignedBy               String? // 分配人ID（关联User.id）
  assignedAt               DateTime @default(now()) // 权限分配时间
  createdAt                DateTime @default(now())
  updatedAt                DateTime @updatedAt

  // 关联：所属组织角色（N:1）
  organizationRole       OrganizationRole       @relation(fields: [organizationRoleId], references: [id], onDelete: Cascade)
  // 关联：所属组织权限（N:1）
  organizationPermission OrganizationPermission @relation(fields: [organizationPermissionId], references: [id], onDelete: Cascade)

  // 约束：1个角色不能重复分配同一个权限
  @@unique([organizationRoleId, organizationPermissionId])
  // 索引：优化权限分配查询
  @@index([organizationRoleId])
  @@index([organizationPermissionId])
  @@map("organization_role_permission")
}

### Prisma Config

```ts
// Add your `prisma.config.ts`
```

### Logs & Debug Info

```
// Debug logs here
```

### Environment & Setup

- **OS:** 
- **Database:** 
- **Node.js version:** 

### Prisma Version

```
// Prisma version output
```

**Comment by murray484** [comment]
I am also having this issue with Prisma 7.  My transaction code worked fine on 6.16, but jumping to 7 I get type errors like this:

`Property 'estimate' does not exist on type 'Omit<PrismaClient<never, undefined, runtime.Types.Extensions.DefaultArgs>, runtime.ITXClientDenyList>'.ts(2339)`

Here is a sample of where I am using a transaction:
```ts
return prisma.$transaction(async (tx) => {
    // 1) Create the estimate
    const estimate = await tx.estimate.create({
      data: {
        date: input.date,
        validUntil: input.validUntil,
        description: input.description,
        notes: input.notes,
        status: input.status,
        customer: input.customerId
          ? { connect: { id: input.customerId } }
          : undefined,
      },
    });

   /* more unrelated code... */

});
```

This code was working fine before I moved to V7.  This is a blocking issue for me and will prevent me from moving to V7.

**Comment by murray484** [comment]
Update: Keeping V7 but switching to prisma-client-js instead of the new rust-free client solved the issue for me.

**Comment by 791045873** [comment]
> Update: Keeping V7 but switching to prisma-client-js instead of the new rust-free client solved the issue for me.

same problem。have other solution except this?
 prisma-client-js is deprecated, I dont want to use it.
thanks.

**Comment by 791045873** [comment]
> > Update: Keeping V7 but switching to prisma-client-js instead of the new rust-free client solved the issue for me.
> 
> same problem。have other solution except this? prisma-client-js is deprecated, I dont want to use it. thanks.

if your prisma version > 7, npm install @prisma/client, this problem will be fixed
