### ISSUE TITLE
Prisma 6.12.0 - Cannot find module '@prisma/client/runtime/query_compiler_bg.postgresql.wasm'

### ISSUE THREAD

**Issue by cipriancaba** [prisma/prisma#27754]
### Bug description

Error [PrismaClientKnownRequestError]: 
Invalid `prisma.userProfile.findUnique()` invocation:

Cannot find module '@prisma/client/runtime/query_compiler_bg.postgresql.wasm'
Require stack:
- /vercel/path0/packages/db/client/internal/class.ts
    at async Q.tags (.next/server/chunks/3542.js:1:13760)
    at async (.next/server/chunks/6791.js:1:10600)
    at async k (.next/server/app/[locale]/[params]/(signedin)/page.js:2:8158) {
  code: 'MODULE_NOT_FOUND',
  meta: [Object],
  clientVersion: '6.12.0',
  digest: '4054779382'
}

### Severity

⚠️ Major: Breaks core functionality (e.g., migrations fail)

### Reproduction

https://codesandbox.io/examples/package/prisma

### Expected vs. Actual Behavior

The no rust compiler should have solved all these issues, but they are still here when building on vercel

### Frequency

Consistently reproducible

### Does this occur in development or production?

Only in production (e.g., query engine, generated client)

### Is this a regression?

Never worked

### Workaround

Blocker for no rust mode

### Prisma Schema & Queries

generator client {
  provider               = "prisma-client"
  output                 = "../client"
  moduleFormat           = "esm" // "esm" or `"cjs"` for CommonJS
  runtime                = "nodejs"
  generatedFileExtension = "ts"
  importFileExtension    = ""
  previewFeatures        = ["queryCompiler", "driverAdapters", "multiSchema", "views", "relationJoins"]
}

datasource db {
  provider  = "postgresql"
  url       = env("DATABASE_URL")
  directUrl = env("DIRECT_URL")
  schemas   = ["public", "storage", "crm", "audit"]
}

### Prisma Config

```ts
// Add your `prisma.config.ts`
```

### Logs & Debug Info

```
// Debug logs here
```

### Environment & Setup

macos, next 15.4.4

### Prisma Version

6.12.0

**Comment by jkomyno** [comment]
Hi @cipriancaba, can you please try this integration version of Prisma: [prisma@6.14.0-integration-feat-client-wasm-base64-on-nodejs.6](https://www.npmjs.com/package/prisma/v/6.14.0-integration-feat-client-wasm-base64-on-nodejs.6) (from https://github.com/prisma/prisma/pull/27795) and report back?

Make sure to re-run `prisma generate` after the update.

Handy update script for your projects:
```
pnpm update "@prisma/*"@6.14.0-integration-feat-client-wasm-base64-on-nodejs.6
pnpm update "prisma"@6.14.0-integration-feat-client-wasm-base64-on-nodejs.6
pnpm prisma generate
```

We aim to stabilize the `prisma-client` generator as "generally available" within the next 3 weeks, so your feedback is helpful!
Thanks

**Comment by EvHaus** [comment]
@jkomyno Still getting:

```
Cannot find module '@prisma/client/runtime/query_compiler_bg.postgresql.wasm'
```

When using `6.14.0-integration-feat-client-wasm-base64-on-nodejs.6"`

Anything I can do to help debug this further?

**Comment by jkomyno** [comment]
@EvHaus can you please share your project, or a minimal reproduction of it?
Have you re-run `prisma generate`? Sometimes cleaning up the folders that are not committed to Git also helps (e.g., removing `.output`, `.next`, `.nuxt`, `node_modules`, .., and re-running `pnpm install`, `pnpm prisma generate`, `pnpm build` etc)

**Comment by EvHaus** [comment]
@jkomyno Resetting build files and node_modules didn't help my case. I'm building/running via a Docker container anyway, so stale files are unlikely the cause of this.

I created a minimal repro in: https://github.com/EvHaus/prisma-27754-bug

It works locally on my Mac just fine, but inside the Docker container, you get the same error.

**Comment by jkomyno** [comment]
@EvHaus hey, I've investigated https://github.com/EvHaus/prisma-27754-bug, yours is a different issue.

First off, you're alternating Node.js with Bun in the Dockerfile, while specifying just `runtime = "bun"` in the `prisma-client` generator block in your Prisma schema.

Moreover, you're using `bun build --compile`, which doesn't bundle the `.wasm` files from `@prisma/client/runtime` that you'd normally find in `node_modules`, because `node_modules` doesn't exist in the Docker `final` image.

---

Your code will work fine if you replace your `prisma-client` generator as follows:

```
generator client {
  provider            = "prisma-client"
  output              = "../generated"
  previewFeatures     = ["driverAdapters", "queryCompiler", "relationJoins"]
  runtime             = "nodejs"
}
```

**Comment by EvHaus** [comment]
Thanks @jkomyno. Switching runtime to `nodejs` fixed the issue for me.

**Comment by dani-mp** [comment]
another day, another prisma issue 🙌

**Comment by jkomyno** [comment]
Hey @EvHaus, fyi in the latest version of Prisma (6.15.0) you can write `runtime = "bun"` in the [generator code I posted earlier](https://github.com/prisma/prisma/issues/27754#issuecomment-3161080103), and that should work as expected in Bun :)

**Comment by jkomyno** [comment]
> another day, another prisma issue 🙌

@dani-mp, I'm not sure what you mean by that. The scenario described by EvHaus was actually a Bun issue (specifically about `bun build`, not `bun run`) that we at Prisma had to work around.

If you have any reproducible `prisma-client` specific issue that we haven't addressed yet, I invite you to share a link here, and I'll take a look. Thanks!

**Comment by dani-mp** [comment]
@jkomyno what i mean is that i've been using prisma 6.12 for some weeks (with the ugly workaround i shared in the other issue) and suddenly yesterday, after an unrelated deployment, my app stopped working because of an issue with prisma, similar to this one (but mysql instead of postgresql)

it didn't take me long to find this issue (the original issue is not about bun, i think, and i'm not using bun at all either)

the weird thing is that nothing related to prisma had changed in my project, and it was working just the day before, but when i downloaded the lambda zip, the @prisma/client was there, but inside the runtime folder, there was no `query_compiler_bg.mysql.wasm` file anymore, i could only see similar files with `base64` in the filename, which didn't seem what your own code was expecting - the file was there locally, though, which made debugging the issue more difficult

so i don't know how this happened and why the underlying files changed suddenly under the hood, but i just yolo-upgraded to prisma 6.15 and that solved the sudden issue (no other changes needed), and i could also remove the ugly workaround i had to fix the `__dirname`

**Comment by EvHaus** [comment]
> Hey [@EvHaus](https://github.com/EvHaus), fyi in the latest version of Prisma (6.15.0) you can write `runtime = "bun"` in the [generator code I posted earlier](https://github.com/prisma/prisma/issues/27754#issuecomment-3161080103), and that should work as expected in Bun :)

Thanks. I've confirmed this works as expected. 👍

**Comment by MykhailoYa** [comment]
The solution that helped in my case:
Just upgraded both the `prisma` and the `@prisma/client` dependencies to 6.16.2

**Comment by chrisdel101** [comment]
I've been using 7.2 for at least a month when all of a sudden i started to get this. Few hours or work and I can't get past it. 

Edit: This was freakin nasty man. Seems to be working again for now. 
    
     npm install @prisma/engines@latest prisma@latest @prisma/client@latest --force --foreground-scripts

**Comment by Dev10-34** [comment]
> I've been using 7.2 for at least a month when all of a sudden i started to get this. Few hours or work and I can't get past it.
> 
> Edit: This was freakin nasty man. Seems to be working again for now.
> 
> ```
>  npm install @prisma/engines@latest prisma@latest @prisma/client@latest --force --foreground-scripts
> ```

I updated to 7.3 as well and still facing this issue? does this mean i need to do the above steps specifically to fix this issue? npm update wouldn't suffice I am assuming then?

**Comment by chrisdel101** [comment]
@Dev10-34 just to note that I did lost all my data doing this. I'm still early stage so it was ok for me.
 I'm def no prisma expert. I chose to delete migrations and table rather than fight with it.

**Comment by lambou** [comment]
prisma 7.2.0 , @prisma/client 7.2.0 and nextjs 16.1.3

```txt
Prisma schema loaded from prisma/schema.
Error: 
Cannot find module '/vercel/path0/node_modules/@prisma/client/runtime/query_compiler_fast_bg.postgresql.wasm-base64.js'
Require stack:
- /vercel/path0/node_modules/prisma/build/index.js
```

Had the same issue after installing a package and running npm audit fix.

to fix it i had to delete the `package-lock.json` with `node_modules` folder and ran npm install.

Everything is back to normal.

**Comment by bbird-21** [comment]
For anyone still encountering this issue, in my case it was caused by a version mismatch between Prisma packages.
```
➜  npx prisma --version           
Loaded Prisma config from prisma.config.ts.

Prisma schema loaded from prisma/schema/schema.prisma.
prisma               : 7.3.0
@prisma/client       : 7.2.0
Operating System     : linux
Architecture         : x64
Node.js              : v22.19.0
TypeScript           : 5.9.3
Query Compiler       : enabled
PSL                  : @prisma/prisma-schema-wasm 7.3.0-16.9d6ad21cbbceab97458517b147a6a09ff43aa735
Schema Engine        : schema-engine-cli 9d6ad21cbbceab97458517b147a6a09ff43aa735 (at ../../node_modules/@prisma/engines/schema-engine-debian-openssl-3.0.x)
Default Engines Hash : 9d6ad21cbbceab97458517b147a6a09ff43aa735
Studio               : 0.13.1
```

After upgrading @prisma/client to 7.3.0 to match the Prisma CLI version, the issue was resolved.

**Comment by Mike-Ro** [comment]
@bbird-21 it's working for me

**Comment by endrureza** [comment]
I kept getting this error even with so much changes above. I'm using Nextjs v14 by the way and Prisma v7.4.0.

Edit: My bad, i used to import enum directly from @prisma/client, and it causes this error. I started to import enum from generated/prisma/enum and now it's working again.
