### ISSUE TITLE
In Prisma 7, extending with accelerate drops relations in types under certain conditions

### ISSUE THREAD

**Issue by janoma** [prisma/prisma#28703]
### Bug description

Selected relations are dropped from the type under some conditions in `where` clauses. So far, I've reproduced this with `in`, for example `where: { foo: { in: ['bar', 'baz'] } }`. The provided reproduction repository illustrates that.

Marking this as major since project cannot be built with Prisma 7 in these conditions, or I'd have to drop Accelerate, which is far from ideal. More importantly, it breaks core functionality.

### Severity

⚠️ Major: Breaks core functionality (e.g., migrations fail)

### Reproduction

[Reproduction repository](https://github.com/janoma/prisma-7-bug).

The following block is OK:
```ts
const users = await prisma.user.findMany({
  include: { posts: true },
  where: { id: 1 }
});

const total = users.map((user) => user.posts.length)
//                                       ^? (property) posts: { id: number; authorId: ...
```

Replace the `where` clause for the one that fails and see the error on `user.posts`:

```ts
const users = await prisma.user.findMany({
  include: { posts: true },
  where: { id: { in: [1]}}
});

const total = users.map((user) => user.posts.length)
//                                       ^? any
```

<img width="1001" height="231" alt="Image" src="https://github.com/user-attachments/assets/e4c6bff7-5cbd-4432-bb7d-74325c950bab" />

Using `select` instead of `include` does not fix the issue. The type of the relation is dropped too.

#### Expected behavior

No type errors.

#### Actual behavior

`posts` is dropped from each user object in the typed response:

```sh
Property 'posts' does not exist on type '{ id: number; }'.ts(2339)
```

### Frequency

Consistently reproducible

### Does this occur in development or production?

Both development and production

### Is this a regression?

This worked with `@prisma/extension-accelerate@1.3.0`, `@prisma/client@6.19.0` and `prisma@6.19.0`.

### Workaround

1. Remove `$extends(withAccelerate())`, _or_
2. Downgrade to `prisma@6.19.0`, `@prisma/client@6.19.0` and `@prisma/extension-accelerate@1.3.0`

#### Model

```prisma
model User {
  id    Int    @id @default(autoincrement())
  posts Post[]
}

model Post {
  id        Int    @id @default(autoincrement())
  author    User   @relation(fields: [authorId], references: [id])
  authorId  Int
}
```

#### Query

```ts
  const users = await prisma.user.findMany({
    include: { posts: true },
    where: { id: { in: [1] }}
  });
```

#### Prisma Config

```ts
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
```

### Logs & Debug Info

Not applicable since this is a type error.

### Environment & Setup

- **OS:** macOS 15.6.1
- **Database:** PostgreSQL
- **Node.js version:** 22.19.0

### Prisma Version

```
prisma               : 7.0.0
@prisma/client       : 7.0.0
Operating System     : darwin
Architecture         : arm64
Node.js              : v22.19.0
TypeScript           : 5.9.3
Query Compiler       : enabled
PSL                  : @prisma/prisma-schema-wasm 6.20.0-16.next-0c19ccc313cf9911a90d99d2ac2eb0280c76c513
Schema Engine        : schema-engine-cli 0c19ccc313cf9911a90d99d2ac2eb0280c76c513 (at node_modules/.pnpm/@prisma+engines@7.0.0/node_modules/@prisma/engines/schema-engine-darwin-arm64)
Default Engines Hash : 0c19ccc313cf9911a90d99d2ac2eb0280c76c513
Studio               : 0.8.0
```

### Related issues

Possibly related to [issue 28661](https://github.com/prisma/prisma/issues/28661).

**Comment by samuelcole** [comment]
I had a similar issue when my `select`s are defined elsewhere: https://github.com/prisma/prisma/issues/28580#issuecomment-3564240310

**Comment by francofantini** [comment]
I believe that `.$extends` in general is breaking the types. I'm having the same error with read replicas.
```ts
.$extends(readReplicas({ ... }))
```

**Comment by janoma** [comment]
> I believe that `.$extends` in general is breaking the types. I'm having the same error with read replicas.
> 
> .$extends(readReplicas({ ... }))

It's very likely, but it seems that the argument to `$extends` makes _some_ difference. For example, in my bug report repository, if you replace `withAccelerate()` with `readReplicas({ url: env("REPLICA_URL") })`, you still get the error but at a different level:

```ts
  const users = await prisma.user.findMany();
  //      ^? const users: any
```

However, with `withAccelerate()` the type of users is correct:

```ts
  const users = await prisma.user.findMany();
  //      ^? const users: { id: number }[]
```

Still, it's broken in both cases, but I think this is good info for whoever has to confirm and debug.

**Comment by FGoessler** [comment]
@francofantini  We are currently working on a fix for the read-replicas extension. The failure there that results to the general `any` type is that the import path inside the extension that imports `'@prisma/client/runtime/library'` needs to be updated to `'@prisma/client/runtime/client'`. 
But our updates to the read replicas extension will also include some other changes to account for the driver-adapter based setup. 

@janoma Based on my debugging of this type issue here I can confirm that its specific to the accelerate extension. Am verifying a potential fix for this.

@samuelcole Your issue I was not bale to reproduce so far. Could you please provide a standalone reproduction example using the latest extension versions? Thank you!

**Comment by francofantini** [comment]
Hi @FGoessler, do you have an ETA on the fix for `extension-read-replicas`? Thanks in advance.

**Comment by FGoessler** [comment]
We just shipped `@prisma/extension-accelerate` version `3.0.1` with a fix for the issue described here. 

Please let us know should you run into further issues with the accelerate extension types. 

Thank you for your patience! 🙏

**Comment by janoma** [comment]
Thank you Florian. I tested locally with the reproduction repository and it seems to work there. Will test later with the production repository too.

**Comment by ryanburns23** [comment]
@FGoessler this update fixed issues in a few places but broke types in other places:

Example 1:
```ts
const data = await prisma.articles.findMany({
    where: {
      status: 'published',
    },
    select: { 
      title: true,  
      tags: {
        select: {
          label: true,
          id: true,
          slug: true,
        },
      }
    }
  });
```
 
The type produced by this query does not respect the select param. The type of `data` contains all fields from the schema and omits included relations.

Example with broken types:
<img width="431" height="525" alt="Image" src="https://github.com/user-attachments/assets/0a1800a9-4073-4577-8713-94121dd594f5" />

If I omit the where query, the types are correct:
<img width="370" height="388" alt="Image" src="https://github.com/user-attachments/assets/4d774be8-7fc3-4e49-b35f-4c6c5b1929a8" />


Example 2:

Here is another query that was working correctly on `3.0.0` but has issues after upgrading to `3.0.1`
Broken types on `3.0.1`
<img width="397" height="567" alt="Image" src="https://github.com/user-attachments/assets/bb43b760-a01a-4c07-8f60-ba698e1001e7" />

Working on `3.0.0`
<img width="394" height="568" alt="Image" src="https://github.com/user-attachments/assets/1de156fa-31cf-40dd-9fd5-54af53aa86a2" />

**Comment by janoma** [comment]
@FGoessler can you reopen this issue? I was able to reproduce the failure reported by @ryanburns23. I have updated the reproduction repository with the example. The type includes columns that are not selected (like `id` and `authorId`, and it does not include `tags`, which _is_ selected.

The issues go away after removing `$extends(withAccelerate())` in `prisma.ts`.

Failing versions:
```
   "prisma": "7.1.0",
    "@prisma/client": "7.1.0",
    "@prisma/extension-accelerate": "3.0.1",
```

**Comment by naqashse102** [comment]
@janoma same getting here with version 7.2.0
[https://github.com/prisma/prisma/issues/28970#issuecomment-3702125039](url)

**Comment by nurul3101** [comment]
@janoma @naqashse102 Can you please try this experimental version and verify if the issue is fixed?

```json
"@prisma/extension-accelerate": "0.0.0-experimental-425470e"
```

I verified this with the reproduction [repository](https://github.com/janoma/prisma-7-bug) and it seems to be fixed now. Please let me know if this fixes the issue for you.

**Comment by fidalgodev** [comment]
> [@janoma](https://github.com/janoma) [@naqashse102](https://github.com/naqashse102) Can you please try this experimental version and verify if the issue is fixed?
> 
> "@prisma/extension-accelerate": "0.0.0-experimental-425470e"
> I verified this with the reproduction [repository](https://github.com/janoma/prisma-7-bug) and it seems to be fixed now. Please let me know if this fixes the issue for you.

```ts
"prisma": "^7.2.0",
"@prisma/extension-accelerate": "^3.0.1",
"@prisma/client": "^7.2.0",
```

Also having the same type inference issues.
@nurul3101 has this not been fixed?

**Comment by Alejoxd70** [comment]
> > [@janoma](https://github.com/janoma) [@naqashse102](https://github.com/naqashse102) Can you please try this experimental version and verify if the issue is fixed?
> > "@prisma/extension-accelerate": "0.0.0-experimental-425470e"
> > I verified this with the reproduction [repository](https://github.com/janoma/prisma-7-bug) and it seems to be fixed now. Please let me know if this fixes the issue for you.
> 
> "prisma": "^7.2.0",
> "@prisma/extension-accelerate": "^3.0.1",
> "@prisma/client": "^7.2.0",
> Also having the same type inference issues. [@nurul3101](https://github.com/nurul3101) has this not been fixed?

The best thing to do is downgrade the version, It worked for me, I think they are reviewing the issue

**Comment by janoma** [comment]
Hello from 6 months after original post. The [reproduction repository](https://github.com/janoma/prisma-7-bug) is still showing the same failure with Prisma 7.8.0. I don't know why this was ever closed, or why it wasn't reopen when people (including myself) reported repeated failures.

@nurul3101 @FGoessler
