### ISSUE TITLE
Interactive Transactions: fatal when throwing string instead of Error() since 3.10.0

### ISSUE THREAD

**Issue by andyjy** [prisma/prisma#12663]
### Bug description

works in 3.9.2, fatals as of 3.10.0:

```
await prisma.$transaction((prisma) => { throw "abort transaction"; }) // throwing string, not new Error()
```

error since 3.10.0: `TypeError: Cannot create property 'clientVersion' on string "abort transaction"`

### How to reproduce

^- code above, this one seems straightforward but just let me know if reproduction repo required

### Expected behavior

able to throw an expression of type as an error, as accepted by Typescript compiler
(yes I do typically follow best practice re: `Error`s 😉 ; this broke a unit test that was rolling back a transaction where there wasn't need for a full `Error`)

### Prisma information

N/A

### Environment & setup

- OS: Mac OS
- Database: Postgres
- Node.js version: 14

### Prisma Version

worked in versions up to + including `3.9.2`, fails in `3.10.0` and `3.11.1`

**Comment by janpio** [comment]
I can confirm this:

```
C:\Users\Jan\Documents\throwaway\slackUuid>node script.js
  prisma:tryLoadEnv Environment variables not found at null +0ms
  prisma:tryLoadEnv Environment variables not found at undefined +3ms
  prisma:tryLoadEnv No Environment variables loaded +0ms
  prisma:tryLoadEnv Environment variables not found at null +2ms
  prisma:tryLoadEnv Environment variables not found at undefined +0ms
  prisma:tryLoadEnv No Environment variables loaded +1ms
  prisma:client dirname C:\Users\Jan\Documents\throwaway\slackUuid\node_modules\.prisma\client +0ms
  prisma:client relativePath ..\..\.. +0ms
  prisma:client cwd C:\Users\Jan\Documents\throwaway\slackUuid +1ms
  prisma:client clientVersion: 3.11.1 +4ms
  prisma:client clientEngineType: library +0ms
  prisma:client:libraryEngine internalSetup +0ms
TypeError: promises.map is not a function
    at Proxy._transactionWithArray (C:\Users\Jan\Documents\throwaway\slackUuid\node_modules\@prisma\client\runtime\index.js:40597:34)
    at Proxy.$transaction (C:\Users\Jan\Documents\throwaway\slackUuid\node_modules\@prisma\client\runtime\index.js:40622:21)
    at main (C:\Users\Jan\Documents\throwaway\slackUuid\script.js:20:18)
    at Object.<anonymous> (C:\Users\Jan\Documents\throwaway\slackUuid\script.js:25:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
  prisma:client:libraryEngine hookProcess received: exit +25ms
  prisma:client:libraryEngine runBeforeExit +1ms

C:\Users\Jan\Documents\throwaway\slackUuid>node script.js
C:\Users\Jan\Documents\throwaway\slackUuid\script.js:21
        await prisma.$connect();
        ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1032:15)
    at Module._compile (node:internal/modules/cjs/loader:1067:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 

C:\Users\Jan\Documents\throwaway\slackUuid>npm install prisma@3.9.2 @prisma/client@3.9.2
  agentkeepalive sock[0#registry.npmjs.org:443::::::::true:::::::::::::] create, timeout 300001ms +0ms
  agentkeepalive sock[0#registry.npmjs.org:443::::::::true:::::::::::::](requests: 1, finished: 1) free +401msin 169ms

changed 4 packages, and audited 5 packages in 5s

found 0 vulnerabilities

C:\Users\Jan\Documents\throwaway\slackUuid>node script.js
  prisma:tryLoadEnv Environment variables not found at null +0ms
  prisma:tryLoadEnv Environment variables not found at undefined +2ms
  prisma:tryLoadEnv No Environment variables loaded +1ms
  prisma:tryLoadEnv Environment variables not found at null +2ms
  prisma:tryLoadEnv Environment variables not found at undefined +0ms
  prisma:tryLoadEnv No Environment variables loaded +0ms
  prisma:client clientVersion: 3.9.2 +0ms
  prisma:client clientEngineType: library +0ms
  prisma:client:libraryEngine internalSetup +0ms
  prisma:client:libraryEngine Searching for Query Engine Library in C:\Users\Jan\Documents\throwaway\slackUuid\node_modules\.prisma\client +4ms
  prisma:client:libraryEngine loadEngine using C:\Users\Jan\Documents\throwaway\slackUuid\node_modules\.prisma\client\query_engine-windows.dll.node +1ms
  prisma:client:libraryEngine library starting +60ms
prisma:info Starting a postgresql pool with 9 connections.
  prisma:client:libraryEngine library started +828ms
abort transaction
  prisma:client:libraryEngine hookProcess received: exit +231ms
  prisma:client:libraryEngine runBeforeExit +1ms
```
