### ISSUE TITLE
Error after Upgrading from 5.8.1 to 5.9.0

### ISSUE THREAD

**Issue by paulwer** [prisma/prisma#22875]
### Bug description

After upgrading the following error is shown:
```
Error: Cannot find module 'F:\XXX\XXX\backend\node_modules\@prisma\client\runtime\library'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:1060:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:1053:15)
    at resolveExports (node:internal/modules/cjs/loader:538:14)
    at Function.Module._findPath (node:internal/modules/cjs/loader:607:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1025:27)
    at Function.Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (F:\dev\ecence\backend\src\models\user\user.service.ts:7:1)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
```

### Expected behavior

Run Application. Works fine on 5.8.1.

I guess this error occurs because of the following line in our nestjs application:
```
import { PrismaClientKnownRequestError } from '@prisma/client/runtime/library';
```

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: Windows
- Database: MySQL 8
- Node.js version: 18.13.0

### Prisma Version

```
v5.9.0
```

**Comment by Jolg42** [comment]
Note: We think this is a regression and already tracked in https://github.com/prisma/prisma/issues/22870

We're investigating and we expect to fix this in a patch release soon.

We'll keep you updated, in the meantime, you can stay on `5.8.1` until we release `5.9.1`.

**Comment by millsp** [comment]
Hey, can you please import it from `@prisma/client`?

```ts
import { PrismaClientKnownRequestError } from '@prisma/client'
```

**Comment by don-cryptus** [comment]
having the same issue currently

**Comment by janpio** [comment]
See here for our in progress fix: https://github.com/prisma/prisma/issues/22870#issuecomment-1917587412

**Comment by marcelino-borges** [comment]
After upgrading to 5.9.0 today I started to have issues with my generated types, after renaming a column name and running a migration. I had to rollback... =/

**Comment by millsp** [comment]
Hey @marcelino-borges, could you please try out an integration version proposed in this [issue](https://github.com/prisma/prisma/issues/22870#issuecomment-1917587412) by my colleague and report there if that fixed it for you? Thanks.

**Comment by paulwer** [comment]
> Hey, can you please import it from `@prisma/client`? I am asking you this because you are importing an internal implementation.
> 
> ```ts
> import { Prisma } from '@prisma/client'
> 
> Prisma.PrismaClientKnownRequestError
> ```

this worked for me. From my pov this can be closed

**Comment by lamuertepeluda** [comment]
> ```ts
> ```ts
> Prisma.PrismaClientKnownRequestError
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

This works _only_ when you generate the client.

Beware of this when you want just the base constructor, e.g. you are extending the class like in https://github.com/prisma/prisma/issues/22875#issuecomment-1918397215

**Comment by Jolg42** [comment]
Hello here 👋🏼 @paulwer @lamuertepeluda @marcelino-borges @0-don 
@millsp already worked on a fix in https://github.com/prisma/prisma/pull/22880 

Could you try this version `5.10.0-integration-fix-client-exports-map.10` and let us know if that fixes the issue?

Note that like mentioned earlier, importing via `@prisma/client/runtime/library` is not recommended as it is deprecated (see for example https://github.com/prisma/prisma/discussions/17832) 

We recommend you to switch to something like this:
```
import { PrismaClientKnownRequestError } from '@prisma/client';
```

**Comment by wassimbj** [comment]
I also ran an existing project with prisma client set to 5.9.1 and i get the same issue above in the description, i've tried to downgrade to 5.8.1 and i also have the same issue, note that an previous developer was working on this project fine until i came :)

**Comment by Jolg42** [comment]
@wassimbj `5.9.1` is not released yet (stay tuned)

Did you try `5.10.0-integration-fix-client-exports-map.10` or `5.10.0-integration-fix-client-exports-map.11` already?

**Comment by wassimbj** [comment]
Yes i'm just installing it i'll update my answer once i test it

**Comment by markoorn** [comment]
Not sure if this should be marked as completed until v5.9.1 is released (any ETA on that?)

**Comment by millsp** [comment]
We are working on the release as we speak, I will keep you updated.

**Comment by Jolg42** [comment]
https://github.com/prisma/prisma/releases/tag/5.9.1 is now available with the fix ✨ 

Please create [a new issue](https://github.com/prisma/prisma/issues/new/choose) if you find a bug.

**Comment by markoorn** [comment]
I can confirm that 5.9.1 resolves the issue - thanks for the quick fix!
