### ISSUE TITLE
In Prisma 7, extending with accelerate drops some relations in types

### ISSUE THREAD

**Issue by janoma** [prisma/prisma#29627]
### Bug description

(This is a follow up from #28703, which was opened back in November and closed at some point but the problem is still there.)

Selected relations are dropped from the type under some conditions in `where` clauses.

Marking this as major since my project still cannot be built with Prisma 7, or I'd have to drop Accelerate, which is far from ideal. More importantly, it breaks core functionality that works fine with Prisma 6.

### Severity

⚠️ Major: Breaks core functionality (e.g., migrations fail)

### Reproduction

[Reproduction repository](https://github.com/janoma/prisma-7-bug).

1. `git clone https://github.com/janoma/prisma-7-bug`
2. Install dependencies with `pnpm install`
3. Run `pnpm typecheck`, observer the type error
4. Remove the `where` clause in `index.ts`, run `pnpm typecheck`, observe no type error

### Expected vs. Actual Behavior

**Expected**
No type errors. `tags` is selected in the query. It should be available regardless of the `where` clause.

**Actual**
Type errors. `tags` is not available when the `where` clause is `status: "published"`.

```
index.ts:20:51 - error TS2339: Property 'tags' does not exist on type '{ id: number; title: string; status: ArticleStatus; authorId: number; }'.

20   const tagsCount = data.map((article) => article.tags.length);
                                                     ~~~~


Found 1 error in index.ts:20
```

### Frequency

Consistently reproducible

### Does this occur in development or production?

Both development and production

### Is this a regression?

Yes. This works with `@prisma/extension-accelerate@1.3.0`, `@prisma/client@6.19.3` and `prisma@6.19.3`.

### Workaround

1. Remove `$extends(withAccelerate())`, or
2. Downgrade to `prisma@6.19.3`, `@prisma/client@6.19.3` and `@prisma/extension-accelerate@1.3.0`

### Prisma Schema & Queries

```prisma
model Article {
  id       Int           @id @default(autoincrement())
  status   ArticleStatus @default(draft)
  title    String
  tags     Tag[]
}
```
```ts
const data = await prisma.article.findMany({
    where: {
      status: "published",
    },
    select: {
      title: true,
      tags: {
        select: {
          label: true,
          id: true,
          slug: true,
        },
      },
    },
  });
```

### Prisma Config

```ts
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
```

### Environment & Setup

- **OS:** macOS 26.5.1
- **Database:** PostgreSQL
- **Node.js version:** 24.12.0

### Prisma Version

```
Loaded Prisma config from prisma.config.ts.

Prisma schema loaded from prisma/schema.prisma.
prisma               : 7.8.0
@prisma/client       : 7.8.0
Operating System     : darwin
Architecture         : arm64
Node.js              : v24.12.0
TypeScript           : 6.0.3
Query Compiler       : enabled
PSL                  : @prisma/prisma-schema-wasm 7.8.0-6.3c6e192761c0362d496ed980de936e2f3cebcd3a
Schema Engine        : schema-engine-cli 3c6e192761c0362d496ed980de936e2f3cebcd3a (at node_modules/.pnpm/@prisma+engines@7.8.0/node_modules/@prisma/engines/schema-engine-darwin-arm64)
Default Engines Hash : 3c6e192761c0362d496ed980de936e2f3cebcd3a
Studio               : 0.27.3
```

**Comment by AnupamKumar-1** [comment]
I was able to reproduce this issue using the provided reproduction repository. I’ll investigate the root cause and see if I can put together a fix.
