### ISSUE TITLE
Upgrading from Prisma 5.0.0 -> 5.1.0 results in "TS2321: Excessive stack depth comparing types" error using `mockDeep<PrismaClient>()`

### ISSUE THREAD

**Issue by linjer** [prisma/prisma#20516]
### Bug description

We use the InversifyJS dependency injection framework and Typescript 5.1.6. When upgrading from Prisma 5.0.0 to 5.1.0 with no other code changes, `tsc` results in the following error:

```
... - error TS2321: Excessive stack depth comparing types 'DeepMockProxy<PrismaClient<PrismaClientOptions, never, DefaultArgs>>' and 'PrismaClient<PrismaClientOptions, unknown, Args_2>'.

31   tc.bind(PrismaClient).toConstantValue(mockDeep<PrismaClient>());
```

Not sure if there are workarounds, but this directly reflects the recommended practice from the Prisma guide on unit testing here: https://www.prisma.io/docs/guides/testing/unit-testing#dependency-injection

### How to reproduce

1. Follow Prisma unit testing guide for dependency testing here: https://www.prisma.io/docs/guides/testing/unit-testing#dependency-injection
2. Use `mockDeep<PrismaClient>()` in a unit test
3. Upgrade to Prisma 5.1.0
4. Run TypeScript (i.e. v5.1.6) typechecker

### Expected behavior

TS compilation and typecheck behavior matches 5.0.0.

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
  const tc = new Container();
  tc.bind(PrismaClient).toConstantValue(mockDeep<PrismaClient>());
  return tc;
```

### Environment & setup

- OS: macOS and Debian
- Database: PostgreSQL
- Node.js version: 18.6.0

### Prisma Version

```
5.1.0
```

**Comment by millsp** [comment]
After taking a look, I can confirm that is this not an issue on our end but rather the result of a very resource intensive type implementation in `jest-mock-extended` which was revealed via recent changes. I tried what would be my suggested changes locally and can confirm that after that everything works well, without any change on Prisma's side. I'd be happy to open an PR there. Thanks for the report.

**Comment by millsp** [comment]
https://github.com/marchaos/jest-mock-extended/pull/123

**Comment by janpio** [comment]
This has already been released as `jest-mock-extended@3.0.5` - can you check if using that version resolves your problem @linjer?

**Comment by linjer** [comment]
@janpio After upgrading to `jest-mock-eextended@3.0.5` I no longer have the issue 👍

**Comment by linjer** [comment]
@millsp @janpio Oddly though, maybe worth mentioning is that the tests run fine now, but I now see a different/strange typecheck error:

```
/.../node_modules/typescript/lib/tsc.js:114888
      throw e;
      ^

Error: Debug Failure. No error for last overload signature
    at resolveCall (/.../node_modules/typescript/lib/tsc.js:70364:19)
    at resolveCallExpression (/.../node_modules/typescript/lib/tsc.js:70746:12)
    at resolveSignature (/.../node_modules/typescript/lib/tsc.js:71129:16)
    at getResolvedSignature (/.../node_modules/typescript/lib/tsc.js:71149:18)
    at checkCallExpression (/.../node_modules/typescript/lib/tsc.js:71261:23)
    at checkExpressionWorker (/.../node_modules/typescript/lib/tsc.js:74419:16)
    at checkExpression (/.../node_modules/typescript/lib/tsc.js:74330:32)
    at checkExpressionStatement (/.../node_modules/typescript/lib/tsc.js:76902:5)
    at checkSourceElementWorker (/.../node_modules/typescript/lib/tsc.js:79841:16)
    at checkSourceElement (/.../node_modules/typescript/lib/tsc.js:79701:7)

```

**Comment by linjer** [comment]
@millsp No idea what line and why this occurs. The above error is all I am getting and I was honestly hoping your expertise would provide some clues. Since it seems the only change was related to `jest-mock-extended` and the original test issue is no longer present, we can leave this issue as closed.

**Comment by millsp** [comment]
@linjer, while I do have experience, the error above looks like something went wrong when TS tried to bubble up an error, that's all I can say. It may be that you have a type error still and we cannot know about what it is, as it it obstructed by this - seemingly - bug in the compiler. That may be something you would like to raise in the TS repo. If you figure this out, please let me know.

**Comment by linjer** [comment]
@millsp When upgrading `jest-mock-extended` by itself, there is no issue. The issue only arises when upgrading both `jest-mock-extended@3.0.5` and `prisma@5.1.x` and the issue occurs both for Prisma versions `5.1.0` and `5.1.1`.

Given that seems to be a different issue with sparse information, I will open a new issue if I find anything. Thanks for addressing the original issue.
