### ISSUE TITLE
Cannot find module '/opt/nodejs/node_modules/@prisma/client/runtime/client'

### ISSUE THREAD

**Issue by rmoss-nutrien** [prisma/prisma#28471]
### Bug description

We have a monorepo that we are converting to use the new Rust-free version (v6.18.0) because of the promised bundle size reduction as we have hit lambda+layer sizing issues in the past with prisma.

We created a package that holds the new generated client and models, and are using that as dependency in other packages and lambdas. Previously, we had the @prisma/client in our lambda layer

We are getting this error below. The generated client needs the runtime, but its treated as an external dependency and not bundled with our code.
Cannot find module '/opt/nodejs/node_modules/@prisma/client/runtime/client'

### Severity

🔹 Minor: Unexpected behavior, but does not block development

### Expected vs. Actual Behavior

Expect that the generated client is able to work out of the box

### Frequency

Consistently reproducible

### Does this occur in development or production?

Only in production (e.g., query engine, generated client)

### Is this a regression?

Worked in rust version of prisma (v6.0.1) and is broken with rust-free version (v6.18.0)

### Workaround

Our solution was to bundle the @prisma/client/runtime with our code, but that seems like a workaround rather than a proper solution

### Prisma Schema & Queries

```prisma
// Add relevant schema.prisma snippet
generator client {
  provider     = "prisma-client"
  output       = "./generated"
  engineType   = "client"
  moduleFormat = "cjs"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

...models...
```
```ts
// Add relevant Prisma Client query
```

### Prisma Config

```ts
// Add your `prisma.config.ts`
```

### Logs & Debug Info

```
// Debug logs here
```

### Environment & Setup

- **OS:**  macOS and AWS
- **Database:**  PostgreSQL
- **Node.js version:**  v20.19.4 local, >20 on AWS

### Prisma Version

```
// Prisma version output
prisma                  : 6.18.0
@prisma/client          : 6.18.0
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v20.19.4
TypeScript              : 5.9.3
Query Engine (Node-API) : libquery-engine 34b5a692b7bd79939a9a2c3ef97d816e749cda2f (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
PSL                     : @prisma/prisma-schema-wasm 6.18.0-8.34b5a692b7bd79939a9a2c3ef97d816e749cda2f
Schema Engine           : schema-engine-cli 34b5a692b7bd79939a9a2c3ef97d816e749cda2f (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Default Engines Hash    : 34b5a692b7bd79939a9a2c3ef97d816e749cda2f
Studio                  : 0.511.0
```

**Comment by ish1416** [comment]
@rmoss-nutrien I understand the bug and ill try to fix it and create a PR!

**Comment by ish1416** [comment]
@rmoss-nutrien Can you review my PR?

**Comment by jacek-prisma** [comment]
Hi @rmoss-nutrien 
Can you provide a more complete reproduction, ideally something we could test/deploy ourselves?

**Comment by rmoss-nutrien** [comment]
The PR code itself looks fine to me, and I'm hoping that will fix our issue. The question would be is there a better way to generate the runtime or is this the only way because of our lambda/monorepo setup?

Our setup, in short, is a lambda (in a monorepo) that imports a local package where our Prisma client and models are generated per the new Rust-free version. You would need to create and deploy the lambda to get the error.

 We use Apollo graphql to query our lambdas (not sure if that's needed though)

**Comment by jacek-prisma** [comment]
Hi @rmoss-nutrien, a small minimized example would help us reproduce the problem.

**Comment by ish1416** [comment]
> The PR code itself looks fine to me, and I'm hoping that will fix our issue. The question would be is there a better way to generate the runtime or is this the only way because of our lambda/monorepo setup?
> 
> Our setup, in short, is a lambda (in a monorepo) that imports a local package where our Prisma client and models are generated per the new Rust-free version. You would need to create and deploy the lambda to get the error.
> 
> We use Apollo graphql to query our lambdas (not sure if that's needed though)

@rmoss-nutrien Yes, this is the only viable solution for Lambda/monorepo setups.

The issue occurs because Lambda deployment separates your generated client from the @prisma/client runtime package. The hardcoded relative import ./runtime/client.js assumes they're co-located, which breaks in Lambda environments.
Why alternatives won't work:
Build-time bundling doesn't resolve cross-package relative imports in monorepos
Lambda's deployment structure places packages in different locations
No runtime workaround exists for incorrect import paths
Why this solution is optimal:
Backward compatible (opt-in only)
Minimal change (single config flag)
Directly addresses the deployment architecture mismatch
Without this fix, Lambda + monorepo users have no workaround - they simply cannot deploy Prisma clients. This solution unblocks a growing segment of serverless users with zero risk to existing functionality.

**Comment by rmoss-nutrien** [comment]
That's a good enough explanation for me! This PR is good to go by me.

If we have any more issues, I will create the minimized example to have it ready going forward

**Comment by rmoss-nutrien** [comment]
Is there an update on this? The PR looks good to go on our part

This is blocking the upgrade to the rust-free version along with this issue #28421 (currently as we may uncover more as we go)

**Comment by ish1416** [comment]
> Is there an update on this? The PR looks good to go on our part
> 
> This is blocking the upgrade to the rust-free version along with this issue [#28421](https://github.com/prisma/prisma/issues/28421) (currently as we may uncover more as we go)

Can we merge it ? Can you tell me the exact issue what we are facing?

**Comment by daifuyang** [comment]
same as me

**Comment by daifuyang** [comment]
I've identified an issue in `d/generated/prisma/internal/class.ts` where ES module imports (`import`) are being used in a way that's incompatible with serverless function compute environments (like AWS Lambda, Alibaba Cloud Function Compute, etc.).

**Problem Details:**

The current implementation uses dynamic `import()` statements within functions:
```typescript
async function decodeBase64AsWasm(wasmBase64: string): Promise<WebAssembly.Module> {
  const { Buffer } = await import('node:buffer')  // ❌ Problematic for function compute
  const wasmArray = Buffer.from(wasmBase64, 'base64')
  return new WebAssembly.Module(wasmArray)
}
```

This causes issues because:
1. Function compute environments often have limitations with dynamic imports
2. Layers/function packages may not support ES module loading at runtime
3. CommonJS (`require`) is generally more reliable in these environments

**Required Fixes:**

1. **Update `package.json`:**
```json
{
  "type": "commonjs"
}
```

2. **Update `tsconfig.json`:**
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "moduleResolution": "node"
  }
}
```

**Suggested Code Changes:**

Convert the dynamic imports to CommonJS `require()` syntax:

```typescript
async function decodeBase64AsWasm(wasmBase64: string): Promise<WebAssembly.Module> {
  const { Buffer } = require('node:buffer')  // ✅ Use require instead
  const wasmArray = Buffer.from(wasmBase64, 'base64')
  return new WebAssembly.Module(wasmArray)
}

// For the config object
config.compilerWasm = {
  getRuntime: () => require("@prisma/client/runtime/query_compiler_bg.mysql.js"),
  
  getQueryCompilerWasmModule: async () => {
    const { wasm } = require("@prisma/client/runtime/query_compiler_bg.mysql.wasm-base64.js")
    return decodeBase64AsWasm(wasm)
  }
}
```
