### ISSUE TITLE
Instrumentation error in production: `TypeError: parentTracer.getSpanLimits is not a function`

### ISSUE THREAD

**Issue by SheaBelsky** [prisma/prisma#14887]
### Bug description

I am attempting to connect to `honeycomb.io` with the new Prisma Telemetry options. In a dev environment this works just fine. But in production, I receive the following error:

```
TypeError: parentTracer.getSpanLimits is not a function
  at new Span (/build/node_modules/@prisma/client/runtime/index.js:21694:37)
  at /build/node_modules/@prisma/client/runtime/index.js:23527:18
  at Array.forEach (<anonymous>)
  at createSpan (/build/node_modules/@prisma/client/runtime/index.js:23511:25)
  at runMicrotasks (<anonymous>)
  at runNextTicks (node:internal/process/task_queues:61:5)
  at listOnTimeout (node:internal/timers:528:9)
  at processTimers (node:internal/timers:502:7)
```

### How to reproduce

My code (after following these instructions: https://www.prisma.io/docs/concepts/components/prisma-client/opentelemetry-tracing#register-tracing-in-your-application)

```js
import { NodeTracerProvider } from "@opentelemetry/sdk-trace-node";
import { OTLPTraceExporter } from "@opentelemetry/exporter-trace-otlp-proto";
import { PrismaInstrumentation } from "@prisma/instrumentation";
import { registerInstrumentations } from "@opentelemetry/instrumentation";
import { Resource } from "@opentelemetry/resources";
import { SemanticResourceAttributes } from "@opentelemetry/semantic-conventions";
import { SimpleSpanProcessor } from "@opentelemetry/sdk-trace-base";

function setupTelemetry() {
  if (process.env.NODE_ENV !== "production") {
    return;
  }
  const provider = new NodeTracerProvider({
    resource: new Resource({
      [SemanticResourceAttributes.SERVICE_NAME]: "SERVICE_NAME"
    })
  });

  // Setup how spans are processed and exported. In this case we're sending spans
  // as we receive them to an OTLP-compatible collector (e.g. Jaeger).
  provider.addSpanProcessor(new SimpleSpanProcessor(new OTLPTraceExporter()));

  // Register your auto-instrumentors
  registerInstrumentations({
    instrumentations: [new PrismaInstrumentation()],
    tracerProvider: provider
  });

  provider.register();
  // eslint-disable-next-line no-console
  console.log("📈 Telemetry set up");
}

export default setupTelemetry;
```

I then import `setupTelemetry` at the entrypoint for my application and execute it:

```js
import setupTelemetry from './server/telemetry.ts';
// ....
setupTelemetry();
```

### Expected behavior

In a production environment, I should not receive an error AND I should receive telemetry data to Honeycomb. Right now, I get the aforementioned error and receive no telemetry data.

In a development (local) environment, everything behaves as expected.

### Prisma information

Packages:
```
    "@prisma/client": "4.2.1",
    "@prisma/instrumentation": "4.2.1",
    "prisma": "4.2.1",
```

### Environment & setup

- OS: macOS (local) and Linux (Azure App Services)
- Database: Azure PostgreSQL DB
- Node.js version: v16.14.2 (locally and in Azure)

### Prisma Version

```
prisma                  : 4.2.1
@prisma/client          : 4.2.1
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Default Engines Hash    : 2920a97877e12e055c1333079b8d19cee7f33826
Studio                  : 0.469.0
```

**Comment by garrensmith** [comment]
@SheaBelsky When you say it works in the dev environment, is the dev environment still using honeycomb?

**Comment by danstarns** [comment]
I cannot confirm this bug using honeycomb.io, using your reproduction I get traces in there. 

Are you setting all the required environment variables to connect to Honeycomb?

```
export OTEL_EXPORTER_OTLP_ENDPOINT="https://api.honeycomb.io"
export OTEL_EXPORTER_OTLP_HEADERS="x-honeycomb-team=YOUR_KEY_HERE"
export OTEL_SERVICE_NAME="your-service-name"
```

Please could you share the open telemetry versions or your package.json?

**Comment by garrensmith** [comment]
Could you also tell us what is different between your dev environment and production environment?

**Comment by SheaBelsky** [comment]
Package information:

```
    "@opentelemetry/exporter-trace-otlp-http": "0.31.0",
    "@opentelemetry/exporter-trace-otlp-proto": "0.31.0",
    "@opentelemetry/instrumentation": "0.31.0",
    "@opentelemetry/resources": "1.5.0",
    "@opentelemetry/sdk-trace-base": "1.5.0",
    "@opentelemetry/sdk-trace-node": "1.5.0",
    "@opentelemetry/semantic-conventions": "1.5.0",
```

My production environment runs on Azure App Service, and my dev environment runs on my computer. When I use the exact same environment variables (and the only difference being that the code runs locally vs on Azure App Service), I get the original error on Azure App Service.

@danstarns are you able to get logs in a cloud environment using my code? or are you running it locally?

**Comment by SheaBelsky** [comment]
Sorry for not including earlier - the only other difference would be that in Azure App Services, I'm running in a Docker environment, and not doing that in a local environment. My dockerfile is pretty minimal though:

```
FROM node:16-alpine AS builder
WORKDIR /build

COPY . .

RUN npm ci
RUN npm run compile

CMD ["npm", "start"]
```

and here's my entire `package.json` just for completeness:

```
{
  "name": "backend",
  "version": "1.0.0",
  "main": "dist/index.js",
  "license": "UNLICENSED",
  "engines": {
    "node": ">=16.14.2"
  },
  "dependencies": {
    "@azure/core-auth": "1.3.2",
    "@azure/storage-blob": "12.9.0",
    "@hubspot/api-client": "7.1.2",
    "@opentelemetry/exporter-trace-otlp-proto": "0.31.0",
    "@opentelemetry/instrumentation": "0.31.0",
    "@opentelemetry/resources": "1.5.0",
    "@opentelemetry/sdk-trace-base": "1.5.0",
    "@opentelemetry/sdk-trace-node": "1.5.0",
    "@opentelemetry/semantic-conventions": "1.5.0",
    "@prisma/client": "4.2.1",
    "@prisma/instrumentation": "4.2.1",
    "@sentry/node": "7.11.1",
    "@sentry/tracing": "7.11.1",
    "agenda": "4.3.0",
    "apollo-server-core": "3.5.0",
    "apollo-server-express": "3.5.0",
    "apollo-server-plugin-base": "3.5.1",
    "applicationinsights": "2.2.0",
    "bcryptjs": "2.4.3",
    "cookie": "0.4.2",
    "cross-fetch": "3.1.5",
    "express": "4.17.3",
    "google-auth-library": "7.11.0",
    "graphql": "15.5.0",
    "graphql-fields": "2.0.3",
    "graphql-rate-limit": "2.3.1",
    "graphql-scalars": "1.17.0",
    "graphql-type-json": "0.3.2",
    "jsonwebtoken": "8.5.1",
    "password-validator": "5.1.1",
    "prisma": "4.2.1",
    "reflect-metadata": "0.1.13",
    "type-graphql": "1.1.1",
    "typegraphql-prisma": "0.21.3",
    "typescript": "4.6.2",
    "uuid": "8.3.2"
  },
  "devDependencies": {
    "@types/bcrypt": "5.0.0",
    "@types/bcryptjs": "2.4.2",
    "@types/cookie": "0.4.1",
    "@types/express": "4.17.13",
    "@types/graphql-fields": "1.3.4",
    "@types/jest": "27.4.1",
    "@types/jsonwebtoken": "8.5.8",
    "@types/node": "15.12.2",
    "@types/uuid": "8.3.4",
    "@types/validator": "13.7.1",
    "@typescript-eslint/eslint-plugin": "5.15.0",
    "@typescript-eslint/parser": "5.15.0",
    "azure-maps-rest": "2.0.8",
    "class-validator": "0.13.2",
    "csv-parser": "3.0.0",
    "env-cmd": "10.1.0",
    "eslint": "8.11.0",
    "eslint-config-prettier": "8.5.0",
    "eslint-plugin-prettier": "4.0.0",
    "jest": "27.0.4",
    "jest-mock-extended": "2.0.4",
    "nodemon": "2.0.19",
    "prettier": "2.6.0",
    "ts-jest": "27.0.3",
    "ts-node": "10.7.0"
  },
  "prisma": {
    "seed": "ts-node ./src/seed.ts"
  },
  "repository": {
    "url": "https://github.com/AxisAbility/leto"
  },
  "scripts": {
    "compile": "npx prisma generate && tsc",
    "dev": "env-cmd -f .env.dev --use-shell \"nodemon --config nodemon.json\"",
    "format": "eslint --config .eslintrc --fix --quiet ./src",
    "introspect": "env-cmd -f .env.dev --use-shell \"prisma introspect\"",
    "local:prod": "env-cmd -f .env.prod.local --use-shell \"nodemon --config nodemon.json\"",
    "local:staging": "env-cmd -f .env.staging.local --use-shell \"nodemon --config nodemon.json\"",
    "lint": "eslint --config .eslintrc --quiet --fix ./src",
    "migrate": "env-cmd -f .env.dev --use-shell \"prisma migrate dev\"",
    "migrate:prod": "env-cmd -f .env.prod --use-shell \"prisma migrate deploy\"",
    "migrate:staging": "env-cmd -f .env.staging --use-shell \"prisma migrate deploy\"",
    "postinstall": "npm run compile",
    "seed": "env-cmd -f .env.dev --use-shell \"npx prisma db seed\"",
    "start": "node dist/index.js",
    "studio": "env-cmd -f .env.dev --use-shell \"npx prisma studio\"",
    "test": "jest --env=node --colors --coverage test",
  }
}
```

**Comment by janpio** [comment]
Can you maybe create a minimal Node project with Prisma and the tracing setup you are using, and see if that also causes the problem you are describing? That would make it a lot easier for us to maybe also try to deploy such a project to Azure App Services and see if that triggers the problem for us as well. Thanks @SheaBelsky.

**Comment by SheaBelsky** [comment]
Will work on this today!

**Comment by SheaBelsky** [comment]
Here's a minimal representation of this error where I can reproduce the error:

https://github.com/SheaBelsky/prisma-instrumentation-test

Using the following Azure Services:
* https://azure.microsoft.com/en-us/services/app-service/
* https://docs.microsoft.com/en-us/azure/postgresql/flexible-server/

In this minimal environment locally, I can get Honeycomb data to work. But in production (Docker), I cannot and I get the following error:

```
2022-08-22T15:56:13.052368931Z /build/node_modules/@prisma/client/runtime/index.js:21694
2022-08-22T15:56:13.052433833Z     this._spanLimits = parentTracer.getSpanLimits();
2022-08-22T15:56:13.052441634Z                                     ^
2022-08-22T15:56:13.052446134Z
2022-08-22T15:56:13.052450234Z TypeError: parentTracer.getSpanLimits is not a function
2022-08-22T15:56:13.052454434Z     at new Span (/build/node_modules/@prisma/client/runtime/index.js:21694:37)
2022-08-22T15:56:13.052458634Z     at /build/node_modules/@prisma/client/runtime/index.js:23527:18
2022-08-22T15:56:13.052462834Z     at Array.forEach (<anonymous>)
2022-08-22T15:56:13.052468335Z     at createSpan (/build/node_modules/@prisma/client/runtime/index.js:23511:25)
```

**Comment by garrensmith** [comment]
@SheaBelsky one more thing. If you run the docker instance locally, do you still get the error or is it only docker running on Azure?

**Comment by SheaBelsky** [comment]
@garrensmith This does not appear to happen on a local Docker image. This is what I did to create a local Docker image:

```
docker build . --tag instrumentation            
docker run -p 8080:8090 instrumentation
```

You will need to provide the appropriate environment variables to the container when it is built (either with the `.env.dev` file & `env-cmd` package or by binding the arguments at the time the image is built), but I got Honeycomb data from within the container when I built the image locally.

**Comment by garrensmith** [comment]
@SheaBelsky thank you for the detailed help. We will look into it and see what the fix is.

**Comment by SheaBelsky** [comment]
@garrensmith of course! let me know if you need any more information or debugging info from my side!

**Comment by obviousplant** [comment]
i am also getting this same error on our production app. does not happen locally

**Comment by danstarns** [comment]
@SheaBelsky Thank you for the replication. I took your docker file and then run the application, sent an HTTP request to `/users` - No traces in honeycomb plus I don't get any error. 

What I did find is that if I use the console exporter from open opentelemetry I do indeed see the Prisma traces. Here is what I changed to see the traces in the console: 

```diff
import { NodeTracerProvider } from "@opentelemetry/sdk-trace-node";
- import { OTLPTraceExporter } from "@opentelemetry/exporter-trace-otlp-proto";
import { PrismaInstrumentation } from "@prisma/instrumentation";
import { registerInstrumentations } from "@opentelemetry/instrumentation";
import { Resource } from "@opentelemetry/resources";
import { SemanticResourceAttributes } from "@opentelemetry/semantic-conventions";
- import { SimpleSpanProcessor } from "@opentelemetry/sdk-trace-base";
+ import { SimpleSpanProcessor, ConsoleSpanExporter } from "@opentelemetry/sdk-trace-base";

function setupTelemetry() {
  if (process.env.NODE_ENV !== "production") {
    return;
  }
  const provider = new NodeTracerProvider({
    resource: new Resource({
      [SemanticResourceAttributes.SERVICE_NAME]: "SERVICE_NAME"
    })
  });

  // Setup how spans are processed and exported. In this case we're sending spans
  // as we receive them to an OTLP-compatible collector (e.g. Jaeger).
- provider.addSpanProcessor(new SimpleSpanProcessor(new OTLPTraceExporter()));
+ provider.addSpanProcessor(new SimpleSpanProcessor(new ConsoleSpanExporter()()));

  // Register your auto-instrumentors
  registerInstrumentations({
    instrumentations: [new PrismaInstrumentation()],
    tracerProvider: provider
  });

  provider.register();
  // eslint-disable-next-line no-console
  console.log("📈 Telemetry set up");
}

export default setupTelemetry;
```

Can you confirm that if you enable console logging, you see the Prisma traces in the console and you don't get the described error?

**Comment by SheaBelsky** [comment]
@danstarns Did you run the application locally or in an Azure App Service environment?

When I use the Console Span Exporter locally, I get Prisma traces in my console. That's fine!

But I was originally able to receive Honeycomb spans with the local docker image by using the code I provided earlier (using `OTLPTraceExporter`). Locally, when I use `ConsoleSpanExporter`, I do not receive any data in Honeycomb. I can't really do anything else without the data being exported - Is `ConsoleSpanExporter` meant to export data to a collector? I don't think it is to the best of my knowledge

**Comment by danstarns** [comment]
@SheaBelsky I did not use Azure App Service environment, I used the Docker image you provided. 

ConsoleSpanExporter **is not ment** to export data to a collector, I am trying to establish where the issue is - If you see Prisma logs in the console using `ConsoleSpanExporter` then we know that the issue is at the exporting stage with `OTLPTraceExporter`.

**Comment by SheaBelsky** [comment]
Still getting the same error in Azure when using `ConsoleSpanExporter`, and I don't see any emitted traces in the console @danstarns 

```
2022-09-01T13:51:45.139071054Z TypeError: parentTracer.getSpanLimits is not a function
2022-09-01T13:51:45.139088555Z     at new Span (/build/node_modules/@prisma/client/runtime/index.js:21694:37)
2022-09-01T13:51:45.139100956Z     at /build/node_modules/@prisma/client/runtime/index.js:23527:18
2022-09-01T13:51:45.139105557Z     at Array.forEach (<anonymous>)
2022-09-01T13:51:45.139110157Z     at createSpan (/build/node_modules/@prisma/client/runtime/index.js:23511:25)
2022-09-01T13:51:45.139114257Z     at runNextTicks (node:internal/process/task_queues:61:5)
2022-09-01T13:51:45.139131858Z     at listOnTimeout (node:internal/timers:528:9)
2022-09-01T13:51:45.139136359Z     at processTimers (node:internal/timers:502:7)
2022-09-01T13:51:45.291346076Z This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
```

**Comment by danstarns** [comment]
> Still getting the same error in Azure when using `ConsoleSpanExporter`, and I don't see any emitted traces in the console @danstarns
> 
> ```
> 2022-09-01T13:51:45.139071054Z TypeError: parentTracer.getSpanLimits is not a function
> 2022-09-01T13:51:45.139088555Z     at new Span (/build/node_modules/@prisma/client/runtime/index.js:21694:37)
> 2022-09-01T13:51:45.139100956Z     at /build/node_modules/@prisma/client/runtime/index.js:23527:18
> 2022-09-01T13:51:45.139105557Z     at Array.forEach (<anonymous>)
> 2022-09-01T13:51:45.139110157Z     at createSpan (/build/node_modules/@prisma/client/runtime/index.js:23511:25)
> 2022-09-01T13:51:45.139114257Z     at runNextTicks (node:internal/process/task_queues:61:5)
> 2022-09-01T13:51:45.139131858Z     at listOnTimeout (node:internal/timers:528:9)
> 2022-09-01T13:51:45.139136359Z     at processTimers (node:internal/timers:502:7)
> 2022-09-01T13:51:45.291346076Z This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
> ```

Thank you for trying this, we are looking into it.

**Comment by obviousplant** [comment]
hey can we get some sort of update on this? You literally cannot deploy to any azure linux machines.

**Comment by trevorr** [comment]
I don't know if it's relevant, but I starting hitting this error locally when I upgraded Prisma 4.7.1 to 4.14.0. I then upgraded all the opentelemetry libraries and it went away.

```
@opentelemetry/api                          ^1.3.0  →   ^1.4.1
@opentelemetry/context-async-hooks          ^1.8.0  →  ^1.12.0
@opentelemetry/exporter-trace-otlp-http    ^0.34.0  →  ^0.38.0
@opentelemetry/resources                    ^1.8.0  →  ^1.12.0
@opentelemetry/sdk-trace-base               ^1.8.0  →  ^1.12.0
@opentelemetry/sdk-trace-node               ^1.8.0  →  ^1.12.0
@opentelemetry/semantic-conventions         ^1.8.0  →  ^1.12.0
```

**Comment by Fenntasy** [comment]
This problem appeared on my repo because of End to End testing with Playwright on a Github Action. I can't reproduce it locally but with the last `Bump @prisma/instrumentation from 4.13.0 to 4.14.1` it exploded. OpenTelemetry is up to date but we can't do the upgrade of @prisma/instrumentation because of that error.

**Comment by thyming** [comment]
I'm also experiencing this deploying to ECS after upgrading @prisma/* from 5.2.0 to 5.4.1.

**Comment by ati-pave** [comment]
Experienced the same error on Prisma >5.4.2 (tried 5.4.2, as well as 5.5). Downgrading to 5.2.0 worked for me

**Comment by edobrb** [comment]
Version 5.5.2 solved for me

**Comment by jvaczcorporation** [comment]
Not work:

```
  const provider = new NodeTracerProvider()
  const exporter = new TraceExporter()

  provider.addSpanProcessor(new SimpleSpanProcessor(exporter))

  registerInstrumentations({
    tracerProvider: provider,
    instrumentations: [
      new PrismaInstrumentation(),
      new HttpInstrumentation(),
      new FastifyInstrumentation(),
    ],
  })

Work fine:

```
  const provider = new NodeTracerProvider()
  const exporter = new TraceExporter()

  provider.addSpanProcessor(new SimpleSpanProcessor(exporter))
  provider.register()

  registerInstrumentations({
    instrumentations: [
      new PrismaInstrumentation(),
      new HttpInstrumentation(),
      new FastifyInstrumentation(),
    ],
  })
```

**Comment by ZenSoftware** [comment]
> Not work:
> 
> ```
>   const provider = new NodeTracerProvider()
>   const exporter = new TraceExporter()
> 
>   provider.addSpanProcessor(new SimpleSpanProcessor(exporter))
> 
>   registerInstrumentations({
>     tracerProvider: provider,
>     instrumentations: [
>       new PrismaInstrumentation(),
>       new HttpInstrumentation(),
>       new FastifyInstrumentation(),
>     ],
>   })
> ```
> 
> Work fine:
> 
> ```
>   const provider = new NodeTracerProvider()
>   const exporter = new TraceExporter()
> 
>   provider.addSpanProcessor(new SimpleSpanProcessor(exporter))
>   provider.register()
> 
>   registerInstrumentations({
>     instrumentations: [
>       new PrismaInstrumentation(),
>       new HttpInstrumentation(),
>       new FastifyInstrumentation(),
>     ],
>   })
> ```
@jvaczcorporation
This comment is important.  It is the only thing that has worked for me to fix this issue.  I believe I've had this issue for just about a year now.  Thank you!!!  Finally, I can deploy my NestJS API with OTEL instrumentation integrated.  🧪💙🎐

I do believe this information would be useful to the OTEL team managing the respective packages affected.  I don't believe this issue is just specific to Prisma.  It would be nice to link this issue to somewhere the OTEL community could see it.  Anyone know which repo to search for?

**Comment by pleymor** [comment]
I still get the issue even after having installed `@opentelemetry/api`:

```json
"dependencies": {
    "other": "...",
    "@opentelemetry/api": "^1.8.0",
    "@opentelemetry/exporter-trace-otlp-http": "^0.49.1",
    "@opentelemetry/instrumentation": "^0.49.1",
    "@opentelemetry/resources": "^1.22.0",
    "@opentelemetry/sdk-trace-base": "^1.22.0",
    "@opentelemetry/sdk-trace-node": "^1.22.0",
    "@opentelemetry/semantic-conventions": "^1.22.0",
    "@prisma/client": "^5.10.2",
    "@prisma/instrumentation": "^5.10.2"
},
"devDependencies": {
    "other": "...",
    "prisma": "^5.10.2"
}
```

> TypeError: parentTracer.getSpanLimits is not a function
    at new Span (/Users/me/myproject/node_modules/@prisma/instrumentation/node_modules/@opentelemetry/sdk-trace-base/src/Span.ts:122:37)

Simplest way to reproduce:

```ts
import { PrismaInstrumentation } from '@prisma/instrumentation';

// =====> TypeError: parentTracer.getSpanLimits is not a function
const prismaInstrumentation = new PrismaInstrumentation();
```

**Comment by SevInf** [comment]
I've reproduced the issue using the code from @jvaczcorporation.
[Internal link](https://github.com/prisma/reproductions/tree/main/gh-14887). 

The culprit seems to be missing `provider.register()` call. If that's not the case for you, could any of you share a reproduction repo where we could see this happen locally.

**Comment by SevInf** [comment]
On a second thought and a little bit more digging in, it think it is Prisma issue after all. 
We should not try to create the spans if there is no active tracer present.

**Comment by millsp** [comment]
Maybe related: https://github.com/prisma/prisma/issues/24373

**Comment by aloisklink** [comment]
https://github.com/prisma/prisma/issues/24373 would have fixed this for me.

The problem was that I had two different `@opentelemetry/api` libraries in my `node_modules`.

Playing around with my dependencies until there was only one version of `@opentelemetry/api` in my `pnpm-lock.yaml` file fixed the `TypeError: parentTracer.getSpanLimits is not a function` error for me.

**Comment by samirotiv** [comment]
We are facing the same when we try to integrate Prisma OpenTelemetry with Elastic APM. Prisma installs its own version of `@opentelemetry/instrumentation`, although there is only one version of `@opentelemetry/api`. I think making it a peer dependency might solve this issue.

**Comment by bplies-ATX** [comment]
Possible cause mentioned in #24715
