### ISSUE TITLE
TypeError: this.getGlobalTracingHelper(...).dispatchEngineSpans is not a function

### ISSUE THREAD

**Issue by mdesousa** [prisma/prisma#25978]
### Bug description

We started seeing this error after upgrading to 6.1.0

### How to reproduce

We use a 3rd party monitoring platform (highlight.io). Their sdk leverages opentelemetry and it appears that this is crashing prisma with this error: TypeError: this.getGlobalTracingHelper(...).dispatchEngineSpans is not a function.

### Expected behavior

The application should not crash.

### Prisma information

N/A

### Environment & setup

- OS: macOS, Debian
- Database: PostgreSQL
- Node.js version: 22

### Prisma Version

```
prisma                  : 6.1.0
@prisma/client          : 6.1.0
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v22.12.0
Query Engine (Node-API) : libquery-engine 11f085a2012c0f4778414c8db2651556ee0ef959 (at ../node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 11f085a2012c0f4778414c8db2651556ee0ef959 (at ../node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 6.1.0-21.11f085a2012c0f4778414c8db2651556ee0ef959
Default Engines Hash    : 11f085a2012c0f4778414c8db2651556ee0ef959
Studio                  : 0.503.0
Preview Features        : relationJoins
```

**Comment by mdesousa** [comment]
Hi, in case it helps i've created a small repo to reproduce the issue: [prisma-highlight-bug](https://github.com/mdesousa/prisma-highlight-bug)

**Comment by Dentling** [comment]
Experiencing the same issue on 6.2.0.

So Issue sadly still persists in 6.2.0.

**Comment by andyjy** [comment]
I hit this error upgrading to Prisma `v6.2.0`, realised I still had outdated (v5) version of `@prisma/instrumentation`. Also upgraded peer dependency `@opentelemetry/instrumentation` from `v0.53.0` to `v0.56.0` - not checked which caused it but between these two updates the error was resolved.

**Comment by andyjy** [comment]
yes I ensured consistent version numbers across all @opentelemetry/* packages - same `v0.xx`, same `v1.xx` as appropriate for the packages currently using stable vs. "experimental"/unstable (pre v1) versioning

**Comment by aqrln** [comment]
You will get this error if the versions of `@prisma/client` and `@prisma/instrumentation` mismatch and are incompatible. `highlight.io` SDK hardcodes the dependency on the previous major version, `@prisma/instrumentation@5.22`: https://github.com/highlight/highlight/blob/c24328c6f459c404970f623c48b38140852755d5/sdk/highlight-node/package.json#L30. While it still incidentally happens to work with 6.0.0, it's not compatible with the 6.1.0 release anymore.

You should report this issue to the third party package since the problem is on their side and there's nothing we can do about it, sorry.

**Comment by mdesousa** [comment]
thanks @aqrln ... sounds like highlight should make this a peer dependency. i've create an issue for them to look into it: https://github.com/highlight/highlight/issues/9753

**Comment by mdesousa** [comment]
hi @aqrln , while highlight fixes the dependencies we have tried overriding the depency of `@prisma/instrumentation` to match the same version as `@prisma/client` and we are finding that the app still crashes with the same error. can you please take a look at the latest commit in the [test repo](https://github.com/mdesousa/prisma-highlight-bug) to see what's the problem?

**Comment by aqrln** [comment]
I'll have a look — let's reopen this issue until then just in case.

**Comment by mdesousa** [comment]
@andyjy you are correct, and i've [raised an issue](https://github.com/highlight/highlight/issues/9753) about the bundling of @prisma/instrumentation. but note that the [test repo](https://github.com/mdesousa/prisma-highlight-bug) overrides this dependency... which shows that the app still crashes when the correct version of @prisma/instrumentation is used.

**Comment by andyjy** [comment]
the significance of highight-run/node bundling their own compiled version of @prisma/instrumentation is that the Highlight code uses the statically compiled version without ever attempting to import the version installed in `node_modules` 

(you can see this by inspecting node_modules/@highlight-run/node/dist/index.js - we can see there is no `import` or `require()` of `@prisma/instrumentation` - only the reference to the statically compiled version `5.22.0`)

so yes while the test repo now overrides the dep correctly, it's not used by the Highlight package. 

hope this helps!
