### ISSUE TITLE
`unref()` is not a function error when using `$transaction` with rust-free client on Cloudflare Workers

### ISSUE THREAD

**Issue by aiji42** [prisma/prisma#28089]
### Bug description

When using Prisma v6.16.1 with the rust-free client configuration (`engineType = "client"` and `runTime = "workerd"`) on Cloudflare Workers, executing queries with $transaction causes a TypeError because `unref()` is not available on the `setTimeout` return value in the Workers environment.

### Severity

⚠️ Major: Breaks core functionality (e.g., migrations fail)

### Reproduction

1. Update Prisma to v6.16.1
2. Configure schema.prisma with rust-free client for Cloudflare Workers:
```
  generator client {
    provider        = "prisma-client"
    engineType      = "client"
    runtime         = "workerd"
    previewFeatures = ["relationJoins"]
    output          = "./src/generated/prisma"
  }
```
3. Execute any query using $transaction
4. Error occurs: TypeError: i.unref is not a function

### Expected vs. Actual Behavior

`$transaction should` execute successfully without errors on Cloudflare Workers runtime.

### Frequency

Consistently reproducible

### Does this occur in development or production?

Both development and production

### Is this a regression?

Yes - This is a regression introduced in Prisma v6.16.0.

The issue was introduced by PR #28030 (fix(client-engine-runtime): unref transaction timers) which added `unref()` calls to transaction timers. This change works correctly in Node.js environments but breaks compatibility with edge runtimes like Cloudflare Workers.

Last known working version: Prisma versions prior to v6.16.0 should work without this issue, as they didn't include the `unref()` calls on transaction timers.

### Workaround

Manually remove the two `unref()` calls from `node_modules/@prisma/client/runtime/wasm-compiler-edge.mjs`. This fixes the issue but needs to be reapplied after each npm install.

### Prisma Schema & Queries

```prisma
generator client {
  provider        = "prisma-client"
  engineType      = "client"
  runtime         = "workerd"
  previewFeatures = ["relationJoins"]
  output          = "./src/generated/prisma"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```

### Prisma Config

```ts
// Add your `prisma.config.ts`
```

### Logs & Debug Info

```
  [dev:main  ] ✘ [ERROR] TypeError: i.unref is not a function
  [dev:main  ]
  [dev:main  ]       at #s (file:///Users/....../node_modules/@prisma/client-engine-runtime/src/transaction-manager/transaction-manager.ts:216:15)
  [dev:main  ]       at #r (file:///Users/....../node_modules/@prisma/client-engine-runtime/src/transaction-manager/transaction-manager.ts:122:21)
  [dev:main  ]       at async Sr.startTransaction (file:///Users/....../node_modules/@prisma/client-engine-runtime/src/transaction-manager/transaction-manager.ts:85:12)
  [dev:main  ]       at async e7.startTransaction (file:///Users/....../node_modules/@prisma/client/src/runtime/core/engines/client/LocalExecutor.ts:79:5)
  [dev:main  ]       at async kr.transaction (file:///Users/....../node_modules/@prisma/client/src/runtime/core/engines/client/ClientEngine.ts:423:18)
  [dev:main  ]       at async Proxy._transactionWithCallback (file:///Users/....../node_modules/@prisma/client/src/runtime/getPrismaClient.ts:715:20)
```

### Environment & Setup

- **OS:** macOS
- **Database:** Postgres
- **Node.js version:** v22.18.0

### Prisma Version

prisma: 6.16.1
@prisma/client: 6.16.1

**Comment by medz** [comment]
Same problem, 6.16.1 upgrade has been urgently revoked and downgraded to 6.15.0

**Comment by aroman** [comment]
yes is also impacting us. so much for the rust-free client being production ready :(

**Comment by jacek-prisma** [comment]
Fixed in https://github.com/prisma/prisma/pull/28091 and will be included in 6.16.2 release today
