### ISSUE TITLE
AWS Amplify + Next.js + next-auth + Prisma (API route) doesn't work

### ISSUE THREAD

**Issue by bojidaryovchev** [prisma/prisma#10200]
### Bug description

following the reproduction steps, you will end up with the following error, and first I want to say that the problem *does not* come from ```next-auth``` since I initially thought of that but after removing the Prisma adapter it worked fine

![CloudWatch error](https://user-images.githubusercontent.com/8954749/140654898-1f991fa4-3394-4b04-99e8-c70417bc1f04.png)

after checking the deployed lambda for the given API route's code

![Lambda code](https://user-images.githubusercontent.com/8954749/140654943-acfb1b65-10cc-4295-9a7b-14955e4c29ac.png)

we can see that the Prisma's ```LibraryEngine``` is trying to look for the ```schema.prisma``` file in the directory where the given chunk exists, however since it is an API route that gets deployed to a Lambda function the ```schema.prisma``` file does not exist there

having checked the generated chunk that the error comes from ```431.js``` I found the following code

```
// folder where the generated client is found
const dirname = findSync(process.cwd(), [
  "node_modules/.prisma/client",
  ".prisma/client",
], ['d'], ['d'], 1)[0] || __dirname
```

given that the file does not even exist in the deployed Lambda function it is no wonder that it can't be found, this might be a problem with AWS Amplify, I am not sure, but I have tried to copy the ```schema.prisma``` to the ```/var/task/chunks``` directory using the ```postBuild``` phase in the ```amplify.yml``` build configuration - however, I actually had to create the ```task``` and then ```chunks``` directories since they did not even exist which makes me think the build configuration is not directly applicable to the actual Lambda code that gets deployed, I used the following Linux shell commands for that

```
    postBuild:
      commands:
        - dir="$PWD"
        - cd /var
        - mkdir task
        - cd task
        - mkdir chunks
        - cd $dir
        - cp prisma/schema.prisma /var/task/chunks/schema.prisma
```

so now I have no idea how to make it so that my ```schema.prisma``` file would get copied in that chunks directory, or maybe follow some different approach, I don't know, I am just posting this issue hoping that someone out there might be able to add something to the matter, I am not sure if that's something that's wrong with Prisma, maybe it's simply AWS Amplify's fault, no idea, maybe I am missing something or maybe it is simply not possible at this given time

### How to reproduce

1. create a Next.js app using ```npx create-next-app@latest --ts```
2. follow [AWS Amplify Next.js tutorial](https://docs.amplify.aws/guides/hosting/nextjs/q/platform/js/) step by step
3. run ```prisma init``` to initialize Prisma
4. add ```next-auth``` following their tutorial at [NextAuth.js Prisma Adapter](https://next-auth.js.org/adapters/prisma) (in my case I added Google as a provider, everything works fine on my local

	  - having followed the AWS Amplify Next.js tutorial, you would have connected a branch for CI/CD out of the box, so whenever you push your code it's going to get built and redeployed - however, in order to get the environment variables being passed to the API routes follow the next steps:

5. go to your Amplify application / Environment Variables and define the variables for DATABASE_URL, NEXTAUTH_URL, GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET (in my case)
6. go to your Amplify application / Build settings and edit your ```amplify.yml``` file - in the build phase, for each environment variable you have defined, add ```- echo "VARIABLE=$VARIABLE" >> .env``` under the ```commands:``` statement and save the file

	  - having done that, now your environment variables would be available in your api routes (in order to verify you can do ```res.status(200).json({ name: 'John Doe', env: JSON.stringify(process.env) })```

so finally, in order to see the error, you need to visit the deployed version's url and then go to ```CloudWatch``` / ```Logs > Log groups``` and open one of the lambda functions' log groups' log stream and you will see ```"ENOENT: no such file or directory, open '/var/task/chunks/schema.prisma'"```

- PS: I forgot to mention that there was another error related to ```_http_common``` which in order to get rid of I had to modify my ```next.config.js``` and add the following webpack configuration in there (I do not quite remember where I saw that from, so I cannot reference it, but it fixes the issue)

```
  webpack: (config, { defaultLoaders, isServer }) => {
    if (isServer) {
      config.externals.push('_http_common');
    }

    return config;
  },
```

### Expected behavior

I would expect my ```schema.prisma``` to be found and things to work out fine

### Prisma information

```
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "rhel-openssl-1.0.x"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```

I am using version ```3.2.1``` because of [After upgrading from 3.2.1 to 3.3.0 I get a 'Error: Cannot find module 'os''](https://github.com/prisma/prisma/issues/10058)

using the ```next-auth``` Prisma adapter schema

```
model Account {
  id                 String  @id @default(cuid())
  userId             String
  type               String
  provider           String
  providerAccountId  String
  refresh_token      String?
  access_token       String?
  expires_at         Int?
  token_type         String?
  scope              String?
  id_token           String?
  session_state      String?
  oauth_token_secret String?
  oauth_token        String?

  user User @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@unique([provider, providerAccountId])
}

model Session {
  id           String   @id @default(cuid())
  sessionToken String   @unique
  userId       String
  expires      DateTime
  user         User     @relation(fields: [userId], references: [id], onDelete: Cascade)
}

model User {
  id            String    @id @default(cuid())
  name          String?
  email         String?   @unique
  emailVerified DateTime?
  image         String?
  accounts      Account[]
  sessions      Session[]
}

model VerificationToken {
  identifier String
  token      String   @unique
  expires    DateTime

  @@unique([identifier, token])
}
```

### Environment & setup

- OS: Windows
- Database: PostgreSQL
- Node.js version: 14.15.4

### Prisma Version

```
3.2.1
```

**Comment by willcrisis** [comment]
Came here to say I'm having this exact same issue. I'd say it's a f***ing big coincidence, since we have basically the same stack and the the steps to replicate are absolutely the same. Only difference is that I'm using `prisma@3.5.0` and `@prisma/client@3.5.0` , since it fixes the `Error: Cannot find module 'os'` problem.

I even tried to manually create a `schema.prisma` file in the mentioned location using AWS Lambda console, but no success either...

Don't know if it's worth mentioning, but I'm using NextJS 12.0.2 (Amplify says they support only version 11, but if you're not using v12-specific features (like `middleware`), it compiles without problem).

**Comment by bojidaryovchev** [comment]
> Came here to say I'm having this exact same issue. I'd say it's a f***ing big coincidence, since we have basically the same stack and the the steps to replicate are absolutely the same. Only difference is that I'm using `prisma@3.5.0` and `@prisma/client@3.5.0` , since it fixes the `Error: Cannot find module 'os'` problem.
> 
> I even tried to manually create a `schema.prisma` file in the mentioned location using AWS Lambda console, but no success either...
> 
> Don't know if it's worth mentioning, but I'm using NextJS 12.0.2 (Amplify says they support only version 11, but if you're not using v12-specific features (like `middleware`), it compiles without problem).

I have also tried to manually create the file without success, I also tried modifying existing lambda code manually (the hello api route response) to find out that nothing changes, I am guessing it does something under the hood when being handled by amplify, I don't know.. I've started thinking about abandoning Prisma and going for the following setup:

1. keep the same Amplify Next.js app
2. use NextAuth for authentication and combine it with DynamoDB since they have a DynamoDB adapter
3. use AppSync instead of Prisma which easily connects with DynamoDB
4. use AppSync Lambda Authorizer in order to authorize calls to the GraphQL api

I am going to try that today or tomorrow, depending on when I have the time, but it seems to be the way to go for now.. That way I will have the benefit of NextAuth's multiple auth providers (and not having to deal with Cognito User Pools and the lack of support for a giant like Twitter), AppSync works with DynamoDB by default I think and it's easy to have it set up (AppSync provides plenty of useful stuff regarding a mobile app connection, push notifications etc) and then will just protect the API with the lambda authorizer

**Comment by wdj82** [comment]
I had the same problem. Adding

```
  target: 'experimental-serverless-trace'
```

To my next.config file seems to have fixed it.

**Comment by bojidaryovchev** [comment]
@wdj82 omg man I love you haha it solved the problem, amazing, good job! @willcrisis

**Comment by jarnesjo** [comment]
What a pain relief 😅 Thanks!

Next problem was that I got error in the Lambda saying it couldn't find `DATABASE_URL`.  But I find a solutions a wanted to post it for reference if someone else have the same problem.

> yo guys, I think I found a solution. For me, the approach with `next.config.js` did not work, so after trying various things I saw [AWS User Guide # Access Environment Variables](https://docs.aws.amazon.com/amplify/latest/userguide/environment-variables.html#access-env-vars) and managed to get it working.
> 
> 1. I went to my Amplify app Build Settings
> 2. I edited the App build specification `amplify.yml` file
> 3. For every Environment Variable I had added in the Amplify app Environment Variables section, I added
>    `- echo "SOME_VARIABLE=$SOME_VARIABLE" >> .env`
> 4. That's it, after that I redeployed the build and I had all my variables present

https://github.com/aws-amplify/amplify-console/issues/1987#issuecomment-961510561

**Comment by bojidaryovchev** [comment]
https://github.com/bojidaryovchev/next-amplify

this is a repository I am building as a skeleton, feel free to check it out

**Comment by elleryfamilia** [comment]
I'm seeing these errors and the next.config.js fix isn't working. 

next 12.0.8
next-auth 4.1.2
prisma 3.8.1

**Comment by mergebandit** [comment]
Same thing here @elleryfamilia -

next 11.1.4
next-auth 4
prisma 3.9.2

Did you ever resolve?
