### ISSUE TITLE
Can't normaly import generated prisma client, while using multiple schemas in nx monorepository

### ISSUE THREAD

**Issue by Dmutre** [prisma/prisma#26688]
### Bug description

**Title:** Issue with Importing Custom Prisma Client in Latest Prisma 6.x  

**Description:**  
I encountered an issue with importing a custom Prisma Client when using **Prisma 6.x** in dist folder in js. In **Prisma 5.0**, everything worked fine, but after upgrading to Prisma **6.5.0**, my project fails to properly import the generated client.  

### **Steps to Reproduce:**  
1. I use a **custom `output` path** in `schema.prisma` to generate multiple clients:  
   ```prisma
   generator client {
     provider = "prisma-client-js"
     output   = "../../../node_modules/@prisma/client/users"
   }
   ```  
2. I generate the client using:  
   ```sh
   pnpm prisma generate
   ```  
3. When I try to import the client in my NestJS project:  
  ```js
  module.exports = require("./@prisma/client/users/default.js");
  ```
   I get the following error:  
   ```
   Error: Cannot find module 'D:\projects\github\Gomin\node_modules\@prisma\client\users'
   ```  
And everything works normaly on building stage in typescript
4. Checking `node_modules/@prisma/client/users/`, I see that **all required files exist**, including `index.js`, `default.js`, and `query_engine-windows.dll.node`. However, Prisma **still fails to import it properly**.

### **Questions & Suggestions**  
1. Is this a known issue with Prisma 6.x?  
2. Has the import behavior changed in a way that affects custom client outputs?  
3. Could this be a `pnpm`-specific issue, or is it related to how Prisma now handles `output` paths?  

Would appreciate any insights or fixes. Thanks! 🚀  

### Severity

⚠️ Major: Breaks core functionality (e.g., migrations fail)

### Reproduction

**Repository for reproduction:** [[Gomin](https://github.com/Dmutre/Gomin)]  

### **What I Expected to Happen**  
- The custom Prisma Client should be **importable** when generated inside `node_modules/@prisma/client/users/`, just like in Prisma 5.x.  
- Prisma should correctly resolve the client path without manual fixes.  

---

### **What Actually Happened**  
- Prisma 6.x **fails to import the generated client** despite the files being present.  
- Running `require.resolve('@prisma/client/users')` in `main.js` throws a **"Cannot find module"** error.  
- Manually changing `index.js` inside `main.js` to:
  ```js
  module.exports = require("./@prisma/client/users/default.js");
  ```
  **fixes the issue**, but this should not be required manually.  

### Frequency

Consistently reproducible

### Does this occur in development or production?

Both development and production

### Is this a regression?

Yes, last worked in Prisma 5.0.0, broke in 5.9.0 probably (what I found on Internet)

### Workaround

Downgrading to Prisma 5.0.0 fixes it

### Prisma Schema & Queries

```prisma
generator client {
  provider = "prisma-client-js"
  output   = "../../../node_modules/@prisma/client/users"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL_USERS")
}

model User {
  id                  String      @id @default(uuid())
  email               String      @unique
  username            String      @unique
  firstName           String      @map("first_name")
  lastName            String      @map("last_name")
  password            String
  bio                 String?
  emailVerified       Boolean     @default(false) @map("email_verified")
  twoFaEnabled        Boolean     @default(false) @map("two_fa_enabled")

  createdAt           DateTime    @default(now()) @map("created_at")
  updatedAt           DateTime    @default(now()) @updatedAt @map("updated_at")

  tokens              Token[]
  sessions            Session[]
  files               File[]
  userSetting         UserSettings?

  @@map("users")
}

model UserSettings {
  id                  String      @id @default(uuid())
  user                User        @relation(fields: [userId], references: [id], onDelete: Cascade)
  userId              String      @map("user_id") @unique
  sessionDuration     Int         @default(30) @map("session_duration") // Session duration in days

  createdAt           DateTime    @default(now()) @map("created_at")
  updatedAt           DateTime    @default(now()) @updatedAt @map("updated_at")

  @@map("user_settings")
}


enum TokenType {
  EMAIL
  TWO_FA
  SESSION
}

model Token {
  id                  String      @id @default(uuid())
  value               String
  type                TokenType
  user                User        @relation(references: [id], fields: [userId], onDelete: Cascade)
  userId              String      @map("user_id")
  expiresAt           DateTime?

  createdAt           DateTime    @default(now()) @map("created_at")
  updatedAt           DateTime    @default(now()) @updatedAt @map("updated_at")

  session             Session?

  @@map("tokens")
}

model Session {
  id                  String      @id @default(uuid())
  deviceName          String      @map("device_name")
  token               Token?      @relation(references: [id], fields: [tokenId], onDelete: SetNull)
  tokenId             String?     @unique @map("token_id")
  user                User        @relation(references: [id], fields: [userId], onDelete: Cascade)
  userId              String      @map("user_id")
  ipAddress           String      @map("ip_address")
  userAgent           String      @map("user_agent")

  createdAt           DateTime    @default(now()) @map("created_at")
  updatedAt           DateTime    @default(now()) @updatedAt @map("updated_at")

  @@map("sessions")
}

model File {
  id                  String      @id @default(uuid())
  fileName            String      @map("file_name")
  fileExtension       String      @map("file_extension")
  fileSize            Int         @map("file_size")
  mimeType            String      @map("mime_type")
  owner               User?       @relation(references: [id], fields: [ownerId], onDelete: SetNull)
  ownerId             String?     @map("owner_id")
  storagePath         String      @unique @map("storage_path")
  bucket              String

  createdAt           DateTime    @default(now()) @map("created_at")
  updatedAt           DateTime    @default(now()) @updatedAt @map("updated_at")

  @@map("files")
}
```
```ts
// Add relevant Prisma Client query
```

### Logs & Debug Info

```
// Debug logs here
```

### **Additional Information**  
- **Node.js version:** 22.14.0  
- **Prisma version:** 6.5.0  
- **Package manager:** `pnpm`  
- **OS:** Windows  

### Prisma Version

6.5.0

**Comment by FGoessler** [comment]
Hi @Dmutre 👋 

Could you try to use a custom output path that is not inside `node_modules`? An ensure that you package.json not only includes `prisma` as a dev dependency, but also `@prisma/client` as a regular dependency?

We are also working on a new ESM compatible generator that should fix some known issues and limitations and quirks of our current output. A preview version should be released with Prisma v6.6.0. Especially issues with monorepos and pnpm should be addressed by this.
