### PR TITLE
ORM config paths resolve against the file that declared them

### PR DESCRIPTION
**Pull request by wmadden-electric**
## What this changes

The unified CLI now discovers `prisma.config.ts` from the working directory up to the repo root and merges every file it finds, one key at a time. That means an `orm` section declared in, say, `packages/db/prisma.config.ts` now reaches a command run from the repo root — and resolving that section's `./migrations` or `./contract.json` against the working directory pointed at the wrong directory.

`@prisma/cli-engine` 0.3.0 gives a section validator the provenance of the value it validates: which file on the chain declared each top-level key. The `orm` section validator now uses it.

- `contract.source.inputs`, `contract.output` and `migrations.dir` resolve against the directory of the config file that declared `contract` or `migrations`. When those two keys come from different files on the chain, each resolves against its own file.
- An absent `migrations` still defaults to `migrations/`, but now beside the nearest declaring file rather than beside the caller.
- Absolute paths pass through untouched.
- Because the validator now returns absolute paths, `defineOrmCommand` no longer re-resolves the config it hands a handler. Its cwd-anchored `finalizeConfig` call is gone.
- `loadOrmConfig` returns the engine's new config shape — a chain of files rather than one file. This repo's bin reads a single `prisma.config.ts`, so the chain holds that one file and every key's provenance names it.
- `@internal/config-loader` now exports `finalizeContractConfig` and `finalizeMigrationsConfig`, the two halves of `finalizeConfig` the validator needs to resolve each key against its own directory.

## Verification

`@prisma/cli-engine` 0.3.0 is not on npm yet, so this was verified against a locally packed 0.3.0 tarball wired in through a temporary pnpm override. The override and its lockfile churn were reverted before committing; the diff pins nothing new.

Against the real 0.3.0 build:

- `@internal/cli`: `pnpm typecheck` clean (source and tests), `pnpm test` 1442 tests in 115 files, all passing.
- `@internal/config-loader`: `pnpm typecheck` clean, 46 tests passing.
- `pnpm lint:deps`, `pnpm check:conformance` and `biome check` on the changed trees: clean.
- `pnpm test:packages` across the whole workspace: 1172 of 1176 test files pass. The failures are covered below.

## This does not go green yet

Two things have to happen before CI can pass, and neither belongs in this PR.

**1. `@prisma/cli-engine` 0.3.0 has to publish** (prisma/prisma-cli#233). Until then the pin stays at 0.2.3, where `SectionProvenance` does not exist and the engine calls `validate` with one argument. The change is inert and red either way, which is why this is a draft.

**2. The repo has to stop importing `defineConfig`.** 0.3.0 removes the deprecated `defineConfig` alias from `@prisma/cli-engine`. 306 files in this repo — mostly test fixtures and example `prisma.config.ts` files — still imported it, and they fail at runtime under 0.3.0 with `defineConfig is not a function`. That is what the two `@internal/cli-telemetry` failures in the run above are.

**#30129 is the prerequisite for this PR and does that rename.** It is mergeable today: `definePrismaConfig` has existed since engine 0.2.0, and on the pinned 0.2.3 the two names are the same function object, so the sweep is behaviour-neutral. Merge #30129, then move the pin, then this PR goes green.

The other two failures in that run are unrelated: `@prisma/orm-framework`'s `module-identity` test tripped over a leftover gitignored `skills/prisma-8` directory, and one `@internal/adapter-postgres` planner test failed under parallel load and passes on its own.

## Follow-up worth noting

`finalizeConfig` in `@internal/config-loader` now has no production caller — only its own tests. It resolves an entire config against a single directory, which is exactly the behaviour this PR removes. Deleting it (and its test file) is a reasonable cleanup, left out here to keep the diff readable.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Review by wmadden — APPROVED** [review]

**Comment by wmadden-electric** [comment]
Superseded by #30372, which merged 2026-09-24. #30372 declares the `orm` section with the engine's `configSchema` and lets engine 0.6.x resolve path fields against the declaring file. That delivers this PR's outcome without the hand-written validator. The fixture renames this branch carried are already on main.

**Comment by damiommccreary** [comment]
I’m Bearish against whales
