### ISSUE TITLE
Prisma doesn't work in a Turborepo repo with nextjs > 13.1.1 with Prisma

### ISSUE THREAD

**Issue by ashburnham** [prisma/prisma#22510]
### Bug description

When working with a Turborepo repo and Nextjs using Prisma, there are multiple issues that have been resolved using [this plugin](https://www.prisma.io/docs/orm/more/help-and-troubleshooting/help-articles/nextjs-prisma-client-monorepo).

However, when upgrading to Next 13.4.1 it stops working and gives an error

```
ai-api:build: - info Creating an optimized production build...
--
18:07:43.730 | ai-api:build: Failed to compile.
18:07:43.730 | ai-api:build:
18:07:43.731 | ai-api:build: HookWebpackError: Cannot find module '.prisma/client'
18:07:43.731 | ai-api:build: Require stack:
18:07:43.731 | ai-api:build: - /vercel/path0/node_modules/@prisma/nextjs-monorepo-workaround-plugin/index.js
18:07:43.731 | ai-api:build: - /vercel/path0/apps/ai-api/next.config.js
18:07:43.731 | ai-api:build:     at makeWebpackError (/vercel/path0/apps/ai-api/node_modules/next/dist/compiled/webpack/bundle5.js:28:311139)
18:07:43.731 | ai-api:build:     at /vercel/path0/apps/ai-api/node_modules/next/dist/compiled/webpack/bundle5.js:28:105980
18:07:43.731 | ai-api:build:     at eval (eval at create (/vercel/path0/apps/ai-api/node_modules/next/dist/compiled/webpack/bundle5.js:13:28867), <anonymous>:34:1)

```

To make it work with 13.1.1, as well as adding the plugin, I had to add this script to my build process

This is the package.json for the app

```package.json
{
  "name": "ai-api",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "next dev -- -p 3001",
    "build": "npm run exract-prisma && next build",
    "start": "next start",
    "lint": "next lint",
    "postinstall": "chmod +x ../../scripts/extract-prisma.sh && ../../scripts/extract-prisma.sh $PWD",
    "exract-prisma": "chmod +x ../../scripts/extract-prisma.sh && ../../scripts/extract-prisma.sh $PWD"
  },
  "dependencies": {
    "@hirespace/hs-suite-ai-api-sdk": "*",
    "@prisma/client": "^4.12.0",
    "ai": "^2.2.12",
    "langchain": "^0.0.187",
    "next": "^13.1.1",
    "web-streams-polyfill": "^4.0.0-beta.3",
    "webpack-filter-warnings-plugin": "^1.2.1"
  },
  "devDependencies": {
    "@hirespace/eslint-config-hs-suite": "*",
    "@hirespace/hs-suite-tsconfig": "^1.0.0",
    "@types/node": "18.15.11",
    "@types/react": "18.0.31",
    "@typescript-eslint/eslint-plugin": "^6.15.0",
    "@typescript-eslint/parser": "^6.15.0",
    "eslint-import-resolver-typescript": "^3.6.1",
    "typescript": "^5.0.2"
  }
}
  ```

and this is the script that is references

```extract-prisma.sh
# Save current path
CURRENT_PATH=$PWD
echo "Start here"
echo $PWD

# Move to parent package folder
PARENT_PACKAGE_PATH=$1
cd "$PARENT_PACKAGE_PATH"

# Create the prisma folder if it doesn't exist
mkdir -p prisma

# Copy the schema.prisma file if it doesn't exist
if [ ! -f prisma/schema.prisma ]; then
  if [ -f ../../node_modules/@hirespace/dal-sql/prisma/schema.prisma ]; then
    echo "Copying from ../../node_modules" 
    cp ../../node_modules/@hirespace/dal-sql/prisma/schema.prisma ./prisma/schema.prisma
  fi
fi

echo "About to generate prisma client to this location"
echo $PWD

# Generate prisma client using npx
npx prisma generate

# Put one at the root of the project as well for good measure
cp -r prisma ../..

# Remove the src folder if it exists (use with caution)
if [ -d src ]; then
  rm -rf ./src
fi

# Print where the prisma folders are
cd ../..
find . -type d -name prisma

# Return to current path
cd "$CURRENT_PATH"

echo "Back here"
echo $PWD
```

Anyway, it builds on Nextjs 13.1.1 but gives an error on Nextjs 13.4.1 when on Vercel (but works locally)

I would post on the next.js repo too but it's a large private repo and I've wasted a couple of days on this so don't have time at the moment to create a public minimal reproduction. So instead I'm putting it here for others to find in case they are also wasting lots of time!

Perhaps they can add further context.

### How to reproduce

`npx turbo run build --filter=apps/ai-api`

### Expected behavior

It would build without any errors.

### Prisma information

```prisma
generator client {
  provider      = "prisma-client-js"
  output        = "./client"
  binaryTargets = ["native", "rhel-openssl-1.0.x"]
}

datasource db {
  provider = "sqlserver"
  url      = env("DATABASE_URL")
}
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

This all happens on Vercel build machines so I don't know the environment...

### Prisma Version

```
4.12.0
```

**Comment by jkomyno** [comment]
Hi @ashburnham, thank you for opening this issue.
Have you perhaps tried to upgrade Prisma to the latest version (`prisma@5.7.1`) to see whether Turborepo is able to identify it?

Alternatively, can you also please open a new issue in Turborepo's repository? It's possible that some breaking change happened on their side, and they may not be aware of it. 

Also, I understand setting up a reproduction could be time-consuming, but that'd be the best way of allowing library maintainers to investigate this issue and fix it. Thanks!

**Comment by jkomyno** [comment]
Possibly related: https://github.com/prisma/prisma/issues/22530, https://github.com/vercel/next.js/issues/60110.

**Comment by jorgerodrigues** [comment]
I've this issue on and off in our deployments and I'm not convinced that this is a turbo or prisma issue. 
In fact, recently I had a case where the preview deployment worked as expected but then when merged and built into production it would break with this error. 

Given that turbo is part of the vercel ecosystem and prisma is a vastly popular tool at the moment, I'd think it would make sense to go a little deeper on this issue.

**Comment by ErikDakoda** [comment]
I am working on a next.js+prisma+turbo configuration, and I am getting inconsistent build behavior on Vercel. If I keep "Redeploy"-ing the same code sometimes it works, and sometimes it can't find the prisma engine. This is clearly a bug either vercel, prisma, or nextjs-monorepo-workaround-plugin. Extremely frustrating.

**Comment by janpio** [comment]
Can someone provide a reproduction we can try ourselves? Without that it will be super hard for anyone to dive into this topic to figure it out. Thanks!

**Comment by jorgerodrigues** [comment]
> Can someone provide a reproduction we can try ourselves? Without that it will be super hard for anyone to dive into this topic to figure it out. Thanks!

I'll try to recreate something in the coming days. With that said, as you can read in the comments above the issue is often hit-or-miss so a reproduction will most likely be very much hit-or-miss as well.

**Comment by JoseGrillo** [comment]
greetings, you managed to find a viable solution... thank you for your comments.

**Comment by JoseGrillo** [comment]
greetings, you managed to find a viable solution... thank you for your comments.

**Comment by davecarlson** [comment]
How do you use nextjs-monorepo-workaround-plugin without webpack ?

We're using turbopack locally, and get the following warning in the console:
  ⚠ Webpack is configured while Turbopack is not, which may cause problems.
@:dev:  ⚠ See instructions if you need to configure Turbopack:
@:dev:   https://nextjs.org/docs/app/api-reference/next-config-js/turbo

**Comment by Alekzv9** [comment]
I just created a mono repo with `with-prisma` example.

I'm trying to use latest prisma version and connect to planetscale with the planetscale adapter

```
import { Client } from '@planetscale/database';
import { PrismaPlanetScale } from '@prisma/adapter-planetscale';
import { PrismaClient } from '@prisma/client';
export * as SQL from '@prisma/client/sql';
import { fetch as undiciFetch } from 'undici';
```

When I try to use the client I get this error

```
Module not found: Can't resolve '../../.prisma/client/sql/index.mjs'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
../../packages/database/src/client.ts
./app/page.tsx

```
