### ISSUE TITLE
After upgrading from 3.2.1 to 3.3.0 I get a 'Error: Cannot find module 'os''

### ISSUE THREAD

**Issue by jrmyio** [prisma/prisma#10058]
### Bug description

I have an issue where my webpack-built cli application throws an error 
`Error: Cannot find module 'os'` after upgrading Prisma from 3.2.1 to 3.3.0.

When googling I found another thread which seems to be the same issue:
https://answers.netlify.com/t/nextjs-page-with-server-side-logic-throws-error-cannot-find-module-os/46431

When looking at the build output it looks like there is something going wierd / different with the imports.

When using Prisma **3.2.1** the output for using 'supports-color' looks like this (this is the working code):

```js
// ../../node_modules/.pnpm/supports-color@7.2.0/node_modules/supports-color/index.js
var require_supports_color2 = __commonJS2((exports2, module2) => {
  "use strict";
  var os = __webpack_require__(22037);
  var tty = __webpack_require__(76224);
  var hasFlag = require_has_flag2();
  var {env} = process;
  var forceColor;
  if (hasFlag("no-color") || hasFlag("no-colors") || hasFlag("color=false") || hasFlag("color=never")) {
    forceColor = 0;
  } else if (hasFlag("color") || hasFlag("colors") || hasFlag("color=true") || hasFlag("color=always")) {
    forceColor = 1;
  }
  if ("FORCE_COLOR" in env) {
    if (env.FORCE_COLOR === "true") {
      forceColor = 1;
    } else if (env.FORCE_COLOR === "false") {
      forceColor = 0;
    } else {
      forceColor = env.FORCE_COLOR.length === 0 ? 1 : Math.min(parseInt(env.FORCE_COLOR, 10), 3);
    }
  }
  function translateLevel(level) {
    if (level === 0) {
      return false;
    }
    return {
      level,
      hasBasic: true,
      has256: level >= 2,
      has16m: level >= 3
    };
  }
  __name(translateLevel, "translateLevel");
  function supportsColor(haveStream, streamIsTTY) {
    if (forceColor === 0) {
      return 0;
    }
    if (hasFlag("color=16m") || hasFlag("color=full") || hasFlag("color=truecolor")) {
      return 3;
    }
    if (hasFlag("color=256")) {
      return 2;
    }
    if (haveStream && !streamIsTTY && forceColor === void 0) {
      return 0;
    }
    const min2 = forceColor || 0;
    if (env.TERM === "dumb") {
      return min2;
    }
    if (process.platform === "win32") {
      const osRelease = os.release().split(".");
      if (Number(osRelease[0]) >= 10 && Number(osRelease[2]) >= 10586) {
        return Number(osRelease[2]) >= 14931 ? 3 : 2;
      }
      return 1;
    }
    if ("CI" in env) {
      if (["TRAVIS", "CIRCLECI", "APPVEYOR", "GITLAB_CI", "GITHUB_ACTIONS", "BUILDKITE"].some((sign2) => sign2 in env) || env.CI_NAME === "codeship") {
        return 1;
      }
      return min2;
    }
    if ("TEAMCITY_VERSION" in env) {
      return /^(9\.(0*[1-9]\d*)\.|\d{2,}\.)/.test(env.TEAMCITY_VERSION) ? 1 : 0;
    }
    if (env.COLORTERM === "truecolor") {
      return 3;
    }
    if ("TERM_PROGRAM" in env) {
      const version = parseInt((env.TERM_PROGRAM_VERSION || "").split(".")[0], 10);
      switch (env.TERM_PROGRAM) {
        case "iTerm.app":
          return version >= 3 ? 3 : 2;
        case "Apple_Terminal":
          return 2;
      }
    }
    if (/-256(color)?$/i.test(env.TERM)) {
      return 2;
    }
    if (/^screen|^xterm|^vt100|^vt220|^rxvt|color|ansi|cygwin|linux/i.test(env.TERM)) {
      return 1;
    }
    if ("COLORTERM" in env) {
      return 1;
    }
    return min2;
  }
  __name(supportsColor, "supportsColor");
  function getSupportLevel(stream) {
    const level = supportsColor(stream, stream && stream.isTTY);
    return translateLevel(level);
  }
  __name(getSupportLevel, "getSupportLevel");
  module2.exports = {
    supportsColor: getSupportLevel,
    stdout: translateLevel(supportsColor(true, tty.isatty(1))),
    stderr: translateLevel(supportsColor(true, tty.isatty(2)))
  };
});
```

When using Prisma **3.3.0** the output for using 'supports-color' looks like this (the __require('os') fails, so would the tty import):
```js
var require_supports_color2 = __commonJS2({
  "../../node_modules/.pnpm/supports-color@7.2.0/node_modules/supports-color/index.js"(exports2, module2) {
    "use strict";
    var os2 = __require("os");
    var tty = __require("tty");
    var hasFlag = require_has_flag2();
    var { env } = process;
    var forceColor;
    if (hasFlag("no-color") || hasFlag("no-colors") || hasFlag("color=false") || hasFlag("color=never")) {
      forceColor = 0;
    } else if (hasFlag("color") || hasFlag("colors") || hasFlag("color=true") || hasFlag("color=always")) {
      forceColor = 1;
    }
    if ("FORCE_COLOR" in env) {
      if (env.FORCE_COLOR === "true") {
        forceColor = 1;
      } else if (env.FORCE_COLOR === "false") {
        forceColor = 0;
      } else {
        forceColor = env.FORCE_COLOR.length === 0 ? 1 : Math.min(parseInt(env.FORCE_COLOR, 10), 3);
      }
    }
    function translateLevel(level) {
      if (level === 0) {
        return false;
      }
      return {
        level,
        hasBasic: true,
        has256: level >= 2,
        has16m: level >= 3
      };
    }
    __name(translateLevel, "translateLevel");
    __name2(translateLevel, "translateLevel");
    function supportsColor(haveStream, streamIsTTY) {
      if (forceColor === 0) {
        return 0;
      }
      if (hasFlag("color=16m") || hasFlag("color=full") || hasFlag("color=truecolor")) {
        return 3;
      }
      if (hasFlag("color=256")) {
        return 2;
      }
      if (haveStream && !streamIsTTY && forceColor === void 0) {
        return 0;
      }
      const min2 = forceColor || 0;
      if (env.TERM === "dumb") {
        return min2;
      }
      if (process.platform === "win32") {
        const osRelease = os2.release().split(".");
        if (Number(osRelease[0]) >= 10 && Number(osRelease[2]) >= 10586) {
          return Number(osRelease[2]) >= 14931 ? 3 : 2;
        }
        return 1;
      }
      if ("CI" in env) {
        if (["TRAVIS", "CIRCLECI", "APPVEYOR", "GITLAB_CI", "GITHUB_ACTIONS", "BUILDKITE"].some((sign2) => sign2 in env) || env.CI_NAME === "codeship") {
          return 1;
        }
        return min2;
      }
      if ("TEAMCITY_VERSION" in env) {
        return /^(9\.(0*[1-9]\d*)\.|\d{2,}\.)/.test(env.TEAMCITY_VERSION) ? 1 : 0;
      }
      if (env.COLORTERM === "truecolor") {
        return 3;
      }
      if ("TERM_PROGRAM" in env) {
        const version = parseInt((env.TERM_PROGRAM_VERSION || "").split(".")[0], 10);
        switch (env.TERM_PROGRAM) {
          case "iTerm.app":
            return version >= 3 ? 3 : 2;
          case "Apple_Terminal":
            return 2;
        }
      }
      if (/-256(color)?$/i.test(env.TERM)) {
        return 2;
      }
      if (/^screen|^xterm|^vt100|^vt220|^rxvt|color|ansi|cygwin|linux/i.test(env.TERM)) {
        return 1;
      }
      if ("COLORTERM" in env) {
        return 1;
      }
      return min2;
    }
    __name(supportsColor, "supportsColor");
    __name2(supportsColor, "supportsColor");
    function getSupportLevel(stream3) {
      const level = supportsColor(stream3, stream3 && stream3.isTTY);
      return translateLevel(level);
    }
    __name(getSupportLevel, "getSupportLevel");
    __name2(getSupportLevel, "getSupportLevel");
    module2.exports = {
      supportsColor: getSupportLevel,
      stdout: translateLevel(supportsColor(true, tty.isatty(1))),
      stderr: translateLevel(supportsColor(true, tty.isatty(2)))
    };
  }
});
```
The __require function above looks like this:
```js
var __require = /* @__PURE__ */ ((x) =>  true ? __webpack_require__(91426) : 0)(function(x) {
  if (true)
    return __webpack_require__(91426).apply(this, arguments);
  throw new Error('Dynamic require of "' + x + '" is not supported');
});
``` 
and 91426
```js
/***/ 91426:
/***/ ((module) => {

function webpackEmptyContext(req) {
	var e = new Error("Cannot find module '" + req + "'");
	e.code = 'MODULE_NOT_FOUND';
	throw e;
}
webpackEmptyContext.keys = () => ([]);
webpackEmptyContext.resolve = webpackEmptyContext;
webpackEmptyContext.id = 91426;
module.exports = webpackEmptyContext;

/***/ }),
```

### How to reproduce

The setup is pretty specfic but I hope the file examples show the reason why its failing.

### Expected behavior

Native node.js imports should just import without throwing an error.

### Prisma information

The error happends whenever you have prisma 3.3.0 inside your build.

### Environment & setup

OS: Ubuntu
NodeVersion: Tried 12 and 16.
Webpack 5

### Prisma Version

3.3.0

**Comment by Toktik** [comment]
Have same issue after upgrading from 2.23.0 to 3.3.0.

Our setup is done using nrwl/nx.

**Comment by iMiroslav** [comment]
The same for  3.4.0.

**Comment by Axxxx0n** [comment]
Have same issue after upgrading from 3.21.0 to 3.3.0. on node:16.13.0-alpine

**Comment by SynergyEvolved** [comment]
Same.

**Comment by quinnjr** [comment]
Having the same issue, but it seems to be something that's more of an issue of `supports-color` and `chalk` using ESM modules and the `node` import protocol now.

Still haven't found a way to resolve the issues.

**Comment by tpinne** [comment]
Have the same issue with `3.4.1` within a NextJS app. If it is deployed to Netlify the issue occurs. But strangely when it is deployed to vercel it runs smoothly.

**Comment by Reegan01** [comment]
Have the same issue with `NextJS + Netlify` hosting. Kindly provide a solution 

`"Error: Cannot find module 'os'"`

<img width="782" alt="Screenshot 2021-11-08 at 1 21 26 AM" src="https://user-images.githubusercontent.com/7336944/140659726-71a790b6-73a1-4098-88b5-5714eac686e2.png">

**Comment by tonivj5** [comment]
Same issue here, nx workspace (Webpack 5) with local output client. I have changed my imports to use `@prisma/client` instead of a local import (`app/[...]/client`)

```prisma
generator client {
  provider        = "prisma-client-js"
   // Commenting this line, it works
  output          = "./client"
  previewFeatures = ["interactiveTransactions"]
}
```

**Comment by tonivj5** [comment]
Reproduction: https://github.com/tonivj5/prisma-issue-10058

There're two commits
- Works https://github.com/tonivj5/prisma-issue-10058/commit/0654196af804f07ff51934c38fdd1a703254f669 (3.2.1)
- Does NOT works https://github.com/tonivj5/prisma-issue-10058/commit/2399b32fce4de6ff435e0c3700fc990d1b8fdb92 (3.4.1)

Steps:
- npm i
- npm run start
- Depends on which version, it works or not...

**Comment by quinnjr** [comment]
Additional reproduction repo: https://github.com/quinnjr/webpack-os-error-issue

Steps to observer:

1. Install dependencies and setup Prisma correctly
2. Generate Prisma client
3. run `npm run build:ssr`
4. Wait for webpack to finish bundling frontend and backend.
5. Run `npm run serve:ssr`

**Comment by quinnjr** [comment]
Upstream in `webpack` suggests adding `externals: { "node:os": "{}" }` to your webpack config, but I can't get it working in my reproduction repo.

@tonivj5 can you try adding the configuration to your repo and seeing if it fixes the problem?

**Comment by tonivj5** [comment]
> Upstream in `webpack` suggests adding `externals: { "node:os": "{}" }` or `externals: {'node:os': 'commonjs2 os' }` to your webpack config, but I can't get it working in my reproduction repo.
> 
> @tonivj5 can you try adding the configuration to your repo and seeing if it fixes the problem?

@quinnjr it doesn't work...

btw, logs (not relationed with your suggested changes):
```bash
WARNING in ./libs/database/client/runtime/index.js 81:73-80
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./libs/database/client/runtime/index.js 85:15-22
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

```

**Comment by alexander-akait** [comment]
In `@prisma/client@3.2.0` code has `var os = require("os");` (i.e. `require`), so webpack can handle it, because it is statically analyzable, in `v3.3.0` and above code is `var os2 = __require("os");` (i.e. no more simple `require`, now it is helper), so webpack can't handle it, because it is not statically analyzable. 

What is solutions?
- Do not bundle client, because bundler on application side will do it
- Avoid using `__require` helper, maybe `esbuild` has option for this
- polyfill Node.js modules on esbuild side (don't know possible it or not)
- Avoid usage Node.js modules on browser side (maybe hard), but it is good solution, most of them from dependencies, for example `supports-color` package, why you need it in browser? Also it reduce bundle size very well

Note - this problems is not related webpack itself, it happens with other bundlers too, because bundlers can't bundle non statically analyzable code

**Comment by millsp** [comment]
Hey folks, would you mind giving this version a shot `3.5.0-integration-fix-bundlers-broken-require.1`?

**Comment by quinnjr** [comment]
Getting the following error in the webpack bundle when trying to run the server for `@nestjs/ng-universal`:

```sh
const dirname = findSync(process.cwd(), [
                ^

TypeError: findSync is not a function
    at Object../node_modules/.pnpm/@prisma+client@3.5.0-integration-fix-bundlers-broken-require.1_prisma@3.2.1/node_modules/.prisma/client/index.js (/home/joseph/Projects/cs-portfolio/CIS3950/agineek-website/dist/agineek-website/server/main.js:65930:17)
    at __webpack_require__ (/home/joseph/Projects/cs-portfolio/CIS3950/agineek-website/dist/agineek-website/server/main.js:810554:42)
    at Object../node_modules/.pnpm/@prisma+client@3.5.0-integration-fix-bundlers-broken-require.1_prisma@3.2.1/node_modules/@prisma/client/index.js (/home/joseph/Projects/cs-portfolio/CIS3950/agineek-website/dist/agineek-website/server/main.js:66130:16)
    at __webpack_require__ (/home/joseph/Projects/cs-portfolio/CIS3950/agineek-website/dist/agineek-website/server/main.js:810554:42)
    at Object../server/database/database.service.ts (/home/joseph/Projects/cs-portfolio/CIS3950/agineek-website/dist/agineek-website/server/main.js:676417:18)
    at __webpack_require__ (/home/joseph/Projects/cs-portfolio/CIS3950/agineek-website/dist/agineek-website/server/main.js:810554:42)
    at Object../server/authentication/authentication.service.ts (/home/joseph/Projects/cs-portfolio/CIS3950/agineek-website/dist/agineek-website/server/main.js:675880:28)
    at __webpack_require__ (/home/joseph/Projects/cs-portfolio/CIS3950/agineek-website/dist/agineek-website/server/main.js:810554:42)
    at Object../server/authentication/authentication.module.ts (/home/joseph/Projects/cs-portfolio/CIS3950/agineek-website/dist/agineek-website/server/main.js:675824:34)
    at __webpack_require__ (/home/joseph/Projects/cs-portfolio/CIS3950/agineek-website/dist/agineek-website/server/main.js:810554:42)
```

**Comment by millsp** [comment]
Thanks for the feedback, would you mind sharing your generated Prisma Client `index.js`?

**Comment by quinnjr** [comment]
@millsp https://gist.github.com/quinnjr/33bfff5cb4e8265b9bb7c98b632f3abc

**Comment by millsp** [comment]
If you manually edit (and skip regeneration) https://gist.github.com/quinnjr/33bfff5cb4e8265b9bb7c98b632f3abc#file-index-js-L59 to have `@prisma/client/runtime/index` does it solve it?

**Comment by quinnjr** [comment]
No, it does not.

The bundled line for line #59 looks as such:

```javascript
const { findSync } = __webpack_require__(/*! @prisma/client/runtime/index */ "./node_modules/.pnpm/@prisma+client@3.5.0-integration-fix-bundlers-broken-require.1_prisma@3.2.1/node_modules/@prisma/client/runtime/index.js")
```

**Comment by tonivj5** [comment]
Same issue here:
```ts
/.../webpack:/.../database/client/index.js:62
const dirname = findSync(process.cwd(), [
                ^
TypeError: findSync is not a function
```

**Comment by millsp** [comment]
This should be fixed now in `3.5.0-integration-fix-bundlers-broken-require.2` (@tonivj5 @quinnjr), would you mind to give it another try? Thanks :)

**Comment by quinnjr** [comment]
Confirmed working on my application.

Thanks for the quick turn-around time @millsp.

**Comment by tonivj5** [comment]
@millsp it works to me too! 🚀 

But these warnings appears only If I use local client generation
```ts

WARNING in ./libs/.../database/client/runtime/index.js 81:73-80
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./libs/.../database/client/runtime/index.js 85:15-22
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

webpack compiled with 2 warnings (a1699459dc9c42dd)

```

If I import from `@prisma/client` no warnings are showed

**Comment by millsp** [comment]
Thank you all for the feedback it was really useful. And @tonivj5, your reported issue/comment has also been fixed.
